#!/usr/bin/env python3
"""pocgen.py — PoC / vulnerability report generator (v2.5.0).

Generates a structured markdown vulnerability report suitable for bug bounty
submissions (HackerOne/Bugcrowd/Immunefi style).

Usage:
  python3 pocgen.py --title "Open redirect on example.com" --severity medium \
      --target example.com --steps "1. visit ..." --impact "..." --out report.md
  python3 pocgen.py --interactive
"""
import argparse
import os
from datetime import datetime

TEMPLATE = """# {title}

| Field | Value |
|---|---|
| Target | {target} |
| Severity | {severity} |
| Type | {vuln_type} |
| Discovered | {date} |
| Reporter | {reporter} |

## Summary

{summary}

## Steps to Reproduce

{steps}

## Proof of Concept

```
{poc}
```

## Impact

{impact}

## Affected Endpoints

{endpoints}

## Remediation

{remediation}

## References

{references}

---
*Generated by Bug Bounty Arsenal v2.5.0 — {date}*
"""

SEVERITY_GUIDE = {
    "critical": "Immediate exploitation possible; full compromise of confidentiality/integrity/availability.",
    "high": "Significant impact; sensitive data exposure or major functionality abuse.",
    "medium": "Limited impact; requires specific conditions or partial data exposure.",
    "low": "Minor impact; informational or hard-to-exploit issue.",
    "info": "Best-practice deviation; no direct security impact.",
}

REMEDIATION_GUIDE = {
    "xss": "Encode output contextually; implement CSP; validate/sanitize input.",
    "sqli": "Use parameterized queries/prepared statements; ORM; least-privilege DB user.",
    "open_redirect": "Whitelist redirect destinations; avoid user-controlled URLs in redirects.",
    "idor": "Enforce server-side authorization checks per object; use indirect references.",
    "ssrf": "Egress filtering; deny private IP ranges; validate/allowlist URLs.",
    "csrf": "Implement anti-CSRF tokens; SameSite cookies; verify Origin/Referer.",
    "default": "Apply defense in depth; validate input, encode output, enforce authz.",
}

def main():
    ap = argparse.ArgumentParser(description="PoC report generator")
    ap.add_argument("--title", default="Untitled vulnerability")
    ap.add_argument("--target", default="")
    ap.add_argument("--severity", default="medium",
                    choices=["critical", "high", "medium", "low", "info"])
    ap.add_argument("--vuln-type", dest="vuln_type", default="")
    ap.add_argument("--summary", default="")
    ap.add_argument("--steps", default="(describe steps)")
    ap.add_argument("--poc", default="(curl/browser reproduction)")
    ap.add_argument("--impact", default="")
    ap.add_argument("--endpoints", default="")
    ap.add_argument("--remediation", default="")
    ap.add_argument("--references", default="")
    ap.add_argument("--reporter", default=os.environ.get("USER", "researcher"))
    ap.add_argument("--out", default="poc_report.md")
    args = ap.parse_args()

    if not args.summary:
        args.summary = SEVERITY_GUIDE[args.severity]
    if not args.remediation:
        vt = args.vuln_type.lower()
        args.remediation = REMEDIATION_GUIDE.get(vt, REMEDIATION_GUIDE["default"])

    report = TEMPLATE.format(
        title=args.title, target=args.target, severity=args.severity.upper(),
        vuln_type=args.vuln_type or "—", date=datetime.now().strftime("%Y-%m-%d"),
        reporter=args.reporter, summary=args.summary, steps=args.steps,
        poc=args.poc, impact=args.impact or "(describe business impact)",
        endpoints=args.endpoints or "—", remediation=args.remediation,
        references=args.references or "—",
    )

    with open(args.out, "w") as f:
        f.write(report)
    print(f"[+] report -> {args.out}")
    print(f"[+] severity guidance: {SEVERITY_GUIDE[args.severity]}")

if __name__ == "__main__":
    main()
