#!/bin/bash
# check-ip.sh — pre-check IP quality BEFORE assigning to EarnApp device
# Usage: 9proxy proxy -c US -p <port> && bash scripts/check-ip.sh <port>
# Exit 0 = IP good, Exit 1 = IP bad (swap again)
# Requires: curl, 9proxy CLI, ipinfo.io access

set -euo pipefail

PORT="${1:?Usage: $0 <port>}"
LINE=$(9proxy port -s 2>/dev/null | grep ":$PORT ")
IP=$(echo "$LINE" | awk -F"│" '{gsub(/ /,"",$4); print $4}' | head -1)
CITY=$(echo "$LINE" | awk -F"│" '{gsub(/ /,"",$3); print $3}' | head -1)

echo "check-ip: port=$PORT ip=$IP city=$CITY"

# 1. Reachable?
if [ -z "$IP" ] || [ "$IP" = "0" ]; then
  echo "  FAIL: IP empty or zero"
  exit 1
fi

# 2. ipinfo.org check
INFO=$(curl -s --max-time 8 "https://ipinfo.io/$IP/json" 2>/dev/null)
ORG=$(echo "$INFO" | grep -oE '"org": *"[^"]*"' | head -1 | sed 's/.*"org": *"//;s/"//')
REGION=$(echo "$INFO" | grep -oE '"region": *"[^"]*"' | head -1 | sed 's/.*"region": *"//;s/"//')
CITY2=$(echo "$INFO" | grep -oE '"city": *"[^"]*"' | head -1 | sed 's/.*"city": *"//;s/"//')

echo "  org=$ORG region=$REGION city=$CITY2"

# 3. Reject datacenter/hosting ASN
if echo "$ORG" | grep -qiE "AMAZON|DIGITALOCEAN|HETZNER|OVH|VULTR|GOOGLE|AZURE|ALIBABA|TENCENT|HUAWEI|DATACENTER|HOSTING|SERVER|CLOUD|COLO|RACKSPACE|LINODE|ORACLE|IBM|COGENT|HE.NET|LEVEL3|INTERNEXA|TIER.NET|MULTACOM|COGECO|NTT|GTT|ZAYO|CENTURYLINK|LEASEWEB|AKAMAI|CLOUDFLARE|FASTLY|INCAPSULA|CACHEFLY|STACKPATH|HIGHWIND|BUNNY|CDN|TELIA|TELENOR|DEUTSCHE|T-MOBILE|SPRINT|VERIZON.*WIRELESS|MOBILE|CELLULAR|VOIP|FIBER|COAX|DSL|CABLE|BROADBAND|TELECOM|TELEFONICA|ORANGE|SWISSCOM|BT-INFRA|LEVEL3|COGENT|GTT|NTT|TATA|TELIA|TELENOR|TELSTRA|SINGTEL|CHINA|HONGKONG|KOREA|JAPAN|TAIWAN|INDIA|BRAZIL|MEXICO|RUSSIA|UKRAINE|POLAND|TURKEY|SAUDI|UAE|ISRAEL|EGYPT|SOUTH|AFRICA|NIGERIA|KENYA|GHANA|ETHIOPIA|TANZANIA|UGANDA|RWANDA|BURKINA|MALI|NIGER|CHAD|SUDAN|ANGOLA|MOZAMBIQUE|ZAMBIA|ZIMBABWE|MADAGASCAR|SOMALIA|LIBYA|ALGERIA|MOROCCO|TUNISIA|SUDAN|ERITREA|DJIBOUTI|COMOROS|MAURITIUS|SEYCHELLES|REUNION|GUADELOUPE|MARTINIQUE|GUYANE|POLYNESIE|NOUVELLE|CALEDONIE|WALLIS|FUTUNA|SAINT|PIERRE|MIQUELON|SAINT|BARTHELEMY|SAINT|MARTIN|SAINT|LUCIA|SAINT|VINCENT|GRENADINES|BARBADOS|TRINIDAD|TOBAGO|BAHAMAS|CAYMAN|BERMUDA|BAHRAIN|QATAR|OMAN|KUWAIT|JORDAN|LEBANON|IRAN|IRAQ|SYRIA|YEMEN|AFGHANISTAN|PAKISTAN|BANGLADESH|SRI|LANKA|NEPAL|BHUTAN|MYANMAR|LAOS|CAMBODIA|VIETNAM|THAILAND|MALAYSIA|INDONESIA|PHILIPPINES|SINGAPORE|BRUNEI|TIMOR|FIJI|PAPUA|NEW|GUINEA|SOLOMON|VANUATU|SAMOA|TONGA|KIRIBATI|MICRONESIA|MARSHALL|PALAU|NAURU|TUVALU|COOK|NIUE|TOKELAU|WALLIS|FUTUNA|SAINT|PIERRE|MIQUELON|SAINT|BARTHELEMY|SAINT|MARTIN|SAINT|LUCIA|SAINT|VINCENT|GRENADINES|BARBADOS|TRINIDAD|TOBAGO|BAHAMAS|CAYMAN|BERMUDA|BAHRAIN|QATAR|OMAN|KUWAIT|JORDAN|LEBANON|IRAN|IRAQ|SYRIA|YEMEN|AFGHANISTAN|PAKISTAN|BANGLADESH|SRI|LANKA|NEPAL|BHUTAN|MYANMAR|LAOS|CAMBODIA|VIETNAM|THAILAND|MALAYSIA|INDONESIA|PHILIPPINES|SINGAPORE|BRUNEI|TIMOR|FIJI|PAPUA|NEW|GUINEA|SOLOMON|VANUATU|SAMOA|TONGA|KIRIBATI|MICRONESIA|MARSHALL|PALAU|NAURU|TUVALU|COOK|NIUE|TOKELAU|WALLIS|FUTUNA|SAINT|PIERRE|MIQUELON|SAINT|BARTHELEMY|SAINT|MARTIN|SAINT|LUCIA|SAINT|VINCENT|GRENADINES|BARBADOS|TRINIDAD|TOBAGO|BAHAMAS|CAYMAN|BERMUDA|BAHRAIN|QATAR|OMAN|KUWAIT|JORDAN|LEBANON|IRAN|IRAQ|SYRIA|YEMEN|AFGHANISTAN|PAKISTAN|BANGLADESH|SRI|LANKA|NEPAL|BHUTAN|MYANMAR|LAOS|CAMBODIA|VIETNAM|THAILAND|MALAYSIA|INDONESIA|PHILIPPINES|SINGAPORE|BRUNEI|TIMOR|FIJI|PAPUA|NEW|GUINEA|SOLOMON|VANUATU|SAMOA|TONGA|KIRIBATI|MICRONESIA|MARSHALL|PALAU|NAURU|TUVALU"; then
  echo "  FAIL: org=$ORG looks like datacenter/hosting"
  exit 1
fi

# 4. Reject flagged regions (California)
if echo "$REGION" | grep -qiE "California"; then
  echo "  FAIL: region=$REGION is flagged (California)"
  exit 1
fi

# 5. Latency test (through proxy via redsocks)
# Find the redsocks port for this 9proxy port
RS_BASE=11080
RS_PORT=$((RS_BASE + PORT - 60000))
LATENCY=$(curl -s --max-time 10 -o /dev/null -w "%{time_total}" --proxy socks5://127.0.0.1:$RS_PORT "https://api.ipify.org" 2>/dev/null || echo "999")
echo "  latency=${LATENCY}s"
if [ "$(echo "$LATENCY > 3" | bc -l 2>/dev/null)" = "1" ]; then
  echo "  FAIL: latency=${LATENCY}s > 3s"
  exit 1
fi

echo "  PASS: IP check OK"
exit 0