#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/evidence-hygiene

Skill: EVIDENCE HYGIENE — PoC Capture & Redaction Discipline
Desc : Evidence-capture and PoC-redaction discipline for bug-bounty submissions: cookie redaction protocol (which fields to mask, Preview annotation / Burp panel hiding / DevTools workflow), PII black-bar discipline (what to mask in other-user data — names, emails, phones, faces — vs what is safe to leave — usernames, trace IDs, request bodies), HAR file sanitization (jq filters for Cookie/Set-Cookie/Authorization headers), Burp Repeater/Intruder screenshot hygiene (hide request body, show only Results table for rate-limit attacks), Chrome DevTools Console PoC patterns (credentials include so cookies are not echoed, labeled console.log), screenshot capture order, filename conventions, post-submission rotation hygiene. Use BEFORE any PoC screenshot, BEFORE attaching a HAR, or whenever preparing evidence with session cookies or other-user PII. Pairs with bugcrowd-reporting and report-writing.

Run:  python claude-bughunter-evidence-hygiene.py --help
      python claude-bughunter-evidence-hygiene.py --list
      python claude-bughunter-evidence-hygiene.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/evidence-hygiene'
TITLE = 'EVIDENCE HYGIENE — PoC Capture & Redaction Discipline'
DESCRIPTION = 'Evidence-capture and PoC-redaction discipline for bug-bounty submissions: cookie redaction protocol (which fields to mask, Preview annotation / Burp panel hiding / DevTools workflow), PII black-bar discipline (what to mask in other-user data — names, emails, phones, faces — vs what is safe to leave — usernames, trace IDs, request bodies), HAR file sanitization (jq filters for Cookie/Set-Cookie/Authorization headers), Burp Repeater/Intruder screenshot hygiene (hide request body, show only Results table for rate-limit attacks), Chrome DevTools Console PoC patterns (credentials include so cookies are not echoed, labeled console.log), screenshot capture order, filename conventions, post-submission rotation hygiene. Use BEFORE any PoC screenshot, BEFORE attaching a HAR, or whenever preparing evidence with session cookies or other-user PII. Pairs with bugcrowd-reporting and report-writing.'

PAYLOADS = {
    'main': ["name: evidence-hygiene", "description: \"Evidence-capture and PoC-redaction discipline for bug-bounty submissions: cookie redaction protocol (which fields to mask, Preview annotation / Burp panel hiding / DevTools workflow), PII black-bar discipline (what to mask in other-user data \u2014 names, emails, phones, faces \u2014 vs what is safe to leave \u2014 usernames, trace IDs, request bodies), HAR file sanitization (jq filters for Cookie/Set-Cookie/Authorization headers), Burp Repeater/Intruder screenshot hygiene (hide request body, show only Results table for rate-limit attacks), Chrome DevTools Console PoC patterns (credentials include so cookies are not echoed, labeled console.log), screenshot capture order, filename conventions, post-submission rotation hygiene. Use BEFORE any PoC screenshot, BEFORE attaching a HAR, or whenever preparing evidence with session cookies or other-user PII. Pairs with bugcrowd-reporting and report-writing.\""],
    'evidence-hygiene-poc-capture-redaction-discipline': ["The core principle: **Bug-bounty evidence is meant to convince a triager. Anything beyond that \u2014 live cookies, real-user PII, internal trace IDs that aren't useful \u2014 should not be in the evidence.**"],
    '1-two-categories-of-sensitive-data': ["Every PoC artifact (screenshot, HAR, raw HTTP request, terminal transcript) potentially contains data that needs different treatment."],
    '2-cookie-redaction-protocol': [],
    '2-1-what-must-be-masked': ["The session cookie value is the highest-value secret in any PoC. Mask:", "- The session cookie (`authn`, `session`, `sid`, `__Secure-id`, etc. \u2014 name varies per target)", "- `csrf-token` if it's bound to your session", "- `Authorization` headers (Bearer tokens, JWT)", "- `Cookie` request header values for any session-bearing cookie", "- `Set-Cookie` response header values for any session-bearing cookie"],
    '2-2-what-s-safe-to-leave-visible': ["- Cloudflare cookies (`__cf_bm`, `_cfuvid`) \u2014 these are bot-management, not session-bearing", "- Analytics cookies (`ajs_anonymous_id`, `_ga`)", "- Trace correlation IDs (`x-datadog-trace-id`, `x-request-id`)", "- Server / framework headers (`Server: cloudflare`, `X-Frame-Options`)", "- Your test account email/UID (per Bugcrowdninja alias section in `bugcrowd-reporting`)"],
    '2-3-redaction-methods-ranked-by-practicality': ["**Method A \u2014 Don't capture the cookies in the first place** (preferred when possible)", "- For DevTools Console PoCs: use `credentials: 'include'` so the browser sends cookies automatically. Console output won't echo the cookie. Screenshot the Console output, never the Network tab Headers panel.", "- For Burp Repeater PoCs: drag the bottom request/response panel divider DOWN to hide the request body before screenshotting. Capture only the Results table for Intruder runs.", "**Method B \u2014 Black-bar in image editor** (when capture inevitably includes cookies)", "- macOS: Open screenshot in Preview \u2192 Tools \u2192 Annotate \u2192 Rectangle \u2192 set fill color to black \u2192 drag rectangle over the cookie value \u2192 save", "- Windows: Use Snip & Sketch's annotation tools or any image editor (Paint.NET, etc.)", "- Burp itself: in Burp's Proxy \u2192 Match and Replace, you can pre-emptively redact cookie values to placeholder strings before screenshotting", "**Method C \u2014 Find/replace in raw text** (for HAR files, terminal transcripts)", "- See \u00a74 for the jq commands"],
    '2-4-pre-screenshot-checklist': ["Before clicking Capture:", "[ ] Network tab Headers panel is collapsed or out of frame", "[ ] Burp's Request panel is hidden behind the divider drag", "[ ] No \"Copy as cURL\" output is visible on screen", "[ ] DevTools Application \u2192 Storage \u2192 Cookies tab is closed", "[ ] Browser URL bar doesn't show a session token in query string (rare but possible)", "After capturing:", "[ ] Open the screenshot at full resolution before saving", "[ ] Search for the session cookie name substring in any visible text \u2014 if present, redact", "[ ] Search for the literal first 6 chars of your cookie value \u2014 if present, redact", "[ ] Compare to the previous PoC screenshot in the same engagement \u2014 same redaction discipline"],
    '3-pii-black-bar-protocol': ["When a PoC necessarily exposes another user's data (e.g., demonstrating IDOR by showing the victim's email in an attacker-session response), redact the actual PII even in private attachments."],
    '3-1-what-to-mask-other-user-data': ["- First name, last name (full or partial)", "- Email address (mask the local part; can leave domain if non-identifying)", "- Phone number (mask the last 7 digits, optionally leave country code)", "- Physical address (mask everything below city)", "- Date of birth (mask the year, optionally the month)", "- Government IDs (SSN, passport \u2014 mask everything)", "- Profile photos / face images (black-bar the face entirely)", "- Account IDs that the user could correlate to public profiles"],
    '3-2-what-to-leave-visible-proves-the-bug-not-the-user': ["- The fact that the field was returned (the JSON key name)", "- The shape / type of the field (`\"first_name\": \"<REDACTED>\"`)", "- Your own (attacker session's) UID / email \u2014 this proves cross-account", "- The endpoint URL and request method", "- The trace ID"],
    '3-3-worked-example-idor-poc-body': ["**Bad (leaks victim's full PII):**", "```json", "{\"data\":{\"contact\":{\"first_name\":\"Nadene\",\"last_name\":\"Afton\",\"email\":\"nadene.afton@example.com\",\"phone\":\"+1-555-867-5309\"}}}", "**Good (proves the bug, masks the PII):**", "```json", "{\"data\":{\"contact\":{\"first_name\":\"<REDACTED \u2014 real first name>\",\"last_name\":\"<REDACTED \u2014 real last name>\",\"email\":\"<REDACTED>@example.com\",\"phone\":\"<REDACTED>\"}}}", "In screenshot form, black-bar each value with a rectangle annotation labeled \"REAL PII REDACTED\" if there's space."],
    '3-4-in-the-report-body': ["Reference the redaction explicitly:", "```markdown"],
    'proof-of-concept': ["The screenshot below demonstrates the IDOR. The attacker session (uid 12345678) successfully retrieves the victim's profile data (uid 99887766). **Real PII fields in the response are masked with black rectangles to limit unauthorized exposure of victim data, per responsible-disclosure hygiene.** The unredacted response is available privately on request.", "This signals the triager that you're disciplined and gives them a clear path to the unredacted version if they need it for verification."],
    '4-har-file-sanitization': ["HAR (HTTP Archive) files are JSON dumps of network traffic with full request/response bodies and headers. They include cookies, auth tokens, and any PII that was in transit."],
    '4-1-generate-the-har': ["Chrome DevTools \u2192 Network tab \u2192 right-click anywhere in the request list \u2192 \"Save all as HAR with content\""],
    '4-2-sanitize-before-attaching': ["Use `jq` to strip sensitive headers. Save this as a shell function or one-liner you can re-use:", "```bash", "sanitize_har() {", "local input=\"$1\"", "local output=\"${1%.har}.sanitized.har\"", ".log.entries |= map(", "(.request.headers |= map(", "if .name | ascii_downcase | IN(\"cookie\", \"authorization\", \"x-csrf-token\") then .value = \"<REDACTED>\" else . end", "(.response.headers |= map(", "if .name | ascii_downcase | IN(\"set-cookie\") then .value = \"<REDACTED>\" else . end", "(.request.cookies |= map(.value = \"<REDACTED>\")) |", "(.response.cookies |= map(.value = \"<REDACTED>\"))", "' \"$input\" > \"$output\"", "echo \"Sanitized: $output\"", "Usage:", "```bash", "sanitize_har /path/to/exported.har"],
    'output-path-to-exported-sanitized-har': [],
    '4-3-verify-before-attaching': ["```bash"],
    'check-that-no-cookie-or-authorization-values-are-leaking': ["grep -i 'authn\\|\"cookie\"\\|authorization' /path/to/exported.sanitized.har | head -20", "If you see your real cookie value in the output, the sanitization missed something \u2014 fix the jq filter for that specific field name."],
    '4-4-remove-other-user-pii-if-applicable': ["If the HAR captured cross-account data (e.g., during an IDOR demo), additionally strip the response body fields that contain victim PII. Add to the jq filter:", "```jq", "(.response.content.text |= (", "if . then", "(fromjson? // .) | tostring | gsub(\"real.first.name.example\"; \"<REDACTED>\")", "else . end", "Customize the gsub patterns to your specific captured data."],
    '5-burp-suite-screenshot-hygiene': [],
    '5-1-repeater-single-request-demo': ["1. In the Repeater request panel, the Cookie header is on its own line \u2014 drag the panel divider DOWN to hide everything below the request line / target line", "2. Or: temporarily delete the Cookie header text from the Repeater pane (it doesn't affect the original captured request) before screenshotting, then restore", "3. Capture only the response panel (right side) showing the JSON / HTML response that demonstrates the bug"],
    '5-2-intruder-results-table-rate-limit-brute-force-demos': ["The Results window is the strongest evidence for rate-limit findings. To capture cleanly:", "1. After the attack finishes, drag the horizontal divider between the Results table and the Request/Response panels DOWN, until only the Results table is visible", "2. Screenshot only the columns: `Request#`, `Payload`, `Status code`, `Response received`, `Length`", "3. Don't include the Request / Response sub-panels \u2014 they contain the cookie"],
    '5-3-proxy-http-history-capture-demo': ["Almost never the right screenshot \u2014 it shows entire request/response pairs with cookies. Use Repeater for demos instead."],
    '5-4-scanner-findings-if-applicable': ["The Scanner tab's Issues panel is generally safe to screenshot \u2014 it shows finding summaries without the underlying request bodies. Click into a specific finding before screenshotting only if you've redacted its evidence first."],
    '6-chrome-devtools-console-poc-patterns': [],
    '6-1-the-clean-poc-pattern': ["```js", "fetch('/api/endpoint', {", "method: 'POST',", "headers: {'content-type': 'application/json'},", "credentials: 'include',  // sends cookies automatically \u2014 they won't appear in your code", "body: JSON.stringify({ /* your payload */ })", "}).then(r => r.json()).then(j => console.log(\"LABEL:\", JSON.stringify(j)))", "Why this is clean:", "- `credentials: 'include'` means the browser sends cookies. Your code never references them. They never appear in screenshots.", "- `console.log(\"LABEL:\", ...)` produces a labeled output line you can search for in the screenshot", "- `JSON.stringify(j)` formats the response on a single line \u2014 easier to crop tightly"],
    '6-2-multi-step-pocs-clear-console-between-calls': ["For a 4-step PoC (verify before / change / verify after / revert), clear the console between calls so each screenshot only shows ONE call and ONE response:", "- Mac: `Cmd+K`", "- Windows / Linux: `Ctrl+L`", "Take the screenshot immediately after the response prints \u2014 don't wait for unrelated framework warnings to appear."],
    '6-3-long-responses-truncate-for-screenshot': ["If the response body is too long for a clean screenshot, log a summary instead:", "```js", "fetch('/api/endpoint', { /* ... */ })", ".then(r => r.json())", ".then(j => {", "console.log(\"RESPONSE SHAPE:\", Object.keys(j.data || {}));", "console.log(\"CRITICAL FIELD:\", j.data?.victim_id, j.data?.email);", "// (Don't dump the full j \u2014 your screenshot becomes unreadable)"],
    '6-4-allow-pasting-reminder': ["Chrome blocks paste into DevTools Console as anti-self-XSS protection. Type `allow pasting` (literal phrase) once at the start of each session. Do this BEFORE you take any \"running PoC\" screenshot \u2014 otherwise the warning text appears in the screenshot."],
    '7-screenshot-capture-order-discipline': [],
    '7-1-the-5-step-poc-pattern-for-state-change-findings': ["For findings like \"password change without step-up,\" the canonical 5-screenshot pattern is:", "1. **Pre-state verification** \u2014 `verify_password(\"current\") \u2192 true`. Proves you knew the starting state.", "2. **The bug itself** \u2014 `update_password(...)` succeeds without step-up. THE most important screenshot.", "3. **Post-state verification (negative)** \u2014 `verify_password(\"old\") \u2192 false`. Proves the change took effect.", "4. **Post-state verification (positive)** \u2014 `verify_password(\"new\") \u2192 true`. Proves the new credential is active.", "5. **Out-of-band side effects** \u2014 inbox screenshot showing whether a notification email arrived. Proves whether passive defense exists."],
    '7-2-filename-conventions': ["Numbered, descriptive, hyphen-separated:", "{finding-#}-step{step-#}-{description}.png", "Examples:", "04-step1-verify-true-before.png", "04-step2-update-password-no-stepup.png", "04-step3-verify-false-after.png", "04-step4-verify-true-new-pw.png", "04-step5-inbox-notification-check.png", "In the report body, reference each by filename:", "```markdown", "- **Screenshot 1 (`04-step1-verify-true-before.png`)** \u2014 verify_password returns true with the current password.", "- **Screenshot 2 (`04-step2-update-password-no-stepup.png`)** \u2014 update_password returns User with no StepUpRequiredError. THIS IS THE BUG.", "- **Screenshot 3 (`04-step3-verify-false-after.png`)** \u2014 verify_password with old password returns false.", "- **Screenshot 4 (`04-step4-verify-true-new-pw.png`)** \u2014 verify_password with new password returns true.", "- **Screenshot 5 (`04-step5-inbox-notification-check.png`)** \u2014 inbox showing whether out-of-band notification was sent."],
    '7-3-capture-timing': ["- Take all screenshots in one sitting, not across multiple sessions. Mid-session inconsistencies (different browser sizes, different cookie values) are confusing for the triager.", "- Don't reload pages between screenshots if avoidable. Reloads regenerate cookies and may invalidate prior captures."],
    '8-post-submission-hygiene': ["After clicking Submit on the bug-bounty platform:"],
    '8-1-rotate-the-test-account-credentials': ["1. Log out of the target", "2. Log back in (this rotates the session cookie \u2014 any cookie shown in your screenshots is now dead)", "3. Change the password to a fresh value not used elsewhere (any password shown in your screenshots is now dead)"],
    '8-2-save-the-unredacted-artifacts-privately': ["Keep your unredacted HARs / screenshots in a local folder accessible only to you. The triager may ask for the unredacted version during verification. **Never share unredacted artifacts via email \u2014 use the platform's private attachment system on the existing submission thread.**"],
    '8-3-don-t-post-about-the-finding-publicly': ["Most platforms' confidentiality applies to BOTH unresolved and resolved issues. Don't tweet, blog, or discuss the finding in any forum until the program explicitly says you can."],
    '8-4-audit-your-local-artifacts': ["Quarterly, sweep your `~/security-research/` and `~/Downloads/` for stale HARs / screenshots from old engagements. Either move them to a properly-encrypted archive or delete them. Bug-bounty engagement artifacts are sensitive \u2014 they accumulate fast and become a liability."],
    '9-pairing-with-other-skills': [],
    'notes-on-usage': ["This skill is meant to be loaded together with `report-writing` and (for Bugcrowd) `bugcrowd-reporting` when preparing a submission. It does NOT cover:", "- **What** to capture (that's `triage-validation` and `report-writing`'s job \u2014 they tell you what evidence is required for the report to be accepted)", "- **How** to demonstrate exploitation (that's `security-arsenal`'s job \u2014 payloads to send)", "- **Where** to find the assets (that's `offensive-osint`'s job \u2014 recon)", "This skill covers ONLY the redaction / sanitization / hygiene layer that sits between \"I have evidence\" and \"I'm attaching it to the platform.\""],
    'related-skills-chains': ["- **`report-writing`** \u2014 When evidence is redacted and ready for the report body. Workflow primitive: after redaction passes the pre-screenshot checklist, hand off to `report-writing` for the platform-specific report template (H1 / Bugcrowd / Intigriti / Immunefi).", "- **`bugcrowd-reporting`** \u2014 When the redacted evidence is destined for Bugcrowd specifically. Workflow primitive: redacted screenshots + sanitized HARs become attachments referenced in `bugcrowd-reporting`'s VRT-mapped submission body.", "- **`triage-validation`** \u2014 When deciding which evidence is required at all. Workflow primitive: `triage-validation` says \"you need a 5-screenshot PoC for password-change-without-step-up\"; this skill says \"here's how to capture and redact those 5 screenshots cleanly.\"", "- **`security-arsenal`** \u2014 When the payload that produced the evidence is being documented. Workflow primitive: the payload (from `security-arsenal`) goes in the report verbatim; its output / response (handled by this skill) gets cookie / PII redacted before screenshotting.", "- **`bb-methodology`** \u2014 When Phase 5 (Validate & Report) needs evidence captured. Workflow primitive: Phase 5's evidence-capture step routes through this skill before the report is drafted."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()