#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/meme-coin-audit

Skill: MEME COIN & TOKEN SECURITY AUDIT
Desc : Meme coin and token security audit — rug pull detection (honeypot, hidden mint, fee manipulation, LP lock bypass), Solana SPL token analysis (freeze authority, mint authority, metadata mutability), Token-2022 extension risks (transfer hooks, permanent delegate), DEX liquidity pool attacks (sandwich amplification, LP drain, bonding curve exploits), pump.fun/Raydium/Jupiter integration risks, and real exploit examples from 2024-2025. Use for any token audit, rug pull assessment, meme coin security review, or pre-investment due diligence.

Run:  python claude-bughunter-meme-coin-audit.py --help
      python claude-bughunter-meme-coin-audit.py --list
      python claude-bughunter-meme-coin-audit.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/meme-coin-audit'
TITLE = 'MEME COIN & TOKEN SECURITY AUDIT'
DESCRIPTION = 'Meme coin and token security audit — rug pull detection (honeypot, hidden mint, fee manipulation, LP lock bypass), Solana SPL token analysis (freeze authority, mint authority, metadata mutability), Token-2022 extension risks (transfer hooks, permanent delegate), DEX liquidity pool attacks (sandwich amplification, LP drain, bonding curve exploits), pump.fun/Raydium/Jupiter integration risks, and real exploit examples from 2024-2025. Use for any token audit, rug pull assessment, meme coin security review, or pre-investment due diligence.'

PAYLOADS = {
    'main': ["name: meme-coin-audit", "description: Meme coin and token security audit \u2014 rug pull detection (honeypot, hidden mint, fee manipulation, LP lock bypass), Solana SPL token analysis (freeze authority, mint authority, metadata mutability), Token-2022 extension risks (transfer hooks, permanent delegate), DEX liquidity pool attacks (sandwich amplification, LP drain, bonding curve exploits), pump.fun/Raydium/Jupiter integration risks, and real exploit examples from 2024-2025. Use for any token audit, rug pull assessment, meme coin security review, or pre-investment due diligence."],
    'meme-coin-token-security-audit': ["Fast-kill rug pull detection and deep token security analysis for EVM and Solana meme coins."],
    'pre-dive-kill-signals': ["Check these BEFORE reading a single line of code. If any are true, skip the audit \u2014 the token is likely a rug or not worth the time."],
    'hard-kills-skip-immediately': ["- **Contract not verified** on Etherscan/Solscan \u2192 Cannot audit source = cannot trust", "- **Deployer wallet** has history of rug pulls (check Etherscan deployer page)", "- **Token age < 1 hour** AND no known team \u2192 Too early, wait for more data", "- **Mint authority retained** (Solana) AND no cap \u2192 Infinite mint = certain rug", "- **Freeze authority retained** (Solana) on meme coin \u2192 Honeypot confirmed", "- **Transfer hook present** (Token-2022) with mutable hook program \u2192 Honeypot vector", "- **Permanent delegate** extension (Token-2022) \u2192 Can steal all holder tokens"],
    'soft-kills-proceed-with-extreme-caution': ["- Top holder > 20% of supply (excluding DEX pools)", "- LP not burned or locked in verified contract", "- Contract is upgradeable / proxy with retained admin", "- Less than $5K liquidity in the pool", "- No social presence / anonymous deployer with no history"],
    'the-one-rule': [],
    'bug-classes-8-token-specific': [],
    '1-hidden-mint-unlimited-supply': ["**Quick grep (EVM):**", "```bash", "grep -rn \"function mint\\|_mint(\\|_balances\\[.*\\] +=\" src/ --include=\"*.sol\" | grep -v \"test\\|lib\\|node_modules\"", "**Quick grep (Solana):**", "```bash", "grep -rn \"MintTo\\|mint_to\\|mint_authority\" src/ --include=\"*.rs\" | grep -v \"test\\|target\"", "**Kill if:** MAX_SUPPLY enforced in every mint path, or mint function removed entirely."],
    '2-honeypot-transfer-restriction': ["**Quick grep:**", "```bash", "grep -rn \"blacklist\\|isBlacklisted\\|_bots\\|maxTxAmount\\|approve.*override\\|tradingEnabled\" src/ --include=\"*.sol\"", "**Solana equivalent:**", "```bash", "grep -rn \"freeze_authority\\|transfer_hook\\|TransferHook\\|permanent_delegate\" src/ --include=\"*.rs\"", "**Kill if:** No blacklist mapping, no transfer hooks, no freeze authority."],
    '3-fee-manipulation': ["**Quick grep:**", "```bash", "grep -rn \"setFee\\|setSellFee\\|_taxFee\\|_sellFee\" src/ --include=\"*.sol\"", "grep -rn \"function set.*Fee\" -A5 src/ --include=\"*.sol\" | grep -v \"require\\|MAX\\|<=\"", "**Kill if:** Fee setter has `require(fee <= MAX_FEE)` with MAX_FEE <= 10%."],
    '4-liquidity-pool-drain': ["**Quick grep:**", "```bash", "grep -rn \"migrateLP\\|emergencyWithdraw\\|\\.sync()\\|setPair\\|setRouter\" src/ --include=\"*.sol\"", "**Kill if:** LP tokens burned to dead address, no migration function, no pair setter."],
    '5-bonding-curve-manipulation': ["**Quick grep:**", "```bash", "grep -rn \"virtualReserve\\|setCurve\\|graduate\\|bonding_curve\" src/ --include=\"*.sol\" --include=\"*.rs\"", "**Kill if:** Curve parameters immutable, graduation permissionless."],
    '6-authority-retention-solana': ["**Quick grep:**", "```bash", "grep -rn \"mint_authority\\|freeze_authority\\|update_authority\\|close_authority\" src/ --include=\"*.rs\"", "grep -rn \"set_authority.*None\" src/ --include=\"*.rs\"  # Good sign: revocation", "**Kill if:** All authorities = None, verified on-chain."],
    '7-fake-renounce-hidden-ownership': ["**Quick grep:**", "```bash", "grep -rn \"renounceOwnership.*override\\|_shadowAdmin\\|_backupOwner\\|selfdestruct\" src/ --include=\"*.sol\"", "**Kill if:** renounceOwnership NOT overridden, no second admin role, no selfdestruct."],
    '8-sandwich-amplification-by-design': ["**Quick grep:**", "```bash", "grep -rn \"swapExactTokensForETH\" -A5 src/ --include=\"*.sol\" | grep \"0,\"", "grep -rn \"swapThreshold\\|_rebase\\|mandatoryPool\" src/ --include=\"*.sol\"", "**Kill if:** Auto-swap has proper slippage, no rebase mechanics."],
    'fast-red-flag-sweep': ["Run the 8 bug-class greps above across the source tree for fast red-flag detection. Together they catch:", "- Direct mint/balance manipulation", "- Blacklist and transfer restriction patterns", "- Unbounded fee setters", "- LP migration and emergency withdraw functions", "- Fake renounce overrides", "- Zero slippage auto-swaps", "- All Solana authority patterns", "- Token-2022 dangerous extensions", "**Source grep does NOT check** (verify these out-of-band):", "- On-chain state (use Etherscan/Solscan for authority verification)", "- Holder distribution (use DEXTools/Birdeye)", "- LP lock status (use Unicrypt/PinkLock/Solscan)", "- Deployer wallet history (manual check)"],
    'foundry-poc-template-token-exploits': ["```solidity", "// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.0;", "import \"forge-std/Test.sol\";", "import \"../src/Token.sol\";", "contract TokenExploitTest is Test {", "Token token;", "address owner = makeAddr(\"owner\");", "address victim = makeAddr(\"victim\");", "address attacker = makeAddr(\"attacker\");", "// Uniswap V2 router (mainnet fork)", "address constant ROUTER = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D;", "address constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;", "function setUp() public {", "vm.createSelectFork(\"mainnet\");", "// Deploy token as owner", "vm.startPrank(owner);", "token = new Token();", "// Add liquidity...", "vm.stopPrank();", "function test_hiddenMint_rug() public {", "// Step 1: Victim buys tokens", "vm.startPrank(victim);", "// ... buy tokens on Uniswap", "vm.stopPrank();", "// Step 2: Owner mints and dumps", "vm.startPrank(owner);", "uint256 supplyBefore = token.totalSupply();", "token.mint(owner, 1_000_000_000e18);", "assertGt(token.totalSupply(), supplyBefore, \"Supply should increase\");", "// ... sell minted tokens", "vm.stopPrank();", "// Step 3: Victim's tokens are now worthless", "// Assert token price crashed", "function test_honeypot_blacklist() public {", "// Step 1: Victim buys", "vm.startPrank(victim);", "// ... buy tokens", "vm.stopPrank();", "// Step 2: Owner blacklists victim", "vm.startPrank(owner);", "token.blacklist(victim);", "vm.stopPrank();", "// Step 3: Victim cannot sell", "vm.startPrank(victim);", "vm.expectRevert(\"Blacklisted\");", "token.transfer(address(1), 100e18);", "vm.stopPrank();", "function test_fee_manipulation_rug() public {", "// Step 1: Verify initial fee is low", "assertEq(token.sellFee(), 3); // 3%", "// Step 2: Owner sets fee to 99%", "vm.prank(owner);", "token.setFees(3, 99); // Buy 3%, Sell 99%", "// Step 3: Victim sells \u2014 loses 99% to fees", "vm.startPrank(victim);", "uint256 balanceBefore = address(victim).balance;", "// ... sell tokens", "// Assert: received almost nothing", "vm.stopPrank();"],
    'solana-quick-checks-no-source-code-needed': ["When you don't have source code, check on-chain:", "1. MINT AUTHORITY \u2192 solana account <MINT> --output json | check mint_authority", "- Should be null", "- If Some(pubkey) \u2192 CRITICAL: can mint infinite tokens", "2. FREEZE AUTHORITY \u2192 same as above, check freeze_authority", "- Should be null", "- If Some(pubkey) \u2192 CRITICAL: honeypot", "3. LP STATUS \u2192 Check Raydium/Orca pool", "- LP burned? (tokens sent to 1111...1111)", "- LP locked? (in verified locker with no backdoor)", "- LP held by deployer? \u2192 CRITICAL: instant rug", "4. TOP HOLDERS \u2192 Birdeye/Solscan holders tab", "- Top 10 < 30% of supply (excluding pools)", "- Creator wallets (check first transactions)", "5. PROGRAM UPGRADEABILITY", "- Is the program upgradeable? \u2192 can change any logic", "- Upgrade authority should be None for immutable programs", "6. TOKEN-2022 EXTENSIONS", "- Any transfer hook? \u2192 potential honeypot", "- Permanent delegate? \u2192 CRITICAL"],
    'related-skills-chains': ["- **`web3-audit`** \u2014 When the target is a DeFi protocol (not just a token). Workflow primitive: this skill's 8 token-specific bug classes are a subset of `web3-audit`'s scope; if the target has lending / vault / oracle logic beyond the token contract itself, also load `web3-audit` for the broader 10 DeFi bug classes.", "- **`triage-validation`** \u2014 When deciding if a rug-pull finding qualifies as a bug bounty submission. Workflow primitive: many \"rug vector\" observations are pre-rug warnings, not exploitable bugs in a deployed protocol; run 7Q gate to distinguish \"the deployer COULD rug\" (informational) from \"the contract IS exploitable now\" (reportable).", "- **`report-writing`** \u2014 When writing up a confirmed token security finding for Immunefi / private bounty. Workflow primitive: Foundry PoC template here feeds into `report-writing`'s Immunefi body template.", "- **`offensive-osint`** \u2014 When the token has off-chain infrastructure (project website, Telegram, deployer doxxing). Workflow primitive: on-chain audit is this skill's domain; deployer wallet history, social presence, and project legitimacy checks route to `offensive-osint`.", "- **`bb-methodology`** \u2014 When confirming engagement mode. Workflow primitive: PART 0 separates \"pre-investment due diligence\" (this skill's primary use) from \"Immunefi bug bounty submission\" (different reporting + severity standards); the answer routes which post-audit handoff is correct."],
    'operator-notes-claude-bughunter': [],
    'solana-specific-signals-2025-2026-reality': ["Token-2022 transfer hooks are the new rug-pull vector. Hook authority can be set to a single key; that key can pause / blacklist / fee-on-transfer arbitrary addresses post-launch. Always check hook authority + permanent-delegate authority for Token-2022 mints:", "```bash"],
    'get-mint-extensions-for-a-token-2022-mint': ["spl-token display <MINT_ADDRESS> --program-id TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"],
    'look-for-transferhook-authority-permanentdelegate-delegate': ["If TransferHook authority is non-null \u2192 the holder of that key can revoke transfer rights mid-trade. If PermanentDelegate is non-null \u2192 that delegate can move any holder's tokens at any time (effectively a built-in confiscation). Either alone is rug-class.", "pump.fun bonding curves can be manipulated via the curve's K-parameter; mint authority retained beyond bonding-curve completion is the classic exit-scam shape. Check `mintAuthority` AFTER the curve completes \u2014 legitimate launches null it, scams retain it for the post-graduation dump."],
    'honeypot-detection-beyond-the-obvious': ["`transfer()` succeeds in dry-run but fails on certain addresses (sender allowlist / blocklist). Test with: simulated buy \u2192 simulated transfer to a different address \u2192 simulated sell. If buy + transfer succeed but sell fails, it's a honeypot.", "Quick triage matrix:", "Cross-source verification: solana-rugcheck, rugcheck.xyz, dexscreener risk signals, honeypot.is (EVM). Never trust a single source \u2014 rug-checkers can be fooled by deferred-malice patterns (clean for first 7 days, hook activates later)."],
    'lp-lock-claims-verify-don-t-trust': ["LP-lock badges on DexScreener mean nothing without on-chain verification. Check the actual lock contract (Unicrypt, TeamFinance, Bonkbot, PinkLock) for:", "- **Unlock date** \u2014 the on-chain timestamp, not the badge text", "- **Lock owner** \u2014 is it the deployer's wallet? Are there multiple lockers fragmenting the LP?", "- **Extension / shortening permission** \u2014 some lock contracts allow the owner to SHORTEN the lock; that's an exit hatch dressed as a lock", "- **Lock contract bytecode** \u2014 verify it's the canonical locker, not a fork with backdoors", "Some \"locked\" LPs are 1-day locks renewed weekly \u2014 visually the same as a year lock to the buyer, but the deployer can let it lapse on any Tuesday. Always read the lock contract source on the chain explorer."],
    'pre-investment-due-diligence-in-under-5-minutes': ["The 6-question fast filter:", "1. Mint authority null?", "2. Freeze authority null?", "3. Update authority null (for metadata immutability)?", "4. LP locked in a verified contract for > 6 months?", "5. Top 10 holders concentration < 30% (excluding pools/burn addresses)?", "6. Bonding curve completed (for pump.fun) AND post-completion mint authority null?", "Five \"no\"s = walk away. Three \"no\"s = high risk, only enter with size you'd walk away from. Two \"no\"s with strong narrative + thin liquidity = the canonical retail trap."],
    'mev-sandwich-amplification-on-illiquid-mints': ["Buying into a mint with < $50K liquidity guarantees you'll be sandwiched. The bot infrastructure on Solana and Ethereum is institutionalized in 2026 \u2014 Jito MEV-share and private order-flow auctions. If your trade size > 1% of available liquidity, expect sandwich loss > 5%; > 5% of liquidity, expect > 20% slippage from sandwich alone.", "Mitigations (rank by 2026 effectiveness):", "1. **Jito bundles** (Solana) \u2014 submit with priority tip, atomic with no MEV window", "2. **Flashbots Protect RPC** (Ethereum) \u2014 private mempool submission", "3. **MEV-protected DEX aggregators** \u2014 Jupiter's slippage protection, 1inch Fusion, CoWSwap", "4. **Splitting orders** \u2014 N smaller trades vs 1 large; reduces sandwich profitability per trade", "If the mint is so illiquid that even split orders sandwich \u2014 that's the signal to skip the trade, not the signal to use better tooling."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()