#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/bugcrowd-reporting

Skill: BUGCROWD REPORTING — Program-Specific Tactics
Desc : Bugcrowd-specific reporting tactics complementing report-writing: VRT category search-and-fallback strategy when no exact match exists, manual severity override when VRT defaults underrate impact, severity-request paragraph as first body section, OOS-clause rebuttal templates (rate limiting on auth-flow endpoints, debug-info framing, user-enumeration with sensitive PII, theoretical-issue counter), chained-finding cross-reference patterns, target selection for QA-vs-prod programs, researcher-side hygiene (Bugcrowdninja email alias, account state restoration, friendly-tester posture). Use when filing a Bugcrowd submission, when VRT default seems wrong, when triager closes as OOS or downgrades severity, when chaining linked submissions, or when scope distinguishes production from QA. Pairs with report-writing and triage-validation.

Run:  python claude-bughunter-bugcrowd-reporting.py --help
      python claude-bughunter-bugcrowd-reporting.py --list
      python claude-bughunter-bugcrowd-reporting.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/bugcrowd-reporting'
TITLE = 'BUGCROWD REPORTING — Program-Specific Tactics'
DESCRIPTION = 'Bugcrowd-specific reporting tactics complementing report-writing: VRT category search-and-fallback strategy when no exact match exists, manual severity override when VRT defaults underrate impact, severity-request paragraph as first body section, OOS-clause rebuttal templates (rate limiting on auth-flow endpoints, debug-info framing, user-enumeration with sensitive PII, theoretical-issue counter), chained-finding cross-reference patterns, target selection for QA-vs-prod programs, researcher-side hygiene (Bugcrowdninja email alias, account state restoration, friendly-tester posture). Use when filing a Bugcrowd submission, when VRT default seems wrong, when triager closes as OOS or downgrades severity, when chaining linked submissions, or when scope distinguishes production from QA. Pairs with report-writing and triage-validation.'

PAYLOADS = {
    'main': ["name: bugcrowd-reporting", "description: \"Bugcrowd-specific reporting tactics complementing report-writing: VRT category search-and-fallback strategy when no exact match exists, manual severity override when VRT defaults underrate impact, severity-request paragraph as first body section, OOS-clause rebuttal templates (rate limiting on auth-flow endpoints, debug-info framing, user-enumeration with sensitive PII, theoretical-issue counter), chained-finding cross-reference patterns, target selection for QA-vs-prod programs, researcher-side hygiene (Bugcrowdninja email alias, account state restoration, friendly-tester posture). Use when filing a Bugcrowd submission, when VRT default seems wrong, when triager closes as OOS or downgrades severity, when chaining linked submissions, or when scope distinguishes production from QA. Pairs with report-writing and triage-validation.\""],
    'bugcrowd-reporting-program-specific-tactics': ["This skill encodes patterns that apply specifically to Bugcrowd's submission flow. For the generic per-platform templates (HackerOne / Bugcrowd / Intigriti / Immunefi report bodies), use the `report-writing` skill. For the 7-Question Gate before deciding to report at all, use `triage-validation`."],
    '1-vrt-category-selection-search-fallback-strategy': ["Bugcrowd's submission form requires a single VRT (Vulnerability Rating Taxonomy) selection. The dropdown's default severity is bound to the chosen node \u2014 pick wrong and the form auto-suggests a lower priority (often P4) when the actual impact is P3 or P2."],
    '1-1-search-hierarchy-try-in-order-pick-the-highest-severity-match-that-still-describes-the-bug': ["For any finding, search the VRT dropdown with these terms in this order:", "1. **The bug's primary class** \u2014 e.g., `IDOR`, `XSS`, `SSRF`, `auth bypass`, `2FA bypass`", "2. **The data category exposed** \u2014 e.g., `PII`, `sensitive data exposure`, `disclosure of secrets`", "3. **The control bypassed** \u2014 e.g., `broken access control`, `authentication bypass`", "4. **The endpoint type** \u2014 e.g., `no rate limiting on form > login`, `no rate limiting on form > change password`", "5. **The generic parent node** \u2014 e.g., `Server Security Misconfiguration > Other`, `Broken Access Control > Other`"],
    '1-2-pick-the-highest-severity-match-that-still-accurately-describes-the-bug': ["Never select a VRT that misrepresents the bug just to get a higher default severity. Triagers will reassign and may flag the misrepresentation. The discipline is: pick the most specific *accurate* VRT, then use \u00a72 (Manual Severity Override) if the default is wrong."],
    '1-3-common-mappings-worth-knowing': [],
    '1-4-if-no-good-vrt-exists': ["Pick `Server Security Misconfiguration \u2192 Other` or `Broken Access Control \u2192 Other` and **lead the description body with a \"VRT mapping note\"** explaining why the chosen node is the closest available match and what the bug actually is."],
    '2-manual-severity-override': ["Bugcrowd's form lets you manually set Technical Severity *separate from the VRT default*. The form text itself states: *\"A severity rating suggested by the VRT is not guaranteed to be the severity rating applied to your submission.\"*"],
    '2-1-when-to-override': ["Override the VRT default when:", "- The chained outcome is a higher severity than the standalone bug class (chain \u2192 ATO)", "- The VRT category is approximate and its default doesn't reflect the actual impact class", "- The program's own Focus Areas explicitly list this outcome at a higher severity than VRT's default", "- The data class exposed is more sensitive than the VRT's example uses (e.g., real-name PII vs. handle enumeration)"],
    '2-2-how-to-override-form-mechanics': ["1. Select the VRT that most accurately describes the bug (per \u00a71)", "2. Note the auto-suggested severity (P4, P3, etc.)", "3. In the **Technical Severity** field, manually pick the severity you're requesting", "4. Add a **Severity Request** paragraph as the FIRST section of the description body (per \u00a73)"],
    '2-3-don-t-over-claim': ["P1 inflation is the fastest way to lose triager trust. Reserve P1 for ATO without interaction, RCE, mass PII exfiltration, fund theft, and similar Critical-bucket impacts. If the chain to P1 requires a separate stolen-cookie premise, file the standalone primitive at P3 and discuss the chain explicitly with cross-references (per \u00a74)."],
    '3-severity-request-paragraph-always-first-in-the-body': ["When the VRT default underrates impact, the FIRST section of the description body should be a severity-request paragraph. This is the first thing the triager reads and it pre-empts the auto-close that often happens when triagers see \"P4\" in the form."],
    '3-1-template': ["```markdown"],
    'severity-request-please-review-carefully-before-applying-vrt-default': ["The closest VRT category for this finding is \"[chosen VRT],\" which Bugcrowd defaults to **P[N] ($X-$Y in [program]'s rubric)**. **I am requesting evaluation at P[M] [standalone | in chain with submission XXXX]** for the following reasons:", "1. **[Impact axis 1]** \u2014 [specific reason this finding exceeds the VRT default's example]", "2. **[Impact axis 2]** \u2014 [specific reason, often citing the program's own Focus Areas]", "3. **[Impact axis 3]** \u2014 [specific reason, often comparing to historical bounty payouts for the same data class]", "[Optional: one paragraph contrasting the VRT default's typical example with this finding's actual impact, e.g., \"P4 = No Rate Limiting on Login Form\" applies to ordinary login pages where brute force is bounded by lockout policies; this endpoint has neither lockout nor throttle.]"],
    '3-2-worked-example-pattern': ["```markdown"],
    'severity-request-please-review-carefully-before-applying-vrt-default': ["The closest VRT category for this finding is \"No Rate Limiting on Form \u2192 Login,\" which Bugcrowd defaults to **P4 ($XX\u2013$YY in this program's rubric)**. **I am requesting evaluation at P3 standalone, P2 in chain with submission XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX** for the following reasons:", "1. **[Endpoint] is a password-disclosure oracle, not a generic rate-limit gap.** The endpoint returns true/false for a supplied password \u2014 combined with cookie theft, it is the exact primitive an attacker uses to learn the victim's *durable* credential from a stolen *transient* session.", "2. **The chained outcome is \"Account Takeover,\"** explicitly listed under the program \u2192 Focus Areas \u2192 Critical (P1) examples. This finding is one of two independent links that make that chain work; the other is submission XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.", "3. **The two findings have independent fix surfaces.** Per the program's \"one fix = one bounty\" rule they should be evaluated as two separate findings whose chain raises the joint severity.", "The \"P4 = No Rate Limiting on Login Form\" default applies to ordinary login pages where brute-force is bounded by lockout policies. This endpoint has neither lockout nor throttle, and the result of brute force is the *user's actual password* (not a session) \u2014 making the impact significantly higher than the default VRT severity assumes."],
    '3-3-tone-guidelines': ["- Open with *\"Severity request \u2014 please review carefully before applying VRT default\"* (literal phrase). Triagers recognize this and don't auto-close.", "- Use **bold** sparingly; one or two phrases per reason at most.", "- Never use \"could potentially\" or \"may allow\" \u2014 these are downgrade-bait.", "- Cite the program's own Focus Areas / accepted-impact list by exact name.", "- Cross-reference linked submissions by full submission ID (UUID format)."],
    '4-oos-clause-rebuttals-templates': ["Bugcrowd triagers sometimes auto-close findings by mapping them to an OOS clause without reading the report. Pre-empt this by including an **In-scope justification** section that quotes the OOS clause and explains why your finding doesn't fit it."],
    '4-1-rate-limiting-on-non-authentication-endpoints-rebuttal': ["When the finding is on an authentication endpoint (login, password change, password verify, OTP verify, token validate):", "```markdown"],
    'in-scope-justification': ["The program OOS list excludes \"Rate limiting or brute-force issues on **non-authentication** endpoints.\" `[endpoint name]` is the canonical authentication endpoint \u2014 it accepts a password/token/OTP and returns whether it matches the user's stored credential. By definition this is an authentication primitive. The OOS clause's \"non-authentication\" qualifier therefore does NOT apply."],
    '4-2-debug-information-disclosure-rebuttal-for-schema-introspection-findings': ["When the finding involves schema disclosure that's actually a control bypass (e.g., GraphQL allowlist bypass exposing the mutation surface):", "```markdown"],
    'in-scope-justification': ["This is not a \"debug information\" finding. The [persisted-query allowlist | introspection gate | etc.] is acting as an authorization control on the [GraphQL surface | API tree | etc.]. The bypass converts that gate into a no-op \u2014 multiple [mutations | endpoints] become reachable that the official clients cannot invoke. The schema disclosure is incidental; the impact is **mutation-surface unlock**, not information leakage."],
    '4-3-user-enumeration-with-low-risk-information-rebuttal': ["When the finding leaks more than just \"this handle/email exists\":", "```markdown"],
    'in-scope-justification': ["The program OOS list excludes \"User Enumeration issues with **low-risk and insignificant** information being enumerated.\" The data leaked here is **neither low-risk nor insignificant**: it includes the matched user's [full real first name, last name, profile photo / SSN last 4 / phone number / etc.]. Real-[name | identity | etc.] knowledge is the same data class that gates the program's own [account-recovery flows / fraud-investigation interviews / support-call verification], which means this lookup directly defeats one of the program's own anti-fraud controls. This is PII disclosure, not handle enumeration."],
    '4-4-theoretical-issues-not-exploitable-rebuttal': ["When the finding's exploitability has been demonstrated end-to-end:", "```markdown"],
    'in-scope-justification': ["This finding is exploitable end-to-end as demonstrated in the PoC: [one-sentence summary of the proven exploitation path]. The PoC includes [N HTTP requests with redacted cookies | N screenshots | a sanitized HAR file | etc.] showing the attacker's session [reading victim data | changing victim credentials | etc.]. The OOS clause for \"theoretical issues that are not exploitable, or can not be demonstrated as exploitable\" does not apply."],
    '4-5-if-you-don-t-have-end-to-end-proof': ["If you only have an \"API behavior\" observation without a fully demonstrated exploitation path, the finding is theoretical. Don't file it. Capture the missing evidence (delivery confirmation, token-format inspection, cross-account victim data in response, etc.) and re-evaluate. Filing theoretical findings damages researcher reputation on the platform."],
    '5-chained-findings-cross-reference-strategy': ["Many high-impact findings are chains of two or more standalone primitives (oracle + missing step-up = ATO). Bugcrowd's program rule: *\"Submit one vulnerability per report. If multiple vulnerabilities must be chained to demonstrate impact, you may include them together, but please clearly explain the chain.\"*"],
    '5-1-filing-strategy-for-chains': ["1. **Identify the highest-severity chained outcome** (typically the one that maps to a P1/P2 example in the program's Focus Areas).", "2. **File the chain primitives FIRST** as separate reports \u2014 each at its standalone severity (typically P3/P4). A submission's UUID only exists *after* it is filed, so the primitives must exist before anything can reference them. Leave the cross-reference line in each primitive's body as a placeholder for now.", "3. **File the chain consumer** \u2014 the report whose body describes the full ATO/RCE/etc. impact at the chained severity (e.g., P1). Because the primitives already exist, fill in their real UUIDs in the consumer's \"Chain partners\" block (per \u00a75.2).", "4. **Edit each primitive after filing the consumer** to backfill the consumer's UUID: *\"Chain partner: submission [UUID] for the full impact narrative.\"* (The reference is bidirectional, so one report must be edited after the other is filed \u2014 Bugcrowd allows post-submission edits to the description body.)"],
    '5-2-cross-reference-template': ["In the chain consumer's body, near the top:", "```markdown"],
    'chain-partners-filed-as-separate-reports': ["- **submission [UUID-1]** \u2014 [primitive 1: e.g., `me.verify_password` no rate limit]", "- **submission [UUID-2]** \u2014 [primitive 2: e.g., GraphQL APQ allowlist bypass]", "These primitives have independent fix surfaces and are filed separately per the program's \"one fix = one bounty\" rule. The chained impact described here requires both primitives to be exploited end-to-end.", "In each primitive's body:", "```markdown"],
    'chain-context': ["This finding is the [N]th of [M] independent primitives that together produce [impact, e.g., \"permanent account takeover from a stolen session cookie\"]. The full chain narrative and the chained severity (P1) are documented in submission [UUID]. This standalone report is at P3 reflecting the primitive's individual impact."],
    '5-3-what-not-to-do': ["- Don't paste the entire chain narrative into every primitive's body. Cross-reference instead.", "- Don't claim each primitive is independently P1 \u2014 overclaiming damages credibility for all linked reports.", "- Don't ask for a single combined bounty for the chain. The program's \"one fix = one bounty\" rule means each independent fix surface is a separate bounty. Frame the chain as a severity-amplifier, not a merge request."],
    '6-target-selection-qa-vs-production': ["Programs that scope both production and QA assets (e.g., `app.target.com` vs. `app-qa.target.com`) require careful target selection."],
    '6-1-picking-the-right-target-dropdown-entry': [],
    '6-2-qa-disclaimer-paragraph-when-filing-a-qa-tested-finding': ["```markdown"],
    'notes-for-triagers': ["- Tested in the QA environment ([qa-host]) per the program's instruction for non-US researchers / per the program's QA-testing scope.", "- Production may enforce additional controls that QA does not \u2014 please confirm whether the same resolver code path runs on production.", "- All testing limited to my own QA test account; no other accounts were interacted with.", "- Selected target: `[chosen-target]`. Selected VRT: `[chosen-VRT]`. Both selected as closest available matches; please reassign if more appropriate options exist."],
    '7-researcher-side-hygiene-bugcrowd-specific': ["These are program-rule items that affect submission quality even though they're not part of the report body itself."],
    '7-1-account-email-bugcrowdninja-alias': ["Most Bugcrowd-managed programs ask researchers to use their `@bugcrowdninja.com` alias as the account email on the target. This flags traffic as friendly-tester to the target's fraud team. Steps:", "1. Sign up for the target using your Bugcrowd alias (looks like `username@bugcrowdninja.com`)", "2. If you already have an account, update the email to the alias before testing", "3. If the program offers a contact path for multi-account testing, use that to coordinate additional aliased accounts (`alias+test1@bugcrowdninja.com`, etc.)", "4. Document the alias in the report's \"Notes for triagers\" section so the triager can correlate test traffic in their logs"],
    '7-2-account-state-restoration-after-poc': ["After demonstrating any state-changing action (password change, email change, device removal, money transfer):", "1. Restore the account to its pre-PoC state immediately (e.g., revert the password to what it was)", "2. Document the restoration in the report \u2014 *\"Account state was restored immediately after the PoC.\"*", "3. If restoration is impossible (e.g., a sent email cannot be unsent), document the residual state honestly"],
    '7-3-cookie-session-rotation-after-submission': ["After submitting any report that includes session-cookie-derived evidence:", "1. Log out and log back in to rotate the session cookie", "2. Any cookie value visible in screenshots / HARs you submitted is now dead", "3. Optionally, rotate the test-account password to a fresh value not used elsewhere \u2014 that way passwords visible in PoC screenshots are also dead"],
    '7-4-if-the-test-account-gets-locked': ["1. Don't create a second account to bypass the lock \u2014 that looks like fraud", "2. Email the program-specific contact (if provided) with your Bugcrowd username and the report ID", "3. Wait for the program team to unblock you; testing during the lock period damages credibility"],
    '8-submission-order-strategy-for-multi-finding-engagements': ["When you have multiple findings from a single engagement, the order matters."],
    '8-1-recommended-order': ["1. **Chain primitives before their consumer.** A consumer references the primitives' report UUIDs, which only exist once the primitives are filed (see \u00a75.1). File the best-evidenced primitive first to lock your timestamp, then the rest of the chain's primitives.", "2. **The chain consumer next** \u2014 fill in the real primitive UUIDs, then edit each primitive to backfill the consumer's UUID (Bugcrowd allows post-submission body edits).", "3. **Standalone P3 findings next.** Order by quality of evidence: best-evidenced first, riskier (OOS-adjacent) findings later.", "4. **OOS-risky findings last.** By the time these land, you've established a credible track record on this engagement."],
    '8-2-tracking-submission-ids': ["Maintain a simple text file with each submission's UUID, severity, and one-line description. You'll reference these IDs across reports and during any subsequent triager dialogue."],
    '8-3-what-to-avoid': ["- Don't file all findings in a single batch within minutes. Triagers see this as low-effort spam.", "- Don't file an OOS-risky finding before a clean P3 from the same engagement. The clean one establishes credibility; the risky one benefits from being read in that context.", "- Don't disclose any findings publicly until the program explicitly says it's OK. Bugcrowd's confidentiality applies to both unresolved AND resolved issues."],
    '9-pairing-with-other-skills': [],
    'notes-on-usage': ["This skill is small and focused. It does NOT duplicate content from `report-writing` (per-platform templates, CVSS scoring, downgrade counters, 60-second pre-submit checklist) \u2014 load both skills together when filing a Bugcrowd report. The two skills' content composes naturally because their boundaries are clean: `report-writing` is the body templates, `bugcrowd-reporting` is the program-specific tactics layered on top."],
    'related-skills-chains': ["- **`report-writing`** \u2014 Always load this skill alongside `bugcrowd-reporting`. Workflow primitive: `report-writing` provides the body skeleton; this skill layers VRT selection + severity-request paragraph + OOS-clause rebuttals on top of that skeleton.", "- **`triage-validation`** \u2014 When deciding if a Bugcrowd-bound finding will pass triage. Workflow primitive: 7Q gate runs first; only validated findings reach this skill for VRT mapping.", "- **`evidence-hygiene`** \u2014 When attaching screenshots / HARs to a Bugcrowd submission. Workflow primitive: Bugcrowd's private attachment system requires redacted evidence; route everything through `evidence-hygiene` before clicking attach.", "- **`security-arsenal`** \u2014 When the PoC step needs payloads cited verbatim. Workflow primitive: the \"Steps to Reproduce\" section in this skill's report bodies pulls exact payloads from `security-arsenal` so the triager can paste-and-run.", "- **`bb-methodology`** \u2014 When confirming engagement mode is bug-bounty (not red-team). Workflow primitive: PART 0 of `bb-methodology` answers \"bug bounty?\"; if yes AND the target is Bugcrowd, this skill becomes the reporting overlay."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()