#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/redteam-report-template

Skill: Prerequisite: pandoc installed
Desc : Client-facing red-team deliverable format — codifies the Subject / Observations / Description / Impact / Recommendation / PoC structure used for external red-team engagements (not bug-bounty platform reports). Different audience, different tone, different cadence. Built from an authorized engagement deliverable where 14 findings were packaged into a 52KB MD + 2.2MB DOCX with 16 embedded screenshots. Use when the engagement is "external red team for an enterprise client" (not H1/Bugcrowd/Intigriti), when generating the final report, when the client has specified a custom report format, or when packaging findings into DOCX/PDF.

Run:  python claude-bughunter-redteam-report-template.py --help
      python claude-bughunter-redteam-report-template.py --list
      python claude-bughunter-redteam-report-template.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/redteam-report-template'
TITLE = 'Prerequisite: pandoc installed'
DESCRIPTION = 'Client-facing red-team deliverable format — codifies the Subject / Observations / Description / Impact / Recommendation / PoC structure used for external red-team engagements (not bug-bounty platform reports). Different audience, different tone, different cadence. Built from an authorized engagement deliverable where 14 findings were packaged into a 52KB MD + 2.2MB DOCX with 16 embedded screenshots. Use when the engagement is "external red team for an enterprise client" (not H1/Bugcrowd/Intigriti), when generating the final report, when the client has specified a custom report format, or when packaging findings into DOCX/PDF.'

PAYLOADS = {
    'main': ["name: redteam-report-template", "description: Client-facing red-team deliverable format \u2014 codifies the Subject / Observations / Description / Impact / Recommendation / PoC structure used for external red-team engagements (not bug-bounty platform reports). Different audience, different tone, different cadence. Built from an authorized engagement deliverable where 14 findings were packaged into a 52KB MD + 2.2MB DOCX with 16 embedded screenshots. Use when the engagement is \"external red team for an enterprise client\" (not H1/Bugcrowd/Intigriti), when generating the final report, when the client has specified a custom report format, or when packaging findings into DOCX/PDF.", "sources: authorized-engagement-deliverable, enterprise-redteam-report-conventions", "report_count: 1"],
    'when-to-use': ["Use this skill for **client-deliverable** reports:", "- External red-team engagements with a signed SOW", "- Pentest reports going to a CISO / IT-Sec team (not a triager)", "- Findings that will be reviewed by both technical and non-technical stakeholders", "- Reports that need DOCX/PDF output (not just markdown / platform UI)", "Do NOT use for:", "- Bug-bounty platform submissions (use `report-writing` / `bugcrowd-reporting` instead)", "- Quick proof-of-concept memos", "- Internal team writeups"],
    'the-6-section-format-per-finding': ["This is the canonical structure each finding follows:", "```markdown"],
    'finding-f-descriptive-title': ["**Severity:** Critical / High / Medium / Low / Informational", "**Status:** Confirmed / Patched mid-engagement / Suspected (1 signal)", "**CVSS 3.1:** <score> (<vector>)", "**Affected Asset:** <URL / IP / app name>"],
    '1-subject': ["<One-line statement of the issue. Plain English, no jargon.>"],
    '2-observations': ["<Bulleted list of what was observed during testing. Concrete facts only \u2014 no interpretation yet.>", "- <Observation 1>", "- <Observation 2>", "- ..."],
    '3-description': ["<Technical explanation of the vulnerability. 2-4 paragraphs. Reader should understand WHY the observations indicate a vulnerability, what the underlying flaw is.>"],
    '4-impact': ["<What an attacker could achieve. Concrete attacker outcomes, NOT generic CIA triad statements. Tie to the client's business \u2014 money, data, reputation, regulatory exposure.>"],
    '5-recommendation': ["<Specific, actionable remediation. Vendor patch, configuration change, code-level fix. Avoid \"implement security best practices\" \u2014 say what specifically.>"],
    '6-proof-of-concept-poc': ["<Steps to reproduce, numbered. Include the exact HTTP requests, payloads, tools used.>", "**Step 1:** <action>", "```http", "<full HTTP request or curl one-liner>", "**Step 2:** <action>", "<response excerpt>", "**Screenshot:**", "![F##_descriptive_name](screenshots/F##_descriptive_name.png)"],
    'severity-status-disciplines': [],
    'severity-table-client-facing-different-from-cvss-only': [],
    'status-field-red-team-specific': ["This is the field that distinguishes red-team deliverables from bug-bounty reports. Use one of:", "- **Confirmed** \u2014 reproduced multiple times, with full PoC", "- **Confirmed; patched mid-engagement** \u2014 was reproducible, client patched during the test window (still ship the finding \u2014 see `mid-engagement-ir-detection`)", "- **Confirmed; partially reproducible** \u2014 works but needs specific conditions", "- **Suspected (1 signal)** \u2014 single indicator, not confirmed (rare \u2014 usually drop)", "- **Out-of-band** \u2014 finding from passive recon, not actively tested"],
    'mistakes-to-avoid-from-authorized-engagement': [],
    '1-don-t-retract-findings-that-stopped-reproducing': ["If a finding was confirmed and then stopped working, that is almost always a CLIENT PATCH, not a finding-was-false. The correct response is \"Confirmed; patched mid-engagement\" with timestamps showing when it broke. See `mid-engagement-ir-detection`."],
    '2-don-t-hedge-in-the-impact-section': ["Bad: \"An attacker could potentially be able to access user data, which may lead to...\"", "Good: \"An attacker reads any user's profile data. Demonstrated on test user `victim@target.com` at 14:22 IST.\""],
    '3-don-t-generic-cia-the-impact': ["Bad: \"Loss of confidentiality and integrity of customer data\"", "Good: \"Read access to 247,000 customer records including PAN cards, addresses, GST numbers. India DPDPA Section 33 mandates 72-hour breach disclosure to DPB.\""],
    '4-don-t-list-every-recon-finding-as-a-finding': ["Recon notes (subdomains found, ports open, technologies fingerprinted) belong in a separate **Recon / Attack Surface** appendix, not the findings list. A finding must have an attacker-attainable outcome."],
    '5-don-t-bury-the-poc': ["Each finding MUST have reproducible steps. The PoC section is what proves the finding to a skeptical reader. If you can't write the PoC clearly, the finding probably isn't ready to ship."],
    'document-level-structure': ["1. Executive Summary (1 page, non-technical)", "- Engagement overview (dates, scope)", "- Risk posture summary (heat-map: <X critical, Y high, Z medium...>)", "- Top 3 strategic recommendations", "- Comparison to industry baseline (optional)", "2. Engagement Details", "- Scope (in-scope, out-of-scope, exclusions)", "- Methodology (recon \u2192 exploit \u2192 reporting; or align with PTES / OSSTMM)", "- Tools used", "- Timeline (start / end / key milestones)", "- Team", "3. Risk Summary Table", "4. Findings (one per ## section, in severity order \u2014 Critical first)", "5. Attack Surface / Recon Appendix", "- Subdomains discovered", "- Open ports / services", "- Technology fingerprints", "- APKs found", "- Credentials in breach corpora (count + sample only \u2014 redact)", "- Identity-fabric map (IdP, MFA posture)", "6. Indicators of Compromise (IoCs)", "- Source IPs used during testing (so SOC can correlate)", "- User-Agent strings", "- Test accounts created", "- Files uploaded (with cleanup status)", "7. Cleanup Statement", "- Confirmation that all test artifacts (accounts, uploads, persistence) were removed", "- Outstanding cleanup items requiring client action", "8. Appendices (raw output, screenshots index, full target list)"],
    'docx-generation-pipeline-markdown-docx-with-embedded-images': ["```bash"],
    'prerequisite-pandoc-installed': ["brew install pandoc"],
    'convert': ["pandoc REPORT_FINAL.md \\", "-o REPORT_FINAL.docx \\", "--resource-path=engagement_log/poc \\", "--reference-doc=~/.claude/skills/redteam-report-template/templates/reference.docx \\", "--toc \\", "--toc-depth=2 \\", "--highlight-style=tango"],
    'verify-image-count': ["python3 -c \"", "from docx import Document", "d = Document('REPORT_FINAL.docx')", "imgs = [r for r in d.part.rels.values() if 'image' in r.target_ref]", "print(f'Embedded images: {len(imgs)}')", "print(f'Paragraphs: {len(d.paragraphs)}')", "print(f'Headings: {sum(1 for p in d.paragraphs if p.style.name.startswith(\\\"Heading\\\"))}')"],
    'image-filename-convention': ["screenshots/F<NN>_<descriptive>.png", "Examples:", "F01_locked_accounts.png", "F02a_saml_landing.png", "F02b_saml_ca_block_page.png", "F03_sqli_timing_chart.png", "F15_saml_metadata.png", "Variants get letter suffixes (F02a, F02b). Always zero-pad finding number."],
    'writing-tone-for-client-deliverables': ["**Always:**", "- Use past tense for observations (\"The endpoint returned a 200 status code\")", "- Use present tense for descriptions of the flaw (\"The application does not validate...\")", "- Use imperative for recommendations (\"Apply patch ... by ...\")", "- Number reproduction steps; never \"first... then... also...\"", "**Never:**", "- \"Could potentially\" \u2014 prove it or drop it", "- \"It might be possible\" \u2014 same", "- \"We recommend implementing security best practices\" \u2014 say which one specifically", "- \"The application is vulnerable to...\" without saying what specifically"],
    'audience-translation-same-finding-different-framing': ["Example: hardcoded JWT in APK", "The same finding's Impact paragraph should cover both ends \u2014 start with the business outcome, then drop into technical detail."],
    'findings-that-are-sometimes-wrongly-excluded': ["Red-team deliverables should include \u2014 not just bug-bounty payable bugs:", "- **Information disclosure that helps attack mapping** (CodeIgniter debug toolbar leaking routes, version banners on appliances) \u2014 Medium", "- **User enumeration** (Microsoft OneDrive 302 vs 404 differential) \u2014 Medium", "- **Pre-existing security state observations** (247 accounts already locked by external attacker; weak password policies) \u2014 Informational with stakeholder relevance", "- **Defensive observations** (SOC patched our SQLi within 30 min \u2014 evidence of working detection) \u2014 Informational/positive", "- **Sister-app pattern issues** (same code template across 7 apps) \u2014 Medium (multiplied blast radius)", "Bug bounty would reject most of these. Red-team deliverables embrace them \u2014 the client paid for the assessment to know."],
    'mid-engagement-events-to-document': ["Beyond findings themselves, the deliverable should include:", "- Detected SOC responses (timestamps when defenses kicked in)", "- Concurrent external attacker activity (if any was observed)", "- Findings the client patched during the engagement (with PoC pre-patch as evidence)", "- Tooling failures (e.g., MCP timeout, CAPTCHA not solvable) \u2014 these affect what was/wasn't testable", "Each gives the client context about their real-world detection capability, which often matters more than the findings themselves."],
    'template-library-where-to-put-canned-text': ["Maintain reusable boilerplate in:", "~/.claude/skills/redteam-report-template/templates/", "executive_summary.md      # Reusable exec summary skeleton", "methodology.md            # Standard methodology section", "cleanup_statement.md      # Standard cleanup language", "reference.docx            # Pandoc style template (fonts, headings, colors)", "cover.docx                # Cover page template", "Don't write these from scratch each engagement; clone and customize."],
    'quality-checks-before-delivery': ["Pre-delivery checklist:", "- [ ] Every finding has all 6 sections populated (no \"TBD\")", "- [ ] Every finding has at least one screenshot or HTTP-level evidence", "- [ ] Every PoC includes redactions for client PII (mask emails, phone numbers, IDs)", "- [ ] Every screenshot is referenced in the MD with a relative path that resolves", "- [ ] DOCX render check \u2014 image count matches MD reference count", "- [ ] Severity ordering: Critical findings first, then High, etc.", "- [ ] Executive summary is updated to match final findings (count, themes)", "- [ ] Cleanup statement explicitly says what was created and what was removed", "- [ ] IoC section enables the SOC to reconstruct what they saw", "- [ ] Spell-check (especially client company name, product names)", "- [ ] All tool versions noted in methodology", "- [ ] Status field set correctly on every finding (especially patched-mid-engagement)"],
    'bridge-to-neighboring-skills': ["- `report-writing` \u2014 bug-bounty platform reports (different format, different audience)", "- `redteam-mindset` \u2014 informs what counts as a finding worth shipping", "- `mid-engagement-ir-detection` \u2014 informs the \"patched mid-engagement\" status pattern", "- `evidence-hygiene` \u2014 informs screenshot redaction discipline", "- `m365-entra-attack`, `enterprise-vpn-attack`, etc. \u2014 each provides finding-templates specific to its attack surface"],
    'anti-patterns': ["- **DO NOT** write a 50-page report for 3 findings \u2014 pad-by-page erodes credibility", "- **DO NOT** use the same severity for everything \u2014 calibrate", "- **DO NOT** copy-paste OWASP top-10 boilerplate into Description sections", "- **DO NOT** include findings without PoCs \u2014 they read as speculative", "- **DO NOT** skip the Recommendation section's specificity \u2014 \"patch and review\" doesn't help", "- **DO NOT** mix bug-bounty CVSS scoring with red-team severity unthinkingly \u2014 context differs (e.g., a Medium on a CVSS basis can be Critical for the client if it touches a regulated dataset)"],
    'real-engagement-metric-authorized-engagement': ["For calibration:", "- 14 findings shipped (2 Critical, 4 High, 5 Medium, 3 Low/Info)", "- 18 screenshots embedded", "- 52,737 bytes markdown / 2,262,484 bytes DOCX", "- 414 paragraphs, 123 headings in DOCX", "- 16 inline images (2 were inline in MD-only edge cases)", "- Time-to-deliverable: ~6 hours after engagement close for first draft", "These numbers are typical for a 1-week external red-team engagement on a mid-size enterprise. Scale down for short tests, up for full purple-team exercises."],
    'related-skills-chains': ["- **`triage-validation`** \u2014 This template ingests findings that have ALREADY passed the 7-Question Gate. Engagement flow: every finding through `triage-validation` first \u2192 only validated findings \u2192 `redteam-report-template` packaging. Skipping triage produces a deliverable padded with informational noise that erodes client trust.", "- **`evidence-hygiene`** \u2014 The DOCX with 16 embedded screenshots only works if evidence was captured systematically throughout the engagement. Engagement flow: `evidence-hygiene` discipline at session start \u2192 timestamped, organized screenshot folder \u2192 `redteam-report-template` consumes that folder to populate Evidence blocks.", "- **`redteam-mindset`** \u2014 The Subject / Observations / Description / Impact / Recommendation / PoC structure assumes the operator already thinks like a red-teamer (impact-first, blast-radius framing). Engagement flow: `redteam-mindset` loaded at engagement start \u2192 findings collected with red-team framing baked in \u2192 `redteam-report-template` produces deliverable without rewriting every Impact section.", "- **`mid-engagement-ir-detection`** \u2014 Defensive-action findings (SOC patches mid-test, new IPS rules deployed, account lockouts triggered by external attacker) are first-class findings in red-team deliverables. Engagement flow: `mid-engagement-ir-detection` captures behavior-change events \u2192 each becomes its own Subject in the deliverable, framed as \"client capability observation\" not as \"bug we missed.\"", "- **`report-writing`** + **`bugcrowd-reporting`** \u2014 Bug-bounty platform reports use DIFFERENT structure (one finding per submission, platform-specific severity scoring, OOS-clause counters). Engagement flow: if engagement mode is `bug-bounty` per project memory \u2192 use `report-writing` / `bugcrowd-reporting` instead. This template is ONLY for external red-team / enterprise client deliverables."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()