#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: hack-skills/business-logic-vulnerabilities

Skill: SKILL: Business Logic Vulnerabilities — Expert Attack Playbook
Desc : >-

Run:  python hack-skills-business-logic-vulnerabilities.py --help
      python hack-skills-business-logic-vulnerabilities.py --list
      python hack-skills-business-logic-vulnerabilities.py --dump <section>
"""
import sys, json, argparse

NAME = 'hack-skills/business-logic-vulnerabilities'
TITLE = 'SKILL: Business Logic Vulnerabilities — Expert Attack Playbook'
DESCRIPTION = '>-'

PAYLOADS = {
    'main': ["name: business-logic-vulnerabilities", "description: >-", "Business logic vulnerability playbook. Use when reasoning about workflows, race conditions, price manipulation, coupon abuse, state machines, and multi-step authorization gaps."],
    'skill-business-logic-vulnerabilities-expert-attack-playbook': [],
    'companion-files': [],
    'extended-scenarios': ["Also load [SCENARIOS.md](./SCENARIOS.md) when you need:", "- Payment precision & integer overflow attacks \u2014 32-bit overflow to negative, decimal rounding exploitation, negative shipping fees", "- Payment parameter tampering checklist \u2014 price, discount, currency, gateway, return_url fields", "- Condition race practical patterns \u2014 parallel coupon application, gift card double-spend with Burp group send", "- Captcha bypass techniques \u2014 drop verification request, remove parameter, clear cookies to reset counter, OCR with tesseract", "- Arbitrary password reset \u2014 predictable tokens (`md5(username)`), session replacement attack, registration overwrite", "- User information enumeration \u2014 login error message difference, masked data reconstruction across endpoints, base64 uid cookie manipulation", "- Frontend restriction bypass \u2014 array parameters for multiple coupons (`couponid[0]`/`couponid[1]`), remove `disabled`/`readonly` attributes", "- Application-layer DoS patterns \u2014 regex backtracking, WebSocket abuse"],
    '1-price-and-value-manipulation': [],
    'negative-quantity-price': ["Many applications validate \"amount > 0\" but not for currency:", "Add to cart with quantity: -1", "Update quantity to: -100", "\"quantity\": -5,", "\"price\": -99.99     \u2190 may be accepted", "**Impact**: Receive credit to account, items for free, bank transfers in reverse."],
    'decimal-quantity-0-case': ["Real instructor-led case: an e-commerce app accepted **fractional `quantity`** because backend trusted client float values:", "```json", "// Cart item:", "{\"id\": 114016, \"skuQty\": 0.02}", "// Original price \u00a5500 \u2192 final price \u00a510", "// Variant on a food delivery app:", "// FoodNum=0.01 \u2192 68\u5143 \u5546\u54c1 \u5b9e\u4ed8 0.68\u5143", "Why it works: server multiplies `unit_price * quantity` without enforcing `quantity \u2208 Z+`, so a 2% sliver order pays 2% price but ships the full item. Reproduce by intercepting the cart submit \u2192 setting `skuQty` / `FoodNum` to `0.02` \u2192 finishing checkout."],
    'drop-a-required-field-free-tier-coercion': ["Sport activity registration: when paid prizes are involved server returns `\"payType\": \"paid\"`; if the client request is **edited to omit `prizeIdList` entirely**, the server falls back to `\"payType\": \"free\"` and creates a successful registration that should have cost money.", "```json", "// Original", "{\"prizeIdList\": [\"6264e6948fe587000113e2d9\"], ...}", "// Modified \u2014 array removed entirely", "{\"prizeIdList\": [], ...}", "// Server response:", "{\"ok\": true, \"payType\": \"free\"}", "This is a parameter-existence trust bug \u2014 backend treats \"field absent\" as \"no paid item to enforce\", so fix is to require the field and validate its content server-side."],
    'integer-overflow': ["quantity: 2147483648   \u2190 INT_MAX + 1 overflows to negative in 32-bit", "price: 9999999999999   \u2190 exceeds float precision \u2192 rounds to 0", "Real case: setting `amount=999999999` triggered an overflow path where the system stored `0` as final payable. **Always coordinate before triggering overflow tests** \u2014 they sometimes crash payment services."],
    'rounding-manipulation': ["Item price: $0.001", "Order 1000 items \u2192 each rounds down \u2192 total = $0.00", "Real \"half-price recharge\" bug: input `\u00a50.019` to top-up. The pay gateway charges only `\u00a50.01` (rounded down to the cent), but the wallet credits `\u00a50.02` (rounded up). Net gain per cycle is `\u00a50.01`, repeat for free balance growth."],
    'currency-exchange-rate-lag': ["1. Deposit using currency A at rate X", "2. Rate changes", "3. Withdraw using currency A at new rate \u2192 profit from rate difference"],
    'free-upgrade-via-promo-stacking': ["Test combining discount codes, referral credits, welcome bonuses:", "Apply promo: FREE50  \u2192 50% off", "Apply promo: REFER10 \u2192 additional 10%", "Apply loyalty points \u2192 additional discount", "Total: -$5 (free + credit)"],
    '2-race-conditions': ["**Concept**: Two operations run simultaneously before the first completes its check-update cycle."],
    'double-spend-double-redeem': ["```bash"],
    'send-same-request-simultaneously-millisecond-apart': [],
    'use-burp-repeater-send-to-group-or-race-conditions-tool': ["POST /api/use-coupon    \u2190 send 20 parallel requests", "POST /api/redeem-gift   \u2190 same coupon code, parallel", "POST /api/withdraw-funds \u2190 same balance, parallel"],
    'if-check-and-update-are-non-atomic': [],
    'thread-1-check-balance-100-true': [],
    'thread-2-check-balance-100-true-before-thread-1-deducted': [],
    'thread-1-balance-100': [],
    'thread-2-balance-100-both-succeed-double-spend': [],
    'race-condition-test-with-burp-suite': ["1. Capture request", "2. Send to Repeater \u2192 duplicate 20+ times", "3. \"Send group in parallel\" (Burp 2023+)", "4. Check: did any duplicate succeed?"],
    'turbo-intruder-bypassing-per-number-sms-rate-limit': ["Real case: when a normal request returns `\"\u8be5\u53f7\u7801\u77ed\u65f6\u95f4\u5185\u7533\u8bf7\u53d1\u9001\u77ed\u4fe1\u6b21\u6570\u8fc7\u591a\uff0c\u62d2\u7edd\u53d1\u9001\"`, sending the **same payload** with high concurrency through Turbo Intruder defeats the simple counter:", "```python", "def queueRequests(target, wordlists):", "engine = RequestEngine(endpoint=target.endpoint,", "concurrentConnections=30,", "requestsPerConnection=10,", "pipeline=False)", "for i in range(30):", "engine.queue(target.req, target.baseInput, gate='race1')", "engine.openGate('race1')", "Result: the per-phone limiter races and many requests slip through, generating multiple distinct verification codes (a real SMS-bombing case). Root cause: counter increment is non-atomic vs. the read."],
    'multi-device-concurrent-vip-subscription': ["Real case: a service offers **first-month-only discount**. Open the pay sheet on multiple devices (A, B, C) before any payment finishes, then complete each in sequence. Server only checks \"is new user?\" at the **first** request, so all subsequent requests inherit the discount AND the VIP duration stacks.", "Normal: \u4e0b\u5355 \u2192 \u652f\u4ed8 \u2192 \u5145\u503c\u4f1a\u5458 \u2192 \u7b2c\u4e8c\u6b21\u4e0b\u5355 \u2192 \u670d\u52a1\u7aef\u6821\u9a8c \"\u5df2\u662f\u65b0\u4eba\" \u2192 \u62d2\u7edd", "Bypass: \u8bbe\u5907A: \u8fdb\u5165\u652f\u4ed8\u9875 (\u9501\u5b9a\u4f18\u60e0\u8d44\u683c)", "\u8bbe\u5907B: \u8fdb\u5165\u652f\u4ed8\u9875 (\u5e76\u53d1\u9501\u5b9a)", "\u8bbe\u5907A: \u5b8c\u6210\u652f\u4ed8 \u2192 VIP +1\u6708 (\u4f18\u60e0\u4ef7)", "\u8bbe\u5907B: \u5b8c\u6210\u652f\u4ed8 \u2192 VIP +1\u6708 (\u4ecd\u6309\u4f18\u60e0\u4ef7)", "Same trick works on \"\u8865\u5dee\u4ef7\u5347\u7ea7\u4f1a\u5458\" \u2014 concurrent top-ups duplicate the duration credit."],
    'account-registration-race': ["Register with same email simultaneously \u2192 two accounts created \u2192 data isolation broken", "Password reset token race \u2192 reuse same token twice", "Email verification race \u2192 verify multiple email addresses"],
    'limit-bypass-via-race': ["\"Claim once\" discounts, freebies, \"first order\" bonus:", "\u2192 Send 10 parallel POST /claim requests", "\u2192 Race window: all pass the \"already claimed?\" check before any write"],
    '3-workflow-step-skip-bypass': [],
    'payment-flow-bypass': ["Normal flow:", "1. Add to cart", "2. Enter shipping info", "3. Enter payment (card/wallet)", "4. Click confirm \u2192 payment charged", "5. Order confirmed", "Attack: Skip to step 5 directly", "POST /api/orders/confirm {\"cart_id\": \"1234\", \"payment_status\": \"paid\"}", "\u2192 Does server trust client-sent payment_status?"],
    'multi-step-verification-skip': ["Password reset flow:", "1. Enter email", "2. Receive token", "3. Enter token", "4. Set new password (requires valid token from step 3)", "Attack: Try going to step 4 without completing step 3:", "POST /reset/password {\"email\": \"victim@x.com\", \"token\": \"invalid\", \"new_pass\": \"hacked\"}", "\u2192 Does server check that token was properly validated?", "Or: Try token from old/expired flow \u2192 still accepted?"],
    '2fa-bypass': ["Normal flow:", "1. Enter username + password \u2192 success", "2. Enter 2FA code \u2192 logged in", "Attack: After step 1 success, go directly to /dashboard", "\u2192 Is session created before 2FA completes?", "\u2192 Does /dashboard require 2FA-complete check or just \"authenticated\" flag?"],
    'filter-path-truncation-bypass-and': ["Real case from a Java Web class audit: a manually-implemented Servlet `Filter` checks login by inspecting the URI string. Two reliable bypasses:", "Path-traversal truncation (../):", "Protected:   http://target/FilterDemo/index.jsp        \u2192 302 to /login", "Bypass:      http://target/FilterDemo/../../index.jsp  \u2192 200 (filter sees \"../../\", URL parser collapses)", "Semicolon truncation (;):", "Protected:   http://target/admin/doLogin.action        \u2192 302 to /login", "Bypass:      http://target/;/admin/doLogin.action      \u2192 200", "Servlet container treats segment after ; as \"path parameter\",", "filter that uses request.getRequestURI() sees \"/;/admin/doLogin.action\",", "doesn't match its protected-prefix \"/admin/\", lets the request through,", "but the dispatcher then routes to the real /admin/doLogin.action handler.", "**Fix**: never use `request.getRequestURI()` for security checks; use `request.getServletPath()` which is the normalized servlet-mapped path:", "```java", "// Vulnerable", "String uri = request.getRequestURI();   // /;/admin/doLogin.action", "// Safe", "String path = request.getServletPath(); // /admin/doLogin.action", "When auditing Java code, grep for `request.getRequestURI()` paired with `Filter`/`startsWith`/`indexOf(\"/admin\")` patterns \u2014 those are immediate red flags."],
    'real-name-verification-replay-to-reset': ["Fraudulent path that deliberately fails real-name authentication to **reopen** the editing flow:", "1. Submit real-name auth with intentionally wrong cardNumber", "\u2192 server returns \"code:200, msg:success, ok:true\" but flow shows \"\u9a73\u56de / \u7b49\u5f85\u5ba1\u6838\"", "2. Because the server marks state as \"rejected\" but doesn't lock the user, the UI lets the", "account go back into the \"edit identity\" state", "3. Now resubmit with another (possibly stolen) identity", "\u2192 real-name binding repeats indefinitely, defeating anti-addiction lock and enabling account resale", "Defense: rejected real-name submissions must lock the account / require human review, not loop back to the editor."],
    'shipping-without-payment': ["1. Add item to cart", "2. Enter shipping address", "3. Select payment method (credit card)", "4. Apply promo code (100% discount or gift card)", "5. Final amount: $0", "6. Order placed", "Attack: Apply 100% discount code \u2192 no actual payment processed \u2192 item ships"],
    '4-coupon-and-referral-abuse': [],
    'coupon-stacking': ["Test: Can you apply multiple coupon codes?", "Test: Does \"SAVE20\" + promo stack to >100%?", "Test: Apply coupon, remove item, keep discount applied, add different item"],
    'referral-loop': ["1. Create Account_A", "2. Register Account_B with Account_A's referral code \u2192 both get credit", "3. Create Account_C with Account_B's referral code", "4. Ad infinitum with throwaway emails", "\u2192 Infinite credit generation"],
    'coupon-fixed-dollar-amount-on-variable-price-item': ["Coupon: -$5 off any order", "Buy item worth $3, use -$5 coupon \u2192 net -$2 (credit balance)"],
    '5-account-privilege-logic-flaws': [],
    'email-verification-bypass': ["1. Register with email A (legitimate, verified)", "2. Change email to B (attacker's email, unverified)", "3. Use account as verified \u2014 does server enforce re-verification?", "Or: Change email to victim's email \u2192 no verification \u2192 account claim"],
    'password-reset-token-binding': ["1. Request password reset for your account \u2192 get token", "2. Change your email address (account settings)", "3. Reuse old password reset token \u2192 does it still work for old email?", "Or: Request reset for victim@target.com", "Token sent to victim but check: does URL reveal predictable token pattern?"],
    'oauth-account-linking-abuse': ["1. Have victim's email (but not their password)", "2. Register with victim's email \u2192 get account with same email", "3. Link OAuth (Google/GitHub) to your account", "4. Victim logs in with Google \u2192 server finds email match \u2192 merges with YOUR account"],
    'cookie-replacement-horizontal-vertical-privilege-escalation': ["The textbook IDOR demo from the audit videos:", "1. Login as super-admin \u2192 capture request, copy Cookie (JSESSIONID/Token)", "2. Logout, login as plain user \u2192 capture another request to the SAME endpoint", "3. Replay the plain-user request, but swap the Cookie value with the admin's token", "4. If the response returns admin-only data \u2192 vertical escalation", "If it returns another-user's data \u2192 horizontal escalation", "A common companion bug: `/oa/emp/list` returns **HTTP 302 to /login when no cookie**, but **200 with full data when any plain-user cookie is sent** \u2014 meaning the only check is \"logged in?\", not \"authorized for this endpoint\"."],
    'permission-residue-from-database-inconsistency': ["A subtle case from the second audit class: the admin UI shows that role X has had permission `user:list` revoked, but querying the SQL data:", "```sql", "SELECT * FROM sys_menu WHERE role_id = 2;", "-- two rows for the same menu_id \"user:list\"", "The UI's \"remove permission\" only deleted ONE row; the duplicate row keeps the API accessible. Verify by:", "```sql", "SELECT menu_id, COUNT(*) FROM sys_menu GROUP BY menu_id, role_id HAVING COUNT(*) > 1;", "Lesson: when a UI says permission revoked but API still works \u2192 check the underlying RBAC table for duplicates / orphaned grants."],
    'weak-random-password-reset-token': ["PHP / legacy stack on Windows uses `rand()` whose `RAND_MAX = 32768`. If a reset link uses", "`/resetpassword.php?id=md5(rand())`, the entire keyspace is precomputable:", "```php", "$a = 0;", "for ($a = 0; $a <= 32768; $a++) {", "$b = md5($a);", "echo $b . \"\\r\\n\";", "Iterate the resulting dictionary against `/resetpassword.php?id=<hash>` \u2014 when one returns a valid reset page you can change the victim's password. Audit any token generation that ultimately calls `rand()`, `mt_rand()` (without seeding), `Random()` (default seed in C#), etc."],
    '6-api-business-logic-flaws': [],
    'object-state-manipulation': ["order.status = \"pending\"", "\u2192 PUT /api/orders/1234 {\"status\": \"refunded\"}   \u2190 self-trigger refund", "\u2192 PUT /api/orders/1234 {\"status\": \"shipped\"}    \u2190 mark as shipped without shipping"],
    'transaction-reuse': ["1. Initiate payment \u2192 get transaction_id", "2. Complete purchase", "3. Reuse same transaction_id for second purchase:", "POST /api/checkout {\"transaction_id\": \"USED_TX\", \"cart\": \"new_cart\"}"],
    'limit-count-manipulation': ["Daily transfer limit = $1000", "\u2192 Transfer $999, cancel, transfer $999 (limit not updated on cancel)", "\u2192 Parallel transfers (race condition on limit check)", "\u2192 Different payment types not sharing limit counter"],
    'java-web-no-filter-no-spring-security-anti-pattern': ["Audit-friendly tell: a Spring Boot project that does **NOT** include `spring-boot-starter-security` and has zero `Filter` classes. This means every controller is wide-open for `guest` unless the developer manually checked the session in each method. Reproduce:", "```bash"],
    'inside-the-source-tree': ["find . -name \"*.java\" -exec grep -l \"Filter\" {} \\;     # likely empty", "find . -name \"*.java\" -exec grep -l \"@PreAuthorize\\|@Secured\" {} \\;", "If both are empty, expect almost every API to be unauthorized. From the audit demo:", "```java", "public Result score(@RequestParam(\"userId\") Integer userId) {", "Score score = scoreService.selectScoreByUserId(userId);", "return Result.success(score);", "No check that `userId` matches the session's logged-in user \u2192 horizontal IDOR. Worse: the same endpoint works **without any Cookie**, since nothing forces authentication globally."],
    'spring-security-antmatchers-coverage-gap': ["The audit videos also showed a partially-secured Spring Security config like:", "```java", ".antMatchers(\"/system/user/info\").authenticated()", ".antMatchers(\"/system/menu/**\").hasRole(\"admin\")", "A common error is an over-narrow rule \u2014 e.g. `/system/user/info` is protected but `/system/user/list` is not, or `/system/menu/**` is admin-only but `/system/dept/treeData` is open. Cross-check the controller annotations (`@PreAuthorize(\"@ss.hasPermi('system:user:list')\")`) against the SecurityConfig \u2014 every annotated endpoint must also map to a SecurityConfig rule. Mismatches are common after refactors."],
    '7-subscription-tier-confusion': ["Free tier: cannot access feature X", "Paid tier: can access feature X", "Attack:", "- Sign up for paid trial \u2192 enable feature X \u2192 downgrade to free", "\u2192 Does feature X get disabled on downgrade?", "\u2192 Can you continue using feature X?", "- Inspect premium endpoint list from JS bundle", "- Directly call premium endpoints with free account token", "\u2192 Server checks subscription for UI but not API?"],
    'direct-media-url-leak-vip-resource-bypass': ["Real cases from a fitness/learning app: when the client requests course detail, the JSON response embeds the raw media URL:", "```http", "GET /gerudo/v2/liveCourse/625020ce8f002700010554c1/detail HTTP/1.1", "\"previewPullUrl\": \"http://app-live.../live/app-live_625020ce8f002700010554c2_Preview.flv\"", "Search **all** detail / preview / playback responses for keywords:", ".flv  .m3u8  .mp4  .mp3  videoUrl  downloadUrl  streamUrl  previewPullUrl", "For each hit, replay the URL anonymously (curl, VLC, flv.js demo at `https://bilibili.github.io/flv.js/demo/`). If the URL plays without a session, you've broken VIP gating. Defense: use signed, short-TTL URLs bound to user/IP/Referer, not raw resource paths."],
    'resource-id-replacement-free-paid-course': ["Companion bug: free course detail returns `{\"id\": \"60caa21e853f5c1651b27c1b\", ...}`. Replace the ID in the URL with a known paid course ID. If the response structure remains the same and includes the playable URL \u2192 IDOR on premium content. Defense: verify the **owner relation** on each detail call, not just \"is logged-in\"."],
    '8-file-upload-business-logic': ["For the full upload attack workflow beyond pure logic flaws, also load:", "- [upload insecure files](../upload-insecure-files/SKILL.md)", "Upload size limit: 10MB", "\u2192 Upload 10MB \u2192 compress client-side \u2192 server decompresses \u2192 bomb?", "(Zip bomb: 1KB zip \u2192 1GB file = denial of service)", "Upload type restriction:", "\u2192 Upload .csv for \"data import\" \u2192 inject formulas: =SYSTEM(\"calc\")", "(CSV injection in Excel macro context)", "\u2192 Upload avatar \u2192 server converts \u2192 attack converter (ImageMagick, FFmpeg CVEs)", "Storage path prediction:", "\u2192 /uploads/USER_ID/filename", "\u2192 Can you overwrite other user's file by knowing their ID + filename?"],
    '9-testing-approach': ["For each business process:", "1. Map the INTENDED flow (happy path)", "2. Ask: \"What if I skip step N?\"", "3. Ask: \"What if I send negative/zero/MAX values?\"", "4. Ask: \"What if I repeat this step twice?\" (idempotency)", "5. Ask: \"What happens if I do A then B instead of B then A?\"", "6. Ask: \"What if two users do this simultaneously?\"", "7. Ask: \"Can I modify the 'trusted' status fields?\"", "8. Think from financial/resource impact angle \u2192 highest bounty", "For the formal 5-phase workflow \u2014 Business Modeling \u2192 State Machine \u2192 Attack-Surface Matrix \u2192 Checklist-Driven Testing \u2192 Human Judgement \u2014 load **[METHODOLOGY.md](./METHODOLOGY.md)**. It includes a single-page decision tree (`Q1 ~ Q7`) for \"I'm staring at a request and don't know what to try first\"."],
    '10-high-impact-checklists': ["For the full per-module list (login / register / password recovery / payment / coupon / order / IDOR / privacy / VIP / URL redirect / cookie & token / race / comments) with `why` and `verify` columns \u2014 load **[CHECKLIST.md](./CHECKLIST.md)**.", "The condensed top-impact items below are the \"if you have only 30 minutes, hit these first\" set:"],
    'e-commerce-payment': ["\u25a1 Negative quantity / decimal quantity (skuQty=0.02, FoodNum=0.01) in cart", "\u25a1 Drop required fields (delete prizeIdList) to coerce free tier", "\u25a1 amount=999999999 integer overflow \u2192 final 0", "\u25a1 Apply multiple conflicting coupons via array params", "\u25a1 Race condition: double-spend gift card / same coupon", "\u25a1 Skip payment step directly to order confirmation", "\u25a1 Server-trusted client status fields (payment_status=paid, success:true)", "\u25a1 Refund without return (trigger refund on delivered item via state change)", "\u25a1 Multi-device concurrent VIP subscription / \u8865\u5dee\u4ef7\u5347\u7ea7", "\u25a1 Currency rounding exploitation (\u00a50.019 charge \u2192 \u00a50.02 wallet credit)"],
    'authentication-account': ["\u25a1 2FA bypass by direct URL access after password step", "\u25a1 Filter bypass: ../../path traversal truncation, ;path-parameter truncation", "\u25a1 Password reset token reuse after email change", "\u25a1 Weak random reset token: md5(rand()) on Windows PHP, predictable seed", "\u25a1 Email verification bypass (change email after verification)", "\u25a1 OAuth account takeover via email match", "\u25a1 Register with existing unverified email", "\u25a1 Cookie replacement (admin \u2192 user / user \u2192 another user)", "\u25a1 Real-name verification \"\u6545\u610f\u586b\u9519\" replay-to-reset"],
    'subscriptions-limits-resources': ["\u25a1 Access premium features after downgrade", "\u25a1 Exceed rate/usage limits via parallel requests (Turbo Intruder)", "\u25a1 Referral loop for infinite credits", "\u25a1 Free trial \u2260 time-limited (no enforcement after trial)", "\u25a1 Direct API call to premium endpoint without subscription check", "\u25a1 Free-course ID swap to paid-course ID (IDOR on resource)", "\u25a1 Direct media URL exposure in JSON (.flv / .m3u8 / .mp4 in response)", "\u25a1 Server-side RBAC residue (sys_menu duplicate rows)", "\u25a1 Java Web no-Filter / Spring Security antMatchers gap"],
    '11-consolidated-checklist-2-hour-full-sweep': ["The Section 10 list is the \"30-minute money grab\". This list is the next layer:", "when you have a couple of hours and want a defensive-grade sweep across all", "nine business surfaces. It's organized by surface, then by attack mechanism", "inside the surface, so you can read a column-down for \"what classes of bug", "might exist on this endpoint\" and a row-across for \"where else does this", "attack apply\".", "For full `item / why / verify` triplets including reproduction steps and", "tooling per item, load **[CHECKLIST.md](./CHECKLIST.md)**. This section", "keeps only the item line for fast scanning."],
    '11-1-login-authentication': ["\u25a1 Username enumeration via response diff (msg / status code / timing)", "\u25a1 Username enumeration via SMS-send response (sent vs not-registered)", "\u25a1 Brute force without lockout (no rate limit on failed login)", "\u25a1 Default / weak credentials (admin/admin, root/123456) on backend & infra", "\u25a1 2FA bypass via direct URL after password step / replay 2FA token", "\u25a1 Client-trusted login flag (status=success, is_login=true in response body)", "\u25a1 Third-party / SSO callback IDOR (modify uid in callback to take over)", "\u25a1 Biometric liveness bypass (replay static photo / pre-recorded video)", "\u25a1 Open redirect in login/register (return_url, redirect, callback param)", "\u25a1 Hardware-key signature replay / forgery (USB-Key, PKI cert)"],
    '11-2-registration': ["\u25a1 Username / phone / email enumeration via \"already exists\" response", "\u25a1 Password strength only enforced client-side (set 123456 server-side)", "\u25a1 Skip multi-step registration (POST final step directly, miss email verify)", "\u25a1 Verification code not enforced (empty / random / fixed value passes)", "\u25a1 SMS / email code replay (same code used twice or across users)", "\u25a1 Re-register same username after logout, inherit old data / privileges", "\u25a1 Anti-fraud bypass via N similar virtual accounts (same device, diff email)", "\u25a1 Mass-register replay-protection missing (no nonce on submit step)"],
    '11-3-password-recovery-reset': ["\u25a1 Reset target tampering (uid / email / phone in submit step)", "\u25a1 Reset token predictable (timestamp-derived, weak hash, short random)", "\u25a1 Cross-user token reuse (A's reset_token, change B's password)", "\u25a1 Old-password check missing on logged-in change-password endpoint", "\u25a1 Skip code-verify step, hit final reset endpoint directly", "\u25a1 Reset link / answer / token leaked in HTML or JS source", "\u25a1 Reset token has no expiry / not invalidated after use", "\u25a1 Reset code base64-only \"obfuscated\" in response", "\u25a1 Inconsistent identity across multi-step flow (reset_token from step 2", "reusable in step 4)", "\u25a1 Old session not revoked after email/phone re-bind"],
    '11-4-session-token': ["\u25a1 Session fixation: pre-login session id remains valid after login", "\u25a1 Token not bound to user/IP/device (steal cookie \u2192 use anywhere)", "\u25a1 Forged token: weak algorithm md5(username + timestamp), no server salt", "\u25a1 Stale token still accepted after logout / expiry (no blacklist)", "\u25a1 Cookie tampering (uid / role / is_admin in cookie trusted server-side)", "\u25a1 State-machine replay (replay \"claim red packet\" \u2192 re-claim)", "\u25a1 Anti-replay missing on one-time tokens (CSRF token, OTP, nonce)", "\u25a1 Sensitive credentials (token, answer, key) hardcoded in front-end JS", "\u25a1 Privileged session created from public Session ID without re-auth", "\u25a1 Token works cross-environment (different IP, different UA, no validation)"],
    '11-5-payment-order': ["\u25a1 Amount tampering: amount = 0.01 / 0 / negative / 0.001", "\u25a1 Quantity tampering: quantity = -1 / 0.01 / 1.5 / 999999999", "\u25a1 Integer overflow: quantity * price wraps to 0 or negative", "\u25a1 Floating-point precision exploit (multi-decimal, accumulated rounding)", "\u25a1 Currency code swap (CNY \u2192 JPY/RUB at same numeric value)", "\u25a1 Coupon / discount field forge (coupon_id, discount=, free_shipping=true)", "\u25a1 Item ID swap: replace product_id with cheaper SKU at checkout", "\u25a1 Signature / sign-field bypass (drop sign param, use stale sign)", "\u25a1 Payment-callback forgery (status=paid posted to internal callback)", "\u25a1 Replay paid request \u2192 multiple shipments / multiple credit", "\u25a1 Race / concurrency: oversell, double-spend gift card, double redeem coupon", "\u25a1 Refund without losing the merchandise / virtual rights", "\u25a1 VIP duration tampering (days=999, months=120, period=-1)", "\u25a1 Receiver-account redirect (merchant_id / receiver_account swap on withdraw)", "\u25a1 Negative shipping / fee fields decreasing total (shipping_fee = -500)", "\u25a1 Concurrent topup-then-refund draining (refund > topup in race window)", "\u25a1 Pricing rule transition window (price changes at T, replay at T-\u03b5 with old rule)", "\u25a1 Currency rounding micro-arbitrage (charge 0.019 \u2192 wallet credit 0.02)", "\u25a1 Multi-channel inconsistency (online vs cash-on-delivery vs balance pay)"],
    '11-6-idor-authorization': ["\u25a1 Horizontal IDOR: uid / order_id / resource_id swap to victim's", "\u25a1 Vertical IDOR: role / type / level field set to admin in request", "\u25a1 Hidden field tampering (data-user-id in HTML / JS state)", "\u25a1 Email / phone re-bind without verifying old binding", "\u25a1 UID vs session-token consistency missing (token belongs to A, uid sent as B)", "\u25a1 Predictable / sequential resource IDs (gift IDs, share-link IDs)", "\u25a1 Resource enumeration on order / coupon / share / trip-detail endpoint", "\u25a1 Multi-entry inconsistency: web blocks, mobile API doesn't", "\u25a1 State-machine illegal transition (claim reward without paying / shipping", "before order paid)", "\u25a1 Hidden / undocumented admin endpoint accessible without admin auth", "\u25a1 Cross-role function call (user calls merchant API, rider API, etc.)", "\u25a1 Privilege via concurrent action (request role-elevation race condition)"],
    '11-7-captcha-verification-code': ["\u25a1 Code returned in plaintext in HTTP response (body / header / JS var)", "\u25a1 Receiver tampering: change phone / email param to attacker-controlled", "\u25a1 Empty / fixed code accepted (000000, blank, \"test\")", "\u25a1 Drop the code field entirely \u2192 request still succeeds", "\u25a1 Cross-account reuse (A's valid code accepted on B's flow)", "\u25a1 One-time enforcement missing (same code reusable until expiry)", "\u25a1 Brute force 4-6 digit code (no attempt limit, no lockout)", "\u25a1 SMS / email bombing (no rate limit per IP / per phone / no graphical CAPTCHA)", "\u25a1 Front-end-only \"send-success\" status (server says fail, FE says success)", "\u25a1 Code not bound to session (code generated for A, used in B's session)"],
    '11-8-file-upload': ["\u25a1 Content-Type bypass (Content-Type: image/jpeg, body is PHP)", "\u25a1 Extension trick: double ext (.php.jpg), case mix (.Php), null byte, ;path", "\u25a1 Filename path traversal (filename=../../webshell.php)", "\u25a1 File-content polyglot (image with embedded PHP / shell)", "\u25a1 Office XML repack (unzip docx \u2192 inject XML \u2192 rezip \u2192 upload)", "\u25a1 XXE via .xml / .dtd upload endpoint", "\u25a1 Backend-only upload (admin login \u2192 upload \u2192 exec)", "\u25a1 Upload race: upload + parallel access before AV scan / cleanup", "\u25a1 ZIP bomb (1KB \u2192 1GB on server, decompress DoS)", "\u25a1 CSV formula injection (=SYSTEM(\"calc\"), =cmd|'/c calc'!A1)", "\u25a1 Storage path predictable / overwritable across users (/uploads/UID/file)", "\u25a1 Image converter / parser CVE (ImageMagick, FFmpeg, pillow)"],
    '11-9-csrf-ssrf-xxe': ["\u25a1 XXE file read (<!ENTITY x SYSTEM \"file:///etc/passwd\">)", "\u25a1 XXE blind via OOB (parameter entity \u2192 DNSLog / Burp Collaborator)", "\u25a1 SSRF via image-import / webhook / preview URL (file://, http://127.0.0.1)", "\u25a1 SSRF via FTP / gopher / jar / php-wrapper / dict protocols", "\u25a1 XML parser dangerous wrappers enabled (php://expect, expect://)", "\u25a1 Out-of-band detection for blind injection (DNSLog confirms server hit)", "\u25a1 CSRF on state-changing endpoint (no token, no SameSite, no origin check)", "\u25a1 Payment / withdrawal CSRF via auto-submitting hidden form", "\u25a1 Login CSRF (force victim to log into attacker account)", "\u25a1 JSONP / JSONP-callback exploitation as CSRF read primitive"],
    'how-to-use-this-section': ["1. Print or screenshot the relevant 1-2 sub-sections for the target's surface.", "2. For each `\u25a1` mark: NOT-APPLICABLE / NOT-VULN / VULN / NEEDS-RECHECK.", "3. Mark the EXACT endpoint + parameter + payload that proved the bug", "(or proved it absent), so the report is reproducible.", "4. Cross-reference with `METHODOLOGY.md` Q1~Q7 decision tree when an item", "triggers something unexpected \u2014 the tree tells you which neighboring", "items are likely also vulnerable.", "5. For deep payloads / curl-ready commands / Burp screenshots per item,", "load `CHECKLIST.md` (full triplets) and `SCENARIOS.md` (real cases)."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()