#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/hunt-session

Skill: HUNT-SESSION — Session Management
Desc : Hunt Session Management vulnerabilities — session fixation (no regeneration on login), insufficient invalidation on logout / password-change / email-change, predictable or low-entropy session IDs, JWT-as-session with no exp/revocation, refresh-token rotation/reuse-detection gaps, OAuth/SSO session linkage, device-bound-session (DBSC) downgrade, and cookie attribute issues (Secure/HttpOnly/SameSite/__Host-). Validate with TWO real sessions (attacker A + victim B), body-diff every 200, and OOB confirmation for theft chains. Medium to Critical (fixation→admin hijack, no-invalidation→persistent ATO).

Run:  python claude-bughunter-hunt-session.py --help
      python claude-bughunter-hunt-session.py --list
      python claude-bughunter-hunt-session.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/hunt-session'
TITLE = 'HUNT-SESSION — Session Management'
DESCRIPTION = 'Hunt Session Management vulnerabilities — session fixation (no regeneration on login), insufficient invalidation on logout / password-change / email-change, predictable or low-entropy session IDs, JWT-as-session with no exp/revocation, refresh-token rotation/reuse-detection gaps, OAuth/SSO session linkage, device-bound-session (DBSC) downgrade, and cookie attribute issues (Secure/HttpOnly/SameSite/__Host-). Validate with TWO real sessions (attacker A + victim B), body-diff every 200, and OOB confirmation for theft chains. Medium to Critical (fixation→admin hijack, no-invalidation→persistent ATO).'

PAYLOADS = {
    'main': ["name: hunt-session", "description: \"Hunt Session Management vulnerabilities \u2014 session fixation (no regeneration on login), insufficient invalidation on logout / password-change / email-change, predictable or low-entropy session IDs, JWT-as-session with no exp/revocation, refresh-token rotation/reuse-detection gaps, OAuth/SSO session linkage, device-bound-session (DBSC) downgrade, and cookie attribute issues (Secure/HttpOnly/SameSite/__Host-). Validate with TWO real sessions (attacker A + victim B), body-diff every 200, and OOB confirmation for theft chains. Medium to Critical (fixation\u2192admin hijack, no-invalidation\u2192persistent ATO).\"", "sources: hackerone_public, portswigger_research, owasp_wstg", "report_count: 18"],
    'autonomous-testing-priority': ["**Missing HttpOnly on cookies is auto-detected \u2014 focus your active testing on lifecycle invalidation (higher impact).**", "**Pattern 1 \u2014 Session survives logout (most common high-value finding):**", "1. Login and note the session token/cookie value", "2. Call the logout endpoint (`/logout`, `POST /api/logout`, etc.)", "3. Try to use the OLD session token to access a protected resource (`/api/me`, `/dashboard`, `/account`)", "4. If 200 with user data \u2192 session not invalidated on logout = ATO persistence", "**Pattern 2 \u2014 Session not regenerated on login (session fixation):**", "1. GET any page to receive a pre-authentication session token/cookie", "2. POST valid credentials to the login endpoint", "3. Compare the session token BEFORE and AFTER login", "4. If the token is unchanged \u2192 session fixation vulnerability", "**Pattern 3 \u2014 Session survives password change:**", "1. Login \u2192 record session A value", "2. Change the password via the account settings endpoint", "3. Replay session A on a protected endpoint", "4. If 200 \u2192 token not rotated on credential change = persistent ATO (critical chain when combined with XSS/cookie theft)", "**Content-type:** Login and session endpoints vary \u2014 use `application/json` for REST APIs, `application/x-www-form-urlencoded` for traditional web forms. Try both if the first returns an unexpected response.", "**Proof:** A protected-resource 200 response (with user data) using a session token that should have been invalidated confirms the finding."],
    'hunt-session-session-management': [],
    'crown-jewel-targets': ["Session fixation leading to admin hijack = Critical. Session surviving a password change = High-to-Critical (persistent ATO from a stolen cookie that the victim believes they revoked by resetting their password).", "**Highest-value chains:**", "- **Session fixation** \u2014 server accepts a session ID set by the client and does NOT regenerate it on login \u2192 attacker pre-plants an ID, victim authenticates, attacker rides the now-authenticated session \u2192 persistent ATO.", "- **No invalidation on logout** \u2014 old token still works after `/logout` \u2192 theft window never closes.", "- **No invalidation on password / email change** \u2014 a stolen session survives the victim's \"I think I was hacked, let me reset\" \u2192 persistent ATO. This is the single highest-paid session bug class.", "- **Refresh-token reuse without rotation-detection** \u2014 a leaked refresh token mints fresh access tokens forever; no reuse-detection means the legitimate user's later refresh does NOT revoke the attacker's branch.", "- **Predictable / low-entropy session ID** \u2014 sequential, timestamp- or userId-derived IDs \u2192 brute-force or compute other users' sessions.", "- **JWT-as-session with no `exp` / no revocation list** \u2014 stolen JWT = permanent access; logout is cosmetic."],
    'grounding-patterns-that-shaped-each-phase': ["No invented CVE/report IDs below. These are the *named, publicly-documented* patterns this skill encodes:", "- **Session fixation, login-CSRF, no-regeneration-on-auth** \u2014 OWASP WSTG-SESS-03 / WSTG-SESS-01; the classic ACROS / Mitja Kol\u0161ek session-fixation paper. Highest-impact variant: fixing the session of an SSO/admin user.", "- **SameSite=Lax sibling-subdomain CSRF reaching session state** \u2014 Argo CD **CVE-2024-22424** (Lax cookies sent on top-level cross-site navigations from a sibling subdomain). Use this when a session cookie relies on `SameSite=Lax` as its only CSRF defence.", "- **Refresh-token rotation & automatic reuse-detection** \u2014 the Auth0/IETF OAuth-Security-BCP model: a rotated refresh token, if replayed, must invalidate the *entire token family*. Absence = the core bug to prove.", "- **Device Bound Session Credentials (DBSC)** \u2014 the W3C/Chrome DBSC draft binds a session to a TPM/device key. Test the *downgrade*: does the server still accept a non-bound cookie when the DBSC challenge is stripped?", "- **Cookie attribute hardening** \u2014 OWASP WSTG-SESS-02; `__Host-`/`__Secure-` prefixes per RFC 6265bis. Missing `HttpOnly` is only a finding when a real XSS/DOM sink exists (chain with `hunt-xss`/`hunt-dom`).", "- **Entropy** \u2014 NIST SP 800-63B requires \u226564 bits of entropy in a session identifier. Treat anything decodable to a counter/timestamp/userId as a finding regardless of length.", "Cross-refs: ATO chaining \u2192 `hunt-ato`; JWT alg/kid tampering \u2192 `hunt-api-misconfig`; OAuth code/state flaws \u2192 `hunt-oauth`; CSRF mechanics \u2192 `hunt-csrf`; cookie-theft sinks \u2192 `hunt-xss` / `hunt-dom`."],
    'attack-surface-signals': ["Set-Cookie: session=...            # name varies: sid, JSESSIONID, connect.sid,", "/login /logout /api/login /oauth/token", "/auth/refresh /api/token/refresh   # refresh-token rotation surface", "/account/change-password /settings/email", "?sid= ?session= in URL             # session-in-URL \u2192 leaks via Referer/logs (finding)"],
    'header-signals-worth-flagging-immediately': ["Set-Cookie: session=abc; Path=/                 # no HttpOnly/Secure/SameSite", "Set-Cookie: session=abc; SameSite=None          # None without Secure = rejected by modern browsers, but flag", "Set-Cookie: __Host-sess=...; Secure; Path=/     # GOOD \u2014 hard to fixate", "Sec-Session-Registration: ...                   # DBSC in play \u2192 test downgrade"],
    'step-by-step-hunting-methodology': ["```bash", "TARGET=target.com", "JAR_A=$(mktemp); JAR_B=$(mktemp)"],
    'robust-session-cookie-extractor-handles-httponly-prefix-lines-and-any': [],
    'cookie-name-sid-jsessionid-connect-sid-phpsessid-prints-name-value': ["get_cookie () {  # $1=jar  $2=name-regex (default: common session names)", "local jar=\"$1\" re=\"${2:-session|sid|sess|JSESSIONID|connect\\.sid|PHPSESSID|laravel_session}\"", "awk -v re=\"$re\" '", "/^#HttpOnly_/ { sub(/^#HttpOnly_/,\"\"); }   # strip jar HttpOnly marker", "/^#/ { next }                              # skip remaining comments", "NF>=7 && $6 ~ re { print $6\"=\"$7 }         # field6=name field7=value", "' \"$jar\" | tail -1"],
    'phase-1-session-fixation-regeneration-on-login': ["```bash"],
    'step-1-grab-a-pre-auth-session-the-server-hands-an-anonymous-client': ["curl -s -L -c \"$JAR_A\" \"https://$TARGET/login\" -o /dev/null", "PRE=$(get_cookie \"$JAR_A\"); echo \"pre-auth: $PRE\""],
    'step-1b-stronger-can-we-force-an-arbitrary-id-attacker-chosen-value': ["FIX=\"session=AAAAdeadbeefAAAA\""],
    'step-2-authenticate-while-carrying-the-pre-auth-forced-cookie-reuse-same-jar': ["curl -s -L -c \"$JAR_A\" -b \"$JAR_A\" -X POST \"https://$TARGET/login\" \\", "-d \"username=attacker@example.com&password=CorrectHorse1\" -o /dev/null", "POST=$(get_cookie \"$JAR_A\"); echo \"post-auth: $POST\""],
    'decision': [],
    'if-post-pre-value-unchanged-across-the-auth-boundary-and-that-value': [],
    'now-returns-authenticated-data-fixation-the-server-reused-the-anon-id': [],
    'if-the-forced-fix-value-is-accepted-and-authenticates-critical-fixation': [],
    'attacker-controls-the-id-no-email-xss-needed-to-plant-it': ["AUTH=$(curl -s -L -b \"$JAR_A\" \"https://$TARGET/api/me\")", "echo \"$AUTH\" | head -c 200", "**FP guard:** a value *change* is not automatically safe \u2014 some apps rotate the readable cookie but keep a stable server-side session keyed by a second cookie. Diff the FULL `Set-Cookie` set and confirm the *old* value is genuinely dead (Phase 2). Also confirm `/api/me` returns *your* identity, not a generic 200/landing page."],
    'phase-2-invalidation-on-logout': ["```bash"],
    'a-logs-in-for-real-fresh-jar-capture-a-s-live-session': ["curl -s -L -c \"$JAR_A\" -X POST \"https://$TARGET/api/login\" \\", "-H 'Content-Type: application/json' \\", "-d '{\"email\":\"attacker@example.com\",\"password\":\"CorrectHorse1\"}' -o /dev/null", "A=$(get_cookie \"$JAR_A\"); echo \"A=$A\""],
    'baseline-what-does-an-authenticated-api-me-look-like-for-a-capture-body-not-just-code': ["BEFORE=$(curl -s -L -b \"$JAR_A\" \"https://$TARGET/api/me\")"],
    'logout-a': ["curl -s -L -b \"$JAR_A\" -X POST \"https://$TARGET/api/logout\" -o /dev/null"],
    'replay-a-s-old-cookie-value-explicitly-do-not-reuse-the-jar-logout-may-have': [],
    'overwritten-it-compare-body-code-against-the-authenticated-baseline': ["AFTER=$(curl -s -L -H \"Cookie: $A\" \"https://$TARGET/api/me\" -w '\\n[%{http_code}]')", "echo \"AFTER: $AFTER\"", "**FP discipline (mandatory):**", "- Don't trust the status code. A cached/edge 200 or a generic SPA shell returns 200 for everyone. **Body-diff** `AFTER` against `BEFORE` \u2014 the finding is only real if `AFTER` still contains A's *unique identity marker* (email, user-id, CSRF token, account name).", "- Confirm with a **negative control**: a random/garbage cookie value must NOT return the same authenticated body. If garbage also yields 200 with user data, the endpoint isn't session-gated and there's no finding here.", "- Re-test after a **short delay** and from a **different IP** \u2014 some servers lazily expire on next access or pin sessions to IP."],
    'phase-3-invalidation-on-password-email-change-persistent-ato-core': ["```bash"],
    'this-is-the-real-two-session-flow-a-attacker-holding-a-stolen-old-session': [],
    'b-the-victim-who-changes-their-password-believing-it-revokes-access': [],
    'in-a-real-engagement-a-is-a-session-you-legitimately-captured-for-a-test-account': [],
    'that-you-also-control-as-b-never-use-a-real-third-party': [],
    '1-log-the-test-account-in-as-session-a-capture-it': ["curl -s -L -c \"$JAR_A\" -X POST \"https://$TARGET/api/login\" \\", "-H 'Content-Type: application/json' \\", "-d '{\"email\":\"victim@example.com\",\"password\":\"OldPass!1\"}' -o /dev/null", "SESSION_A=$(get_cookie \"$JAR_A\"); echo \"SESSION_A=$SESSION_A\"", "BEFORE=$(curl -s -L -H \"Cookie: $SESSION_A\" \"https://$TARGET/api/profile\")"],
    '2-log-the-same-account-in-as-session-b-separate-jar-the-victim-s-browser': ["curl -s -L -c \"$JAR_B\" -X POST \"https://$TARGET/api/login\" \\", "-H 'Content-Type: application/json' \\", "-d '{\"email\":\"victim@example.com\",\"password\":\"OldPass!1\"}' -o /dev/null"],
    '3-victim-session-b-changes-the-password': ["curl -s -L -b \"$JAR_B\" -X POST \"https://$TARGET/api/change-password\" \\", "-H 'Content-Type: application/json' \\", "-d '{\"old_password\":\"OldPass!1\",\"new_password\":\"BrandNew!2\"}' -o /dev/null"],
    '4-the-test-replay-the-old-session-a-captured-in-step-1': ["AFTER=$(curl -s -L -H \"Cookie: $SESSION_A\" \"https://$TARGET/api/profile\" -w '\\n[%{http_code}]')", "echo \"AFTER pw-change: $AFTER\"", "**Decision + FP discipline:**", "- Finding is confirmed only if `AFTER` returns 200 **and** the body still carries the account's unique data (body-diff vs `BEFORE`). A bare 200 on a public/SPA route is not proof.", "- Run the **garbage-cookie negative control** again to prove the endpoint is session-gated.", "- Repeat the identical flow for **email-change** (`/settings/email`) and for **logout-all-devices** \u2014 apps frequently invalidate the *acting* session (B) but not *sibling* sessions (A). That sibling-survival is the exact persistent-ATO primitive `hunt-ato` chains.", "- **Severity gate:** if the change-password endpoint also lacks a current-password / MFA step-up (per `hunt-mfa-bypass`), A can pivot from read-only to full takeover \u2192 escalate."],
    'phase-4-cookie-attribute-analysis': ["```bash", "curl -sI -L \"https://$TARGET/\" | grep -i '^set-cookie'", "- **HttpOnly** missing \u2192 cookie reachable via `document.cookie`. Only a finding **chained to a real XSS/DOM sink** (`hunt-xss`/`hunt-dom`) \u2014 note it, don't report standalone as High.", "- **Secure** missing \u2192 cookie sent over cleartext HTTP; pair with `hunt-tls-network` (downgrade/HSTS-gap) for a network-attacker chain.", "- **SameSite** missing/`None` \u2192 CSRF reachability; `SameSite=Lax` is bypassable via sibling-subdomain top-level navigation (Argo CD **CVE-2024-22424** class) \u2192 hand to `hunt-csrf`.", "- **`__Host-` / `__Secure-` prefix absent** \u2192 the session can be overwritten/fixated from a subdomain or non-secure context; its presence largely kills cookie-fixation, so flag the *absence* as the precondition for Phase 1."],
    'phase-5-session-id-entropy': ["```bash"],
    'collect-a-large-sample-200-of-freshly-issued-ids-l-is-required-a-302': [],
    'login-often-sets-the-cookie-on-the-redirect-target-not-the-first-response': ["N=200; SAMP=$(mktemp)", "for i in $(seq 1 $N); do", "J=$(mktemp)", "curl -s -L -c \"$J\" \"https://$TARGET/login\" -o /dev/null", "get_cookie \"$J\" | cut -d= -f2- >> \"$SAMP\"", "rm -f \"$J\"", "sort \"$SAMP\" | uniq -d | head            # duplicates = catastrophic (re-use)", "awk '{print length($0)}' \"$SAMP\" | sort -n | uniq -c   # length distribution", "Then analyse, don't eyeball:", "- **Sequential / monotonic** \u2014 `sort -n` the decoded values; a steady +1/+N delta = predictable.", "- **Decodable structure** \u2014 `base64 -d` / hex-decode each ID and look for embedded `userId`, unix timestamps, or PIDs.", "- **Bit entropy** \u2014 feed the raw bytes to `ent` or `dieharder`; NIST SP 800-63B wants \u226564 bits. 10 samples is far too few to claim anything \u2014 gather hundreds.", "- **FP guard:** a long random-*looking* token is not proof of strength; only structural decode + a large-sample entropy estimate is. Conversely a short token with high per-char entropy may still be fine \u2014 measure, don't count characters."],
    'phase-6-jwt-as-session': ["```bash", "JWT=\"eyJ...\"        # captured from Authorization: Bearer or a cookie"],
    'decode-header-payload-safely-base64url-padding-fix': ["b64url(){ local s=\"${1//-/+}\"; s=\"${s//_//}\"; printf '%s' \"$s===\" | base64 -d 2>/dev/null; }", "b64url \"$(cut -d. -f1 <<<\"$JWT\")\" | jq .   # header: alg, kid", "b64url \"$(cut -d. -f2 <<<\"$JWT\")\" | jq .   # claims: exp, iat, sub, jti", "- **`exp` missing or years out** \u2192 no expiry. **`jti` missing** \u2192 server cannot maintain a revocation list \u2192 logout can't truly revoke.", "- **Revocation test:** logout, then replay the *same* JWT against `/api/me`. If it still returns the user \u2192 tokens are not server-revocable; this is the JWT-session persistence finding. Body-diff to avoid a cached 200.", "- **Tampering (alg/kid/key-confusion) is owned by `hunt-api-misconfig`** \u2014 hand off `jwt_tool $JWT -T` / `-X a` there rather than duplicating it."],
    'phase-7-refresh-token-rotation-reuse-detection': ["```bash"],
    '1-obtain-a-refresh-token-login-or-oauth-token-then-rotate-it-once': ["RT1=$(curl -s -L -X POST \"https://$TARGET/api/login\" \\", "-H 'Content-Type: application/json' \\", "-d '{\"email\":\"victim@example.com\",\"password\":\"OldPass!1\"}' | jq -r '.refresh_token')"],
    '2-use-rt1-to-mint-a-new-access-token-server-should-return-a-rotated-rt2': ["R2=$(curl -s -L -X POST \"https://$TARGET/auth/refresh\" \\", "-H 'Content-Type: application/json' -d \"{\\\"refresh_token\\\":\\\"$RT1\\\"}\")", "RT2=$(jq -r '.refresh_token' <<<\"$R2\"); echo \"rotated? RT1!=RT2 -> $([ \"$RT1\" != \"$RT2\" ] && echo yes || echo NO-ROTATION)\""],
    '3-reuse-detection-test-replay-the-old-rt1-again-simulating-the-leaked-token': ["REPLAY=$(curl -s -L -X POST \"https://$TARGET/auth/refresh\" \\", "-H 'Content-Type: application/json' -d \"{\\\"refresh_token\\\":\\\"$RT1\\\"}\" -w '\\n[%{http_code}]')", "echo \"RT1 replay: $REPLAY\""],
    '4-then-confirm-rt2-was-killed-by-the-replay-correct-bcp-behaviour-invalidates': [],
    'the-whole-family-if-rt2-still-works-after-rt1-was-replayed-no-family-revocation': ["curl -s -L -X POST \"https://$TARGET/auth/refresh\" \\", "-H 'Content-Type: application/json' -d \"{\\\"refresh_token\\\":\\\"$RT2\\\"}\" -w '\\n[%{http_code}]'", "**Findings:** no rotation (RT1==RT2) = a long-lived stealable credential; rotation **without** reuse-detection (RT1 replay still mints tokens, or RT2 survives the replay) = the leaked-token-persistence bug per the OAuth Security BCP. **OOB note:** if you suspect a leaked RT via SSRF/log/JS-bundle, confirm the token's reach with `hunt-ssrf`/`hunt-source-leak`, not by guessing."],
    'phase-8-oauth-sso-session-linkage-dbsc-downgrade': ["```bash"],
    'sso-linkage-after-idp-callback-is-the-app-session-bound-to-the-idp-session': [],
    'log-out-at-the-idp-only-replay-the-app-session-cookie-still-200-with-user': [],
    'data-app-session-outlives-the-idp-session-single-logout-gap': [],
    'dbsc-downgrade-if-responses-carry-sec-session-registration-sec-session-id': [],
    'strip-the-device-bound-proof-header-and-replay-the-plain-cookie': ["curl -s -L -H \"Cookie: $A\" \"https://$TARGET/api/me\" -w '\\n[%{http_code}]'"],
    'if-the-plain-non-bound-cookie-is-still-accepted-device-binding-is-advisory': [],
    'not-enforced-a-stolen-cookie-defeats-dbsc-entirely': ["Hand OAuth `state`/`redirect_uri`/code-injection to `hunt-oauth`; this phase only covers the *session-layer* binding."],
    'chain-table': [],
    'validation-house-fp-discipline': ["Before claiming ANY session finding:", "- **Two real sessions, not placeholders** \u2014 every fixation/invalidation claim uses A and B captured by the `curl` flows above.", "- **Body-diff, never status-only** \u2014 a 200 means nothing without the account's unique identity marker present in the body, diffed against the authenticated baseline.", "- **Negative control** \u2014 a garbage/random cookie must FAIL where your \"surviving\" cookie succeeds; otherwise the endpoint isn't session-gated and it's a non-finding.", "- **Cache/edge check** \u2014 re-request with a cache-buster and from a second IP; rule out an edge-cached or IP-pinned 200.", "- **OOB for theft chains** \u2014 when the impact depends on exfiltrating a cookie/token (XSS, SSRF, log leak), confirm receipt out-of-band (Collaborator) rather than asserting it.", "- **Static-vs-state** \u2014 `HttpOnly`/`Secure`/`SameSite` absence is a *policy* observation; only report as High once paired with a real exploit primitive (XSS, network-MITM, CSRF). Standalone attribute gaps are Low/Informational.", "**Severity:**", "- Session fixation \u2192 admin/SSO takeover: **Critical**", "- No invalidation on password/email change, or refresh-token reuse without detection: **High \u2192 Critical** (escalate if MFA/step-up also absent)", "- Predictable/duplicate session ID: **High**", "- No invalidation on logout: **Medium \u2192 High** (depends on theft vector)", "- Missing `HttpOnly`/`SameSite` standalone: **Low/Informational** until chained"],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()